[Spring 지하철 노선도 관리 - 1,2단계] 조엘(조영상) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #102
Opened 2021-05-06 08:37 UTC by PapimonLikelion

안녕하세요 제이! 우테코에서 첫 미션을 함께 했었는데 오랜만이네요 :)
지하철 노선도 미션을 페어들과 함께 진행했어요!

> __[다음과 같은 사안이 궁금해요]__

__1. DTO가 레이어를 관통해도 괜찮을까요? + DTO는 어느 레이어까지 써야할까요?__
현재 저희 지하철 노선도는 Controller, Service, Dao를 관통하는 LineResponse와 StationResponse가 있어요. 
현재 지하철 노선도 미션에서 필요한 정보들이 각 레이어 별로 모두 비슷해 발생한 일이라고 생각해요. 

Dao에서 Line, Station 등의 도메인 객체를 생성하여 반환하자는 의견도 있었지만, 현재는 그렇게 구현하지 않았어요. 
Dao에서는 DB에서 정보만 뽑아서 Service에 주고, 이후 도메인 객체가 필요하다면 Service에서 해당 정보를 통해 도메인 객체를 생성하는게 맞다고 생각했어요. 
제공된 LineResponse와 StationResponse로 Dao에서 Service로 넘겨줄 정보들이 모두 표현 가능하여, 해당 두 클래스를 Dto 클래스 처럼 사용했어요. 

이렇게 서비스로 넘어온 LineResponse와 StationResponse는 그대로 컨트롤러에 넘겨줬어요. 
컨트롤러에 넘겨줄 정보들이 해당 클래스로 모두 표현이 가능했기에 그대로 넘겨줬어요. 

간단한 CRUD 로직을 쿼리문으로 구현했기 때문에 발생한 일 같아요. 
이렇게 작성된 코드가 조금 어색해보이네요! 제이의 생각이 궁금합니다!

__2. 테스트 마다 DB 세팅__
현재 저희의 Dao 테스트 코드에는 test/resources/schema.sql을 사전에 실행하여, DB를 초기화 시켜서 세팅해주어요. 

Dao 테스트 코드보다 Controller 테스트가 먼저 실행되면, Controller 테스트로 인해 DB가 채워졌었어요. 
DB가 초기화 된 상황을 가정하고 Dao 테스트들을 작성했던 터라, 테스트가 실패하는 경우가 발생헀어요. 
이를 해결하고자 @Sql("classpath:schema.sql") 해당 어노테이션을 통해 테이블을 새로 생성하도록 했어요. 

해당 방식을 처음 접해서, 현업에서는 이런방식도 쓰는지, 좋은 테스트 방식인지 궁금합니다. 

__3. Response 응답에 null을 포함하는 것__
LineResponse 클래스에서는 id, name, color, stations 필드를 필요로 해요. 
여기에서 stations에 대한 정보는 사실 필요가 없는 경우도 있었어요. 
stations 필드를 채워주지 않고 null인 상태에서 controller가 반환하도록 했어요. 

개발자 도구를 통해 보니 해당 네트워크로의 응답을 stations=[] 와 같이 받은 것을 알 수 있었어요. 
Null을 주의하라는 말을 많이 들어서 해당 코드가 조금 두려웠던 것 같아요. 
제이의 생각이 궁금합니다. 

읽어주셔서 감사합니다! 코로나 조심하시고 좋은 하루 되세요 😁

2021-05-07 13:09 UTC, JunHoPark93 requested changes
안녕하세요 조엘! 또뵙네요 :)
미션 잘 구현해주셨어요!
질문주신 부분들은 코멘트로 남겨두었는데 확인부탁드려요 🙏
궁금한점 생기면 언제든 다시 말씀주세요!

2021-05-07 13:09 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/line/LineDaoTest.java
> +@Sql("classpath:schema.sql")
두 번째 질문주신 부분입니다!
초기세팅이 필요한 부분에 이렇게 해주시는건 좋습니다~ 질문주신 컨트롤러테스트가 먼저 실행이 되면 안된다고 말씀주셨는데, 해당 컨트롤러 테스트가 끝나면 비워주는 작업을 해주면 되지 않나요? 
제가 잘못이해한거면 다시 말씀주세요!

2021-05-07 13:09 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/line/LineResponse.java
>      private List<StationResponse> stations;
세 번째 질문주신 부분입니다!

> stations 필드를 채워주지 않고 null인 상태에서 controller가 반환하도록 했어요.

되도록 null을 반환하지 않는게 좋습니다. 해당 필드는 리스트니 emptyList로 반환해주는 건 어떨까요?
혹은 LineResponse.emptyXXX(..)로 메서드를 만드는것도 방법일거같네요~

2021-05-10 03:45 UTC, PapimonLikelion commented on src/main/java/wooteco/subway/line/LineService.java
> +        LineResponse lineResponse = lineDao.findById(id);
Dao의 리턴값으로 도메인 객체를 반환하도록 변경했습니다!
서비스에서의 로직 작성이 더욱 간편해졌어요 :)

2021-05-10 03:48 UTC, PapimonLikelion commented on src/main/java/wooteco/subway/station/StationService.java
> +        long stationId = stationDao.save(stationName);
StationDao, LineDao에 각각 findByName, findById를 만들어 Optional을 반환하도록 하였습니다!

2021-05-10 03:59 UTC, PapimonLikelion commented on src/main/java/wooteco/subway/line/LineResponse.java
> +    public LineResponse() {
Jackson을 통한 JSON -> Java 객체 변환에서 기본 생성자가 없으면 변환이 안되는 에러를 마주한 적이 있었어요!
RequestBody 어노테이션을 사용해서 변환했었는데 에러가 발생했습니다. 
독특했던 게 필드값이 2개 이상인 자바 객체는 기본 생성자 없이, 두 가지 필드값을 생성자로 받으면 에러가 발생하지 않았었는데, 필드값이 하나인 자바 객체에서 생성자로 하나의 필드를 받으면 에러가 발생하더라구요.  
구글링을 조금 하다가 Jackson에서 기본생성자를 통해 java 객체를 생성한 후 필요한 처리를 해주는 것 같았습니다. 

https://velog.io/@conatuseus/RequestBody%EC%97%90-%EC%99%9C-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%A0%95%EC%9E%90%EB%8A%94-%ED%95%84%EC%9A%94%ED%95%98%EA%B3%A0-Setter%EB%8A%94-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-2-ejk5siejhh

혹시나 하는 마음에 우선 남겨뒀던 것 같아요!
RequestBody와 ResponseBody 어노테이션의 동작 방법과 Jackson 라이브러리의 동작 방법을 조금 더 살펴보겠습니다!

2021-05-10 04:01 UTC, PapimonLikelion commented on src/main/java/wooteco/subway/line/LineDao.java
> +    public LineResponse findById(long id) {
네! 그렇게 변경했습니다 :)

2021-05-10 04:02 UTC, PapimonLikelion commented on src/main/java/wooteco/subway/line/LineResponse.java
>      private List<StationResponse> stations;
네! Line도메인 생성시 List<Station>을 채울수 없다면 기본 생성자에서 new ArrayList<>() 를 할당해 주도록 변경했습니다!

2021-05-10 05:47 UTC, PapimonLikelion commented
안녕하세요 제이! 피드백 주신 것 바탕으로 리팩토링 진행했습니다!

> __[다음과 같은 리팩토링을 진행했어요]__

__1. Dao에서 도메인을 반환하도록 했어요__
피드백 주신대로 Dao에서 도메인을 생성하여 반환하도록 했어요.
확실히 도메인 생성을 Dao에서 해주니 Service 레이어에서는 바로 비즈니스 로직을 수행해줄 수 있어 편안했어요. 
Repository를 만들어서 도메인 객체 생성을 해주고, Dao에서 필요한 데이터 접근을 해주는 방식도 괜찮을 것 같다는 생각이 들었습니다. 

__2. DB에서 Unique로 중복 검사를 하기 전에 FindBy~로 먼저 중복검사를 진행해요__
Optional을 반환하는 형태로 findById, findByName 메서드를 StationDao, LineDao에 각각 만들어주었어요. 
해당 메서드를 만들어 서비스 단에서 중복 예외처리를 할 수 있었어요. 
확실히 DDL을 분석해서 중복이 안 된다는 것을 인지하는 것보다 더 가독성이 좋아진것을 느낄 수 있었어요. 

__3. 정적 팩토리 메서드로 도메인 객체를 DTO로 변환해줘요__
StationResponse, LineResponse에 Domain 객체를 매개변수로 넘겨주어 DTO를 생성하도록 리팩토링 진행했어요. 

__4. Response에서 Null 포함하지 않도록 변경했어요__
Dao에서 Line을 조회할 때 List<Station> 정보를 가져올 수 없다면, Line 도메인 내부 생성자에서 new ArrayList<>()를 넣어주어 null값이 필드값으로 존재하지 않도록 했어요. 

> __[다음과 같은 질문이 있어요]__

__1. FindBy~를 통해 Optional을 반환하는 것의 효율성에 대해 궁금해요__
기존의 코드에서는 중복 처리를 DB의 unique로 해줘서 어떤 값을 저장할 때 DB에 쿼리를 한번만 날리면 됐어요. 
하지만 이제 FindById를 통해 유효성검증을 진행하면서 쿼리를 한 번, 실제 저장할 때 쿼리를 한 번, 총 2번의 쿼리를 날려야 해요. 

이러한 방식으로 구현하여 분명히 서비스 코드의 가독성과 안전성은 확보된 것 같았지만, 불필요한 비용이 아닐까 생각이 들었어요.
DB 서버가 서비스 서버와 동떨어져 있으면 네트워크 비용도 2배로 발생하는 것 같고요. 
이 정도 처리는 가독성을 위해서 포기할 만한 수준인지 궁금합니다!

__2. Setter를 통해 필드를 수정해줘요__
LineDao의 Line 조회 메서드로는 온전히 Line을 생성할 수 없어요. 
LIne에 소속된 Station을 가져오기 위해 StationDao의 findStationIdsInLineByLineId 메서드를 실행시켜줘야 해요. 
따라서 LineService에서 불완전한 Line 도메인 객체를 전달받고, Line의 setStations메서드를 통해 findStationIdsInLineByLineId를 통해 변환한 List<Station>을 주입해줘요.
해당 객체의 필드를 마음껏 바꿔줄 수있는 setter는 지양되어야 한다고 생각해요. 

다른 크루들에게 해당 문제를 이야기 해보았고 해결 방법으로는, 
1. 쿼리문을 더욱 정교하게 작성하여 한 번의 쿼리문으로 필요한 정보들을 다 가져오도록 하고, 이를 통해 완전한 Line 도메인 객체 반환
2. LineDao와 StationDao가 있는 LineRepository를 만들어서, Line 도메인 객체에 필요한 필드들을 Dao를 통해 전달 받고, 온전한 Line 도메인 객체를 만들어 서비스에 반환

이 생각이 났어요. 

Repository에 대해 저보다 공부를 많이 한 크루가 Repository는 하나의 Dao만 가지도록 하는 것이 좋다고 해서 1번 방법이 좋지 않을까 하고 있었어요. 

제이의 생각이 궁금합니다!!

2021-05-10 14:29 UTC, JunHoPark93 approved these changes
안녕하세요 조엘!
피드백 반영하시느라 고생많으셨습니다 🙇‍♂️
어느부분을 중점적으로 변경하셨는지 정리까지 감사합니다 🙏
질문주신 부분은 코멘트로 남겨놓겠습니다!
궁금한점 언제든 남겨주세요~ 다음단계때 뵙겠습니다 🥳

2021-05-10 14:29 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/line/LineService.java
> +    }
```suggestion
        return lineDao.findById(lineId).orElseThrow(() -> new IllegalArgumentException(lineId + "에 해당하는.."));
```
요렇게 한줄로 하면 가독이 더 좋아질거에요~ 다른 optional 처리쪽도 마찬가지입니다

2021-05-10 14:31 UTC, JunHoPark93 commented
1. [https://github.com/woowacourse/atdd-subway-map/pull/103#issuecomment-835720862](https://github.com/woowacourse/atdd-subway-map/pull/103#issuecomment-835720862)

다른 크루분들도 해당 부분에 대해서 질문을 해주셨는데요, 해당 답변 링크를 첨부를 드릴게요! 혹시 부족하다면 다시 말씀 주세요~

2. 넵 무분별한 setter는 지양해야합니다. 필요하다면 setXXX보다는 보다 명시적인 이름을 짓고 내부에 validation도 있으면 좋겠죠. repository가 하나의 dao를 가지는게 좋다 라는건 지금처럼 작은 프로젝트에서는 괜찮아요. repository에서도 물론 여러 dao를 가질 수 있어요~ 말씀 주신 그런 문제를 해결하기 위해서 2개의 dao를 repository안에 위치시키고 한번에 조회해오는것도 방법입니다. 하지만 지금 미션에서는 굳이 repository까지 만들어서 할필요는 없어보이네요. 

일전에 다른 크루가 공유해준링크가 있는데요, [https://www.baeldung.com/java-dao-vs-repository](https://www.baeldung.com/java-dao-vs-repository) 저도 재밌게 읽었어요! 한번 참고부탁드려요~

2021-05-10 14:32 UTC, merged

2021-05-19 09:07 UTC, PapimonLikelion commented
# 배포 인프라
## 소켓
- 네트워크 통신 중 소켓에 대해 공부해봄
- https://papimon.tistory.com/80
- www.youtube.com/watch?v=Fh1GAi63CfA
- https://recipes4dev.tistory.com/153
- https://woowacourse.github.io/javable/post/2020-09-20-websocket/
- www.joinc.co.kr/w/Site/Network_Programing/Documents/IntroTCPIP

## 태그
- Network, Socket

## 접근 통제
- Bastion 서버를 도입해 직접적으로 서비스 22번 포트에 접근을 제한시키는 경험을 해봄
- https://github.com/PapimonLikelion/woowacourse-TIL/blob/master/Level2/2021-04-28-%EB%B0%B0%ED%8F%AC1%EB%8B%A8%EA%B3%84.md#%EC%A0%91%EA%B7%BC-%ED%86%B5%EC%A0%9C

## 태그
- Network, Security

2021-05-19 09:31 UTC, PapimonLikelion commented
# 지하철 첫 번째 미션
## Package By Feature vs Package By Layer
- 유지/보수에 용이한 패키지 구조에 대해 고민해본다.
- https://github.com/PapimonLikelion/woowacourse-TIL/blob/master/Level2/2021-05-10.md#%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B5%AC%EC%A1%B0-%EA%B3%A0%EB%AF%BC
- https://www.slipp.net/questions/36
- https://pasudo123.tistory.com/115

## 태그
- Package 구조

## Spring Test
- 상호 독립적인 테스트를 구현하는 방법을 공부함
- `@DirtiesContext`, `@Sql("~~.sql")`, `@Transactional` 어노테이션의 활용 공부
- https://github.com/PapimonLikelion/woowacourse-TIL/blob/master/Level2/2021-05-07.md#%EB%B8%8C%EB%9D%BC%EC%9A%B4-%EC%88%98%EC%97%85

## 태그
- Spring Test