[Spring 지하철 노선도 관리 - 1,2단계] 파피(김태완) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #106
Opened 2021-05-06 08:55 UTC by jujubebat

2021-05-08 11:56 UTC, dave915 requested changes
우기 안녕하세요! 리뷰를 맡게된 데이브입니다. 
미션 구현 잘 해주셨네요 ㅎㅎ
몇가지 피드백 남겼습니다.
진행하면서 궁금한점 있으면 편하게 질문 주세요 :)

2021-05-08 11:56 UTC, dave915 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +@Sql("classpath:tableInit.sql")
전 괜찮다고 생각합니다 👍 👍

2021-05-08 11:56 UTC, dave915 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +            .extract();
요청 하는 부분이 중복 되는데 중복 제거 할 수 없을까요?

2021-05-08 11:56 UTC, dave915 commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +    @ExceptionHandler(DuplicateException.class)
개발자가 예상하지 못한 오류에 대비해 Exception.class 를 처리하는 handler도 있으면 좋을 것 같아요 :)

2021-05-08 11:56 UTC, dave915 commented on src/main/java/wooteco/subway/line/LineController.java
> +    @GetMapping(value = "/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
`, produces = MediaType.APPLICATION_JSON_VALUE` 이 부분은 위쪽에`@RequestMapping("/lines", produces = MediaType.APPLICATION_JSON_VALUE)` 에 한번만 써줘도 될 것 같아요!

2021-05-08 11:56 UTC, dave915 commented on src/main/java/wooteco/subway/line/LineDao.java
> +        return createNewObject(line, keyHolder.getKey().longValue());
`keyHolder.getKey().longValue()` 에서 NullPointerException이 발생 할 가능성이 있다고 나오는데, 체크 해주는게 좋지 않을까요?

2021-05-08 11:56 UTC, dave915 commented on src/main/java/wooteco/subway/line/LineController.java
> +        this.lineDao = lineDao;
`layered architecture` 에서는 Controller layer에서 웹에 관련된 처리를 해주고, Service layer에서 도메인 및 비즈니스 로직 처리, Persistence layer에서 데이터를 저장하는 역할을 하고 있어요. 

그렇기 때문에 Controller에서 바로 Dao를 호출하기 보단 중간에 Service를 두면 좋을 것 같아요! 
음.. 이 피드백은 다음에 3단계에서 진행해도 될 것 같네요 ㅎㅎ 

참고 할 만한 링크 남길게요! 
https://walbatrossw.github.io/etc/2018/02/26/etc-layered-architecture.html

2021-05-09 01:42 UTC, jujubebat commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +            .extract();
메서드로 분리했습니다 😃

2021-05-09 01:43 UTC, jujubebat commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +    @ExceptionHandler(DuplicateException.class)
이 경우 클라이언트에게 어떤 에러 메세지를 보여주는게 적절할까요? "알 수 없는 오류 입니다."를 출력하는게 좋을지 아님 에러 메세지를 그대로 클라이언트에게 줘야하는지 잘 모르겠습니다. 저는 전자가 더 낫다고 생각하는데, 이렇게 하면 어떤 오류인지 알 수 없는 문제가 있다고 생각해서 고민 됩니다.

2021-05-09 01:44 UTC, jujubebat commented on src/main/java/wooteco/subway/line/LineController.java
> +    @GetMapping(value = "/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
중복되는 요소 수정했습니다 ㅎㅎ

2021-05-09 01:44 UTC, jujubebat commented on src/main/java/wooteco/subway/line/LineDao.java
> +        return createNewObject(line, keyHolder.getKey().longValue());
체크해줬습니다. 인텔리제이가 주는 힌트도 꼼꼼히 참고해야겠네요 😃

2021-05-09 01:46 UTC, jujubebat commented on src/main/java/wooteco/subway/line/LineController.java
> +        this.lineDao = lineDao;
### 레이어드 아키텍쳐 적용

처음 미션을 진행할때는 서비스 레이어의 필요성을 느끼지 못해서 만들지 않았습니다.
하지만 DB 예외처리 구조를 바꾸면서 Controller - Service - Repository 형태로 레이어드 아키텍쳐를 적용했습니다 ㅎㅎ
원래는 DB 관련 예외가 있을시(예를들어 없는 노선인데 조회, 업데이트, 삭제를 하는 경우.. 또는 중복된 이름의 노선, 역을 저장하는 경우) 
Dao에서 jdbcTemplate가 던져주는 예외를 그대로 받아 커스텀 예외 전환후 컨트롤러 어드바이스에서 잡아서 클라이언트에게 알려주는 구조였습니다.

하지만 DB와 상관 없이 애플리케이션 단에서 예외를 직접 체크하고 처리하는 것이 유지보수 측면에서 좋을 것 같다는 판단이 들었습니다. 
DB 스키마를 참고하지 않고, 애플리케이션 코드만 보고도 프로젝트의 비즈니스 로직을 파악할 수 있기 때문 입니다. (이 부분은 사실 다른 크루가 받은 피드백을 참고했습니다!)

결론적으로 지금 바뀌어진 구조에서는 서비스 레이어에서 DB 관련 예외 처리, 예외 발생을 수행하고 있습니다. 

### 동시성 문제?
```java
@Transactional
    public Line createLine(Line line) {
        if (lineRepository.isExistName(line)) {
            throw new DuplicateLineNameException();
        }
        return lineRepository.save(line);
    }
```

위와 같은 서비스 레이어 메서드에서 동시성 문제가 발생할 수 있다고 생각했습니다.
만약 2개의 쓰레드가 if문을 통과한후 `lineRepository.save(line);`를 수행한다면, 제가 의도했던 커스텀 예외 `DuplicateLineNameException`가 발생하지 않고 jdbcTemplate가 예외를 던지는 경우가 있을 것이라고 생각했습니다. 
이 경우 DB에는 문제 없이 데이터가 들어가겠지만, 의도한 예외 처리 구조가 동작하지 않는데, 이런 문제는 어떻게 해결하는지 궁금합니다.


### 테스트 코드 작성
아직 인수 테스트, 통합 테스트, 단위 테스트 그리고 스프링에서 사용할 수 있는 여러가지 테스트 방법에 대해 학습을 하지 못했습니다.
처음에 주어진 테스트 코드를 참고하며 테스트 코드 작성을 진행 했습니다. 컨트롤러 단은 인수 테스트를 진행했고 서비스, 레포지토리 단은 메서드 단위 테스트를 진행했습니다. 아직 공부가 부족하여 어떤 상황에서 어떤 의미를 부여하며 어떤 테스트를 진행하는게 좋은지 잘 모르겠습니다. 이제 테스트에 중점을 두고 학습을 해보려고 하는데 관련해서 조언주시면 감사하겠습니다 !

2021-05-09 02:56 UTC, jujubebat commented
### 레이어드 아키텍쳐 적용

처음 미션을 진행할때는 서비스 레이어의 필요성을 느끼지 못해서 만들지 않았습니다.
하지만 DB 예외처리 구조를 바꾸면서 Controller - Service - Repository 형태로 레이어드 아키텍쳐를 적용했습니다 ㅎㅎ
원래는 DB 관련 예외가 있을시(예를들어 없는 노선인데 조회, 업데이트, 삭제를 하는 경우.. 또는 중복된 이름의 노선, 역을 저장하는 경우) 
Dao에서 jdbcTemplate가 던져주는 예외를 그대로 받아 커스텀 예외 전환후 컨트롤러 어드바이스에서 잡아서 클라이언트에게 알려주는 구조였습니다.

하지만 DB와 상관 없이 애플리케이션 단에서 예외를 직접 체크하고 처리하는 것이 유지보수 측면에서 좋을 것 같다는 판단이 들었습니다. 
DB 스키마를 참고하지 않고, 애플리케이션 코드만 보고도 프로젝트의 비즈니스 로직을 파악할 수 있기 때문 입니다. (이 부분은 사실 다른 크루가 받은 피드백을 참고했습니다!) 동시에 애플리케이션 코드가 DB에 덜 의존하게 된다고 생각합니다.

결론적으로 지금 바뀌어진 구조에서는 서비스 레이어에서 DB 관련 예외 처리, 예외 발생을 수행하고 있습니다. 
이 부분에서 리뷰어마다 크루마다 의견이 다 다른것 같습니다. 

1. 애플리케이션에서 직접 예외를 발생시키고 처리한다.
2. DB에서 던저주는 예외를 사용한다. 
3. 둘 다 적용한다.

데이브는 어떤 의견을 가지고 계신지 궁금합니다! 관련해서 조언 많이 주시면 감사하겠습니다. 

### 동시성 문제?
```java
@Transactional
    public Line createLine(Line line) {
        if (lineRepository.isExistName(line)) {
            throw new DuplicateLineNameException();
        }
        return lineRepository.save(line);
    }
```

위와 같은 서비스 레이어 메서드에서 동시성 문제가 발생할 수 있다고 생각했습니다.
만약 2개의 쓰레드가 if문을 통과한후 `lineRepository.save(line);`를 수행한다면, 제가 의도했던 커스텀 예외 `DuplicateLineNameException`가 발생하지 않고 jdbcTemplate가 예외를 던지는 경우가 있을 것이라고 생각했습니다. 
이 경우 DB에는 문제 없이 데이터가 들어가겠지만, 의도한 예외 처리 구조가 동작하지 않는데, 이런 문제는 어떻게 해결하는지 궁금합니다.

### 테스트 코드 작성
아직 인수 테스트, 통합 테스트, 단위 테스트 그리고 스프링에서 사용할 수 있는 여러가지 테스트 방법에 대해 학습을 하지 못했습니다.
그래서 처음에 주어진 테스트 코드를 참고하며 테스트 코드 작성을 진행 했습니다. 컨트롤러 단 api는 인수 테스트를 진행했고 서비스, 레포지토리 단은 메서드 단위 테스트를 진행했습니다. 

원래 저는 상위 모듈에 대한 테스트만 문제없이 통과하면 된다고 생각했습니다. 예를들어 레이어드 아키텍쳐 구조에서 컨트롤러 단 테스트만 문제 없으면, 자동으로 서비스, 레포지토리 레이어에 대한 검증이 이루어진다고 생각했습니다. 하지만 이번에는 서비스, 레포지토리 레이어에 대한 테스트도 진행했습니다. 이렇게 하니 좀 더 마음의 안정이 생기긴 했습니다. 데이브께서는 어떤 기준을 세우고 테스트 코드를 작성하는지 궁금합니다. (다시 생각해보니 TDD를 엄격히 진행하면 모든 컴포넌트에 대한 테스트 코드는 자동으로 따라오겠네요..)

아직 공부가 부족하여 어떤 상황에서 어떤 의미를 부여하며 어떤 테스트를 진행하는게 좋은지 사실 잘 모르겠습니다. 이제 테스트에 중점을 두고 학습을 해보려고 합니다. 관련해서 조언주시면 감사하겠습니다 !

2021-05-09 12:52 UTC, dave915 commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +    @ExceptionHandler(DuplicateException.class)
`e.getMessage()` 를 그대로 내보내 주면 어플리케이션 내부에 패키지 구조 또는 사용 기술이 외부로 노출 될 수 있기 때문에, 
`e.getMessage()`는 로그로 남기고 응답 메세지에는 `"알 수 없는 오류 입니다."` 를 전달해주면 좋을 것 같아요!

2021-05-09 13:01 UTC, dave915 commented
>동시성 문제?

저는 어플리케이션에서 체크, DB에서 발생하는 오류도 체크 해야한다고 생각해요. 말씀 주신대로 DB에서 발생한 오류는 두가지 경우에 따라 처리 방법이 달리 질 것 같아요. (사실 다른 경우도 모두 동일해요)
1. 중복 발생 확인 후 또 다른 로직 처리 -> try-catch를 이용해 이후 처리함.
2. 중복 발생 확인 후 API 오류 발생 -> ControllerAdvice 에서 Exception을 잡아서 처리 

>테스트 코드 작성

어플리케이션이 커지면서 외부 API 를 요청하는등 개발자가 컨트롤하기 힘든 부분이 생기고 이부분을 Mocking 해서 처리하는 경우가 생겨요. 
말씀주신대로 최상위 레이어 테스트만 진행시 모든 변수를 고려하면서 진행 하여야 하기 때문에 테스트 작성이 힘들어지는 경우가 있을 듯 하네요 ㅠㅠ
또한, 하위 레이어만 테스트 하면 되는데 최상위 레이어 테스트만 작성되어있는경우 불필요한 Bean을 모두 Load해야하는 단점도 있어요.  

각 테스트 관련된 목적에 관한 링크와 테스트 방법에 관한 링크 남길게요! 
https://joont92.github.io/tdd/%EC%9D%B8%EC%88%98%ED%85%8C%EC%8A%A4%ED%8A%B8-%EB%8B%A8%EC%9C%84%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%86%B5%ED%95%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%A0%84-%EA%B5%AC%EA%B0%84-%ED%85%8C%EC%8A%A4%ED%8A%B8/

https://cheese10yun.github.io/spring-guide-test-1/

2021-05-09 13:14 UTC, dave915 approved these changes
우기 피드백 반영 한 부분 확인했어요! 
질문하신 부분에 관한 코멘트와 간단한 피드백 남겼어요 :) 
이번 단계는 이만 머지할게요 😁

2021-05-09 13:14 UTC, dave915 commented on src/main/java/wooteco/subway/line/service/LineService.java
> +        throw new NotExistLineException();
이렇게 해도 될 것 같아요 :) 
```suggestion
        return lineRepository.findById(id)
                .orElseThrow(NotExistLineException::new);
```

Optional 관련된 링크도 남길게요! 
https://www.latera.kr/blog/2019-07-02-effective-optional/

2021-05-09 13:14 UTC, dave915 commented on src/main/java/wooteco/subway/line/service/LineService.java
> +    @Transactional
클래스 상단에 한번만 붙여도 전체에 적용됩니다 :) 
```
@Transactional
public class LineService {
```

2021-05-09 13:14 UTC, dave915 commented on src/main/java/wooteco/subway/line/controller/LineAdvice.java
> +public class LineAdvice {
line, station 모두 `subway.exception` 에 있는 Exception을 쓰고 있는 것으로 보이는데, 여러개로 나누어진 Advice를 `subway.exception` 하위에 하나로 합치는건 어떠신가요?

2021-05-09 13:14 UTC, merged

2021-05-15 17:02 UTC, jujubebat commented on src/main/java/wooteco/subway/line/controller/LineAdvice.java
> +public class LineAdvice {
각 도메인 별로 Advice를 분리하면 예외처리 관련 유지보수가 좋아질 것이라고 생각했습니다. 
exception도 도메인 별로 패키지를 나누어 관리하려고 했는데, 부모 예외를 상속하는 예외들이 떨어져 있는게 어색하다고 생각해서 
한 패키지에 관리했습니다. 

하나의 Advice가 모든 예외를 핸들링하게 해도 괜찮은가요? 예외가 많아질 경우 Advice가 커질 것 같은데 문제가 없는지 궁금합니다!

2021-05-16 07:01 UTC, jujubebat commented on src/main/java/wooteco/subway/line/service/LineService.java
> +        throw new NotExistLineException();
가독성이 더 좋은 방법 알려주셔서 감사합니다 😃

2021-05-16 07:05 UTC, jujubebat commented on src/main/java/wooteco/subway/line/service/LineService.java
> +    @Transactional
반영 했습니다!!
DB에서 값을 조회하는 메서드에는 readOnly 옵션을 따로 붙여줬습니다.

어노테이션 순서에 대해서 궁금증이 생겼는데, 중요한 순으로 아래서 위로 배치하나요? 

예를들어 LineService에 어노테이션들을 아래와 같이 붙이면 될까요?

```java
@Transactional
@Service
public class LineService {
```

2021-06-23 01:08 UTC, jujubebat commented
# [Testing] TDD - 2
## 내용
- 테스트 코드를 작성하며 프로젝트를 진행하는 경험을 통해, TDD의 중요성을 깨닫고 공부함 
## 태그
tdd

# [Testing] ATDD - 2
## 내용
- 인수 테스트 주도 개발 개념에 대해서 학습함
- https://www.youtube.com/watch?v=ITVpmjM4mUE
## 태그
atdd