[Spring 지하철 노선도 관리 - 3단계] 알리(허진호) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #115
Opened 2021-05-09 15:07 UTC by jh8579

3단계 커밋을 가져오면서 1,2단계 피드백으로 적용한 부분들 충돌 해결하는 과정에서 시간이 좀 걸렸네요...
자잘한 이슈들 다 해결하고 테스트코드, 동작 확인 다 확인했습니다.
감사합니다!

2021-05-10 12:07 UTC, wbluke requested changes
3단계 빠르게 진행해주셨네요 ㅎㅎ
몇 가지 피드백 남겼으니 확인해 주세요 🙂

2021-05-10 12:07 UTC, wbluke commented on src/main/java/wooteco/subway/line/service/LineService.java
>      @Transactional
트랜잭션 readOnly 옵션도 한번 알아보아요 :)

2021-05-10 12:07 UTC, wbluke commented on src/main/java/wooteco/subway/line/service/LineService.java
> +            .map(this::findStationById)
Station의 수만큼 쿼리가 나갈 것 같은데요. 다음과 같이 개선해보는건 어떨까요?

1. stationIds를 쿼리 in절에 넣어 한번에 Station들을 조회
2. id를 기반으로 한 map 생성
3. orderedStations의 순서에 따라 map에서 Station 조회하여 응답 구성

2021-05-11 09:01 UTC, jh8579 commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +        Set<Long> sectionsIds = lineRoute.getStationIds();
수정했습니다

2021-05-11 09:08 UTC, jh8579 commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +                .equals(section.getUpStationId()))
매번 리뷰받는 내용인데도 습관적으로 getter를 사용하게 되네요
getter를 사용할 때마다 객체에게 메세지를 보낼 수 있을까 한번씩 생각해보려구요!

2021-05-11 12:18 UTC, jh8579 commented on src/main/java/wooteco/subway/line/service/LineService.java
> +            .map(this::findStationById)
station 수만큼 쿼리가 나가던 것을, 말씀해주신대로 한번의 쿼리로 받아오도록 수정했습니다

2021-05-12 15:18 UTC, wbluke requested changes
피드백 반영 깔끔하게 해주셨는데요! 👍 
마지막으로 추가하신 부분에 한가지만 짚고 넘어가면 좋을 것 같아서요ㅎㅎ 
확인 후 재요청 부탁드려요 🙂

2021-05-12 15:18 UTC, wbluke commented on src/main/java/wooteco/subway/ExceptionControllerAdvice.java
> +        System.out.println("[ERROR] " +  error.getMessage());
Spring에서는 sout 대신 log를 사용하도록 해요 :)

2021-05-12 15:18 UTC, wbluke commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
comsumes, produces 지정이 필요한가요? :)

2021-05-12 15:18 UTC, wbluke commented on src/main/java/wooteco/subway/section/controller/SectionController.java
> +    @DeleteMapping(value = "")
이전처럼 굳이 value를 명시할 필요가 없으면 안하는 것이 좋아보여요 :)

2021-05-14 02:20 UTC, jh8579 commented on src/main/java/wooteco/subway/ExceptionControllerAdvice.java
> +        System.out.println("[ERROR] " +  error.getMessage());
로그를 남기는 방법으로 수정했습니다.

2021-05-14 02:20 UTC, jh8579 commented on src/main/java/wooteco/subway/section/controller/SectionController.java
> +    @DeleteMapping(value = "")
수정했습니다!

2021-05-14 02:23 UTC, jh8579 commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
cosumes, produces를 사용해서 어떤 값을 받고 반환 하는지 명시해주려고 했는데,
너무 불필요한 작업일까요?

2021-05-14 02:32 UTC, wbluke commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
RestController에서는 기본적으로 Json 요청/응답이니, 명시하는게 오히려 가독성이 더 떨어진다고 생각해요 :)

2021-05-14 02:35 UTC, jh8579 commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
아 그렇게 생각하니 불필요하다고 생각이 드네요. 제거했습니다!

2021-05-14 02:37 UTC, wbluke approved these changes
지하철 첫 미션 고생 많으셨어요! 👍 
다음 미션도 화이팅입니다 🙂

2021-05-14 02:37 UTC, wbluke commented on src/main/java/wooteco/subway/ExceptionControllerAdvice.java
> +        LOG.warn(error.getMessage());
warning 보다는 error 로그 레벨이 더 맞지 않을까 하네요 :)

2021-05-14 02:37 UTC, wbluke commented on src/main/java/wooteco/subway/ExceptionControllerAdvice.java
> +    private static final Logger LOG = LoggerFactory.getLogger(ExceptionControllerAdvice.class);
로그 잘 적용해 주셨네요 👍

2021-05-14 02:38 UTC, merged