[Spring 지하철 노선도 관리 - 3단계] 루트(김준근) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #125
Opened 2021-05-11 08:56 UTC by Junroot

안녕하세요 제이! 루트입니다!
각 레이어 별로 명확하게 구분해서 설계를 하는게 처음이라 무척 힘들었네요 😅
코드 완전 지우고 새로 시작만 3번 한 것 같습니다 ㅠㅠ
아래는 미번 미션을 진행하면서 생긴 질문들 입니다!

## DB구조와 도메인 로직의 구조
처음에 미션을 진행하면서 최대한 DB의 구조에 의존적이지 않게 구현해보고자 했습니다. 하지만 DB에 저장하거나 불러올 때 도메인 구조와 달라서 코드가 복잡해져서 포기했습니다. 저같은 경우는 아래와 같은 문제를 겪었습니다.

> 도메인 객체에서는 노선이 구간을 가지고 있지만, DB에서는 구간이 노선 정보를 가지고 있다. 그래서 새로운 노선을 저장할 때 문제가 발생한다. 1. DB의 입장에서는 노선을 먼저 저장하고 구간을 저장해야된다. 2. 도메인 객체 입장에서는 구간을 먼저 생성하고 노선을 생성해야된다. 하지만 DB에 먼저 노선을 저장해야되기 때문에, 구간을 생성할 수 없다.

상황 설명이 제대로 됐을지 잘 모르겠네요 😅 위의 상황 뿐만 아니라 도메인과 DB 설계다 달라지만 많은 부분에서 코드가 복잡해지는 문제를 겪었습니다. DB 구조에 의존적인 도메인을 설계는 어쩔 수 없는 걸까요? 보통 이런 문제를 어떻게 해결하는지 궁금합니다.

## 단위 테스트를 어디까지 해야되는가

이번에 미션 진행하면서 단위테스트가아닌 인수테스트를 기반으로 개발을 진행했습니다.(ATDD) 모든 요구사항을 다 만족한 후 단위 테스트도 필요할 것 같다는 필요성을 느껴서 도메인부터 단위 테스트도 작성했습니다. 하지만 도메인을 제외한 다른 레이어의 경우에는 다른 레이어와 많은 의존을 갖는다는 점 때문에 결국에 하지 않았습니다. 특히 `SectionService` 같은 경우에는 3개의 클래스와 의존관계를 맺고 있어서 Mocking하고 단위 테스트하기에는 너무 많은 비용이 든다고 생각이 들었습니다. 구현하고자 하는 로직에 비해 필요이상으로 많은 (인적)비용이 발생하는 서비스 레이어의 경우에는 단위 테스트를 하는게 맞을지 의문이 듭니다. 이미 인수테스트로 통합테스트로 충분히 되었다고 생각이드는데, 제이의 경우에는 이와 같은 상황에서 어떻게 해결하는지 궁금합니다.

이번에도 좋은 리뷰 잘 부탁드립니다!!

2021-05-12 09:50 UTC, JunHoPark93 requested changes
안녕하세요 루트!
많은 고민을 하셨네요 고생많으셨어요 👍
몇가지 피드백 남겼는데 확인부탁드려요!
궁금한점은 언제든 남겨주세요

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
> +            .line(lineDao.save(new Line(lineRequest.getName(), lineRequest.getColor())));
첫 번째 질문주신 부분과 연관이 있을거같은데요,
엔티티와 도메인을 다르게 보시고 작성해주신거같아요! 당연히 둘은 다르지만 현재는 같은것으로보고 만드셔도 무방하다고 생각해요. Line 도메인에 대한 로직이 현재 Line내부에 존재하지 않아 작성해주신 LineEntity와 차이가 없기 때문이기도하구요.
다시 원복하라고 말씀드리는건 아닙니다. 지금의 엔티티와 도메인을 구분하는 시도도 충분히 좋다고 생각해요~

그리구 말씀주신  `2. 도메인 객체 입장에서는 구간을 먼저 생성하고 노선을 생성해야된다`.  에서 구간을 먼저 생성하는것도 괜찮을거같은데 어떻게 생각하시나요? 다른 문제가 있었다면 말씀주세요~

> 상황 설명이 제대로 됐을지 잘 모르겠네요 😅 위의 상황 뿐만 아니라 도메인과 DB 설계다 달라지만 많은 부분에서 코드가 복잡해지는 문제를 겪었습니다. DB 구조에 의존적인 도메인을 설계는 어쩔 수 없는 걸까요? 보통 이런 문제를 어떻게 해결하는지 궁금합니다.

양쪽다 장단점이 있는거같아요! 비슷한 [코멘트](https://github.com/woowacourse/atdd-subway-map/pull/120#discussion_r630108854)를 남겼는데 확인해보시고 궁금한점이 있다면 다시 말씀주세요!

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
> +            .line(lineDao.save(new Line(lineRequest.getName(), lineRequest.getColor())));
오히려 Line을 도메인으로 만드셨다면 Line조회시 역과 구간정보를 보여줘야하기때문에 해당 필드들을 Line도메인에서 가지고 있는것도 좋겠네요! 이부분은 고민해보셔요~

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
> +                lineEntity.getColor()))
Line 목록 조회시에는 구간의 정보는 보여주지 않아도 되는건가요? 🤔

2021-05-12 09:50 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/domain/ConstructionTest.java
> +public class ConstructionTest {
새로이 만든 집합의 개념도 테스트를 잘 해주셨네요 👍

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
> +        sectionService.insertSection(line, section);
사소한 걸수도있지만 생성이라는 의미를 create, insert 를 혼용해서 사용하면 추후 용어가 헷갈릴수있어요. 한가지만 선택해서 사용하는건 어떨까요?

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Construction.java
> +    }
결과적으로 액션을 취할(생성 혹은 삭제) 리스트를 내부에서 가져고오고있는데요, Construction이라는 객체를 보면 아래 두 필드의 상태를 보고있어요.
* sectionsToCreate
* sectionsToRemove

이 두 메서드도 insertSection(...) 처럼 내부에서 validateSectionToInsert() 를 불러줘야하지 않을까요?
이미 construct가 끝난 객체에서 sectionsToCreate()를 부르면 계속 추가될 sections가 반환이 될거니까요.

상태를 보고 로직을 만들때 예외상황을 잘 처리하지않으면 의도치 않은 버그가 생길수있어요.
Consctruction테스트에서도 이미 작업이 끝난것에 대해 sectionsToCreate를 부르면 예외가 발생하는 (혹은 다른방도가 있다면 그렇게 하셔도되구요) 테스트도 추가하면 좋을거같아요~

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +public class SectionService {
두번째 질문에 해당하는 부분입니다!

> 단위 테스트를 어디까지 해야되는가
> 이번에 미션 진행하면서 단위테스트가 아닌 인수테스트를 기반으로 개발을 진행했습니다.(ATDD) 모든 요구사항을 다 만족한 후 단위 테스트도 필요할 것 같다는 필요성을 느껴서 도메인부터 단위 테스트도 작성했습니다. 하지만 도메인을 제외한 다른 레이어의 경우에는 다른 레이어와 많은 의존을 갖는다는 점 때문에 결국에 하지 않았습니다. 특히 SectionService 같은 경우에는 3개의 클래스와 의존관계를 맺고 있어서 Mocking하고 단위 테스트하기에는 너무 많은 비용이 든다고 생각이 들었습니다. 구현하고자 하는 로직에 비해 필요이상으로 많은 (인적)비용이 발생하는 서비스 레이어의 경우에는 단위 테스트를 하는게 맞을지 의문이 듭니다. 이미 인수테스트로 통합테스트로 충분히 되었다고 생각이드는데, 제이의 경우에는 이와 같은 상황에서 어떻게 해결하는지 궁금합니다.

도메인에 대한 테스트는 루트가 잘 작성해주신것처럼 항상 해야합니다. 서비스같은 경우는 저는 너무 간단한경우 아니면 하는편이에요. 왜냐면 통합테스트를 매번 돌리기 힘든 경우가 있기도해요. (매번 호출하기 민감한 경우)
예를 들어, 외부서비스와 연계되어있는 경우가 있는데요, 그런 경우는 repository쪽을 mocking하여 서비스레이어를 테스트합니다. repository가 몇번호출되었는지 등등. 
하지만 이렇게 간단한 서비스는 통합테스트만 해도 괜찮을거같다는 생각입니다!

2021-05-12 09:50 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/entity/SectionEntity.java
> +public class SectionEntity {
말씀주신것처럼 구조를 3번이나 바꿀정도로 많은 고민을 하신게 멋지네요 👍
엔티티를 분리해보신게 정말 좋은시도라고 생각합니다

2021-05-12 19:08 UTC, Junroot commented on src/main/java/wooteco/subway/domain/Construction.java
> +    }
Construction 을 여러 번 사용 가능하도록 수정해봤습니다! 😊

2021-05-12 19:09 UTC, Junroot commented on src/main/java/wooteco/subway/service/LineService.java
> +            .line(lineDao.save(new Line(lineRequest.getName(), lineRequest.getColor())));
말씀하신대로 수정해봤는데 생각보다 많은 부분에 수정이 필요하네요 😅

2021-05-13 15:22 UTC, JunHoPark93 approved these changes
안녕하세요 크로플!
상대적으로 많은 수정이 필요한 부분도 빠르게 수정해주셨네요 🙏
고생많으셨습니다. 
다음 미션도 언제나 화이팅입니다 🥳

2021-05-13 15:22 UTC, merged

2021-05-17 16:28 UTC, Junroot commented
# 학습 로그
## 트랜잭션
- `@Transactional` 어노테이션을 사용하여 각 API마다 원자성과 일관성을 가지도록 구현했다.
- https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction
- https://taetaetae.github.io/2016/10/08/20161008/
## 태그
- Spring

## DTO
- DTO를 사용함으로써 도메인 객체가 뷰에 의존적이지 않게 보호할 수 있수 있었다.
- https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md
## 태그
- Spring

## 서비스 레이어
- 서비스 레이어간의 계층을 명확하게 설계하여 순환 참조를 방지하고, 코드 재사용성을 높였다.
- https://velog.io/@sumusb/Spring-Service-Layer%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0
- https://webdevtechblog.com/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%88%9C%ED%99%98-%EC%B0%B8%EC%A1%B0-circular-reference-d01c6beee7e6
## 태그
- Spring

## Entity 객체
- Entity 객체와 도메인 객체를 별도로 분리하여 SQL과 객체 지향 설계의 패러다임 불일치를 해결했다.
- https://velog.io/@asdfg5415/SQL%EA%B3%BC-JPA
## 태그
- SQL, Spring