[Spring 지하철 노선도 관리 - 3단계] 아론(장세환) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #126
Opened 2021-05-11 09:01 UTC by Sehwan-Jang

안녕하세요 미립! 3단계 구현이 꽤 어려워서 시간이 조금 걸렸습니다. 

3단계를 진행하면서 도메인 로직 구현을 제외하고 가장 고민이 되었던 부분들은 아래 사항들이었습니다.
+ 설계의 방향 (도메인 -> controller 혹은 controller -> 도메인)
+ 테스트 작성 범위

## Q1. API 설계 방향
지하철 미션을 시작할 때 이미 DB 테이블과 DDL이 제공되었습니다. 따라서 저와 페어는 레벨1 에서 진행했던 방식처럼 도메인을 우선적으로 구현하할 시 이후에 DB 연결과정에서 도메인과 DB 단의 괴리 때문에 많은 문제가 발생할 것이라 예상하여 Controller 부분부터 `Controller -> Service -> Dao -> 도메인`의 흐름으로 구현하였습니다.
레벨 1에서 수행했던 설계방향과 다른 방향으로 구현했음에도 크게 문제 되는 점을 느끼지 못하여, 이에 대해 어떤 방법이 더 바람직한 것인지, 혹은 취향차이 인지 잘 모르겠어서 미립의 의견이 궁금해요.

## Q2. 테스트의 범위
이미 1-2 단계에서부터 EtoE 테스트를 작성하라는 요구사항이 있었기에, 기능 단위로 EtoE 테스트를 작성하고 기능을 구현해나가는 방향으로 구현했습니다. 하지만 처음부터 EtoE 테스트를 작성하고나니 보다 세분화한 단위테스트나 통합테스트들을 언제 작성해야할지, 아니면 아예 작성할 필요가 있는지에 대한 고민이 들었습니다. (사실 EtoE 테스트를 통과한다는 것 자체가 모든 부분들이 정상작동하고 있다는 것을 의미한다고 생각합니다.)
물론, 제가 도메인 부터가 아니라 컨트롤러 단 부터 구현을 시작하여 이러한 고민이 들었던 것 같기도 합니다. (도메인 부분부터 구현했다면 적어도 도메인 부분은 단위테스트로 TDD를 하는 방식으로 진행했을 것 같아요) 하지만 그렇다 해도, 서비스나 DAO, 컨트롤러 등 모든 단위에서 테스트가 필요한지에 대해 어떻게 생각하지는지 질문드립니다.

## 
부족하지만, 제 코드 봐주셔서 감사합니다 😊

ps. 1-2단계 리팩토링 중에 실시간 DM으로 강의(?) 해주신 것도 너무 좋았아요. 신선하기도 하고 정말 많이 배운 것 같아요 ㅎㅎ

2021-05-11 09:25 UTC, seok-2-o requested changes
안녕하세요 아론. 
3단계 미션도 빠르게 진행해주셨네요 💯 

코드 관련하여 몇가지 코멘트 남겨 놓았어요. 확인 후 리펙토링 해주세요.

Q1. 구현을 Inside Out 으로 하던지 Outside In 으로 하던지 큰 차이는 없을 것 같아요.
개인적으로는 시스템에 대한 이해도가 높을 경우 Outside In 를 선택하고, 이해도가 떨어질 경우 Inside Out을 선택하는게 좋은 것 같아요.

>사실은 상향식, 하향식 둘 다 TDD의 프로세스를 효과적으로 설명해 줄 수 없다. ... 만약 어떤 방향성을 가질 필요가 있다면 '아는 것에서 모르는 것으로(known-to-unknown)' 방향이 유용할 것이다. 우리가 어느 정도의 지식과 경험을 가지고 시작한다는 점, 개발하는 중에 새로운 것을 배우게 될 것임을 예상한다는 점 등을 암시한다. Test-Driven Development, kent beck

Q2. 저는 모든 레이어에 대한 **단위 테스트가 작성 되어야 한다고 생각**하며, 
추가적으로 지금 인수테스트를 진행하고 있으니 통합테스트도 작성하는 것이 좋다고 생각해요.

레이어간 테스트가 중복되어 불필요하단 느낌을 받는다면 불필요한 레이어를 만들지 않았나 고민해보는것도 좋을 것 같아요.

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/exception/SectionAdditionException.java
> +public class SectionAdditionException extends RuntimeException {
RuntimeException 을 바로 쓰는 것보다 그룹 지을 수 있는 부분을 묶어주는 것도 좋더라구요
```
ㄴ RuntimeException
     ㄴ ServiceException
            ㄴ SectionException
                   ㄴ SectionAdditionException
            ㄴ LineException
```

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/api/dto/LineDetailsResponse.java
> +
저는 개행에도 의미를 부여하는데 아론은 어떤가요 ?

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/api/dto/LineDetailsResponse.java
> +    public LineDetailsResponse() {
기본 생성자가 필요 없다면 접근제어자를 변경하거나 삭제하는것도 좋을 것 같아요.

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/api/dto/LineRequest.java
>      private int distance;
JSR380 💯

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/service/LineService.java
> +    public void update(Long id, @Valid LineUpdateRequest lineRequest) {
`@Valid` 해당 어노테이션이 서비스에서도 동작하나요 ?-?

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/dao/SectionDao.java
> +    public void save(Long lineId, LineRequest lineRequest) {
Repository(Dao) Layer 까지 DTO가 내려와도 괜찮을까요 ?

![image](https://user-images.githubusercontent.com/34270397/117790628-82834400-b284-11eb-9032-e329a60e121c.png)

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/dao/SectionDao.java
> +    public void save(Long lineId, LineRequest lineRequest) {
https://www.petrikainulainen.net/software-development/design/understanding-spring-web-application-architecture-the-classic-way/

2021-05-11 09:25 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/model/Section.java
> +    public Section(Line line, Station upStation, Station downStation, int distance) {
Station upStation, Station downStation 와 같이 동일한 타입의 인자를 받는 경우 빌더를 사용하면
가독성을 향상시키고 실수를 방지 할 수 있어요.

제가 아론의 코드를 활용하다
new Section(line, downStatoin, upStation, 1); 과 같이 객체를 만들면 어떻게 될까요 ?

2021-05-12 17:29 UTC, Sehwan-Jang commented on src/main/java/wooteco/subway/section/dao/SectionDao.java
> +    public void save(Long lineId, LineRequest lineRequest) {
좋은 글 정말 감사해요 미립. 글을 쭉 읽어보니, 레이어의 존재 이유. 그리고 레이어 간 통신 시 왜 같은 DTO 객체를 사용하는 것을 지양해야 하는지 조금이나마 느껴볼 수 있었어요.

그런데 읽으면서 궁금한 점이 하나 있었어요.
제가 이해한 바로는 웹 레이어와 서비스 레이어 사이의 통신에서 Entity 객체가 아닌 DTO 객체를 사용하는 이유는 (여러가지가 있겠지만 그중 하나는) 엔티티 객체에 변화가 생겨도, 웹 레이어와의 의존성을 차단시키고 그 변화의 영향을 끊어버려 유지보수성을 높이기 때문이라고 이해했어요.

이 부분에서 든 생각은 그렇다면 서비스 레이어와 레포지토리(지금은 Dao) 레이어 사이의 통신에서도 굳이 entity  객체를 주고받지 말고 통신에 사용되는 DTO 같은 객체를 생성해서 통신한다면 서비스-웹 레이어 단에서의 장점을 그대로 공유하지 않을까? 그런데 왜 서비스 단에서는 레포지 단으로 Entity 객체를 보낼까에 대한 궁금증이 들었어요. 
그렇게 함으로써 얻는 이득을 제가 생각해 보았을 때, 어차피 서비스 레이어는 도메인 객체를 사용할 수 밖에 없는데, 레포지에서 도메인 객체를 그대로 서비스 레이어로 보내주게 된다면, 서비스 레이어는 굳이 (레포지로부터의) DTO 객체를 도메인 객체로 convert 해주는 로직을 가지지 않아도 된다? 정도가 있을 것 같아요. 
혹시 이 이유 외에 서비스와 레포지 레이어 사이의 통신을 별도의 DTO가 아닌 도메인 객체로 하는 이유가 더 있을까요?

2021-05-13 17:23 UTC, Sehwan-Jang commented on src/main/java/wooteco/subway/line/api/dto/LineDetailsResponse.java
> +
자바 컨벤션을 찾아보고 있는데 제가 찾지 못하는 건지 모르겠지만.... 혹시 클래스 첫줄 개행에 대한 컨벤션이 있을까요?
이제까지 저는 가독성을 위해 클래스 첫줄은 항상 개행해서 변수를 적어주는 편이었거든요.

그리고 평소에는 여러 인스턴스 변수들이 있는 경우 저는 붙여쓰는 편이지만 그 변수들에 어노테이션이 붙게 되면 가독성이 좀 안좋아지는 것 같은데 이럴경우 띄어써도 괜찮을까요?

2021-05-14 06:03 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/dao/SectionDao.java
> +    public void save(Long lineId, LineRequest lineRequest) {
서비스 레이어와 DAO 간의 통신도 DTO 를 통하여 통신한다면 많은 장점이 있을 수 있다고 생각 합니다. 다만 모든 레이어를 별도에 DTO 를  통해 통신한다면 직관성이 떨어지고 많은 양의 코드를 작성해야할 것 같아요. 상대적으로 클라이언트와 통신에 비해 취약점이 적기도하구요.
(개발자가 실수하지 않는다면 악의적인 공격의 가능성은 떨어집니다. 클라이언트는 악의적인 공격이나 노출되지 않아도 되는 데이터가 노출 될 수 있는 단점이 발생할 수잇죠)

2021-05-14 06:08 UTC, seok-2-o approved these changes
피드백 반영하느라 고생 많았어요.

질문하신 내용에 답변 및 추가적으로 소소한 팁 몇가지 남겨놓았습니다. 확인해주시면 좋을것 같아요

이번 피드백을 마지막으로 저와의 미션은 마무리 되는데요.
저와의 미션은 종료되었지만, 궁금한점 어려운점 있으면 편하게 DM 주세요.

감사합니다 🙇

2021-05-14 06:08 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/api/dto/LineDetailsResponse.java
> +
첫줄 개행 말고 인스턴스 필드 사이에 개행이 id 와 name 사이에 개행이 궁금해서 여쭤보았습니다.

이런 컨벤션은 보통 회사 컨벤션을 따르는게 좋습니다. 

어노테이션이 존재하면 개행 하는 방식도 좋아보이네요. 👌

2021-05-14 06:08 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/api/dto/LineUpdateRequest.java
> +    @NotEmpty(message = "노선 색을 지정해야합니다.")
NotEmpty 는 "" 를 허용하는 어노테이션이에요 NotBlank 로 변경하면 어떤가요?

2021-05-14 06:08 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/dao/SectionDao.java
> +    private final JdbcTemplate jdbcTemplate;
이번 미션과 큰 상관이 없는 주제지만 [NamedParameterJDBCTemplate](https://rkaalstu.tistory.com/43)
를 적용해보는 건 어떤가요. 지금보다 유지보수하기에 용이한 코드가 될 것 같아요.

2021-05-14 06:08 UTC, seok-2-o commented on src/main/java/wooteco/subway/section/model/Section.java
> +        if (distance <= 0) {
매직넘버 사용하셨네요.

2021-05-14 06:09 UTC, merged

2021-05-19 17:17 UTC, Sehwan-Jang commented on src/main/java/wooteco/subway/section/model/Section.java
> +        if (distance <= 0) {
# 학습 로그

## DirtiesContext & Transactional

- 테스트에서 실제 db를 사용하게 되면 여러 테스트들을 한번에 실행할때 서로에게 영향을 미쳐 문제가 발생할 수 있다.
- 이러한 문제를 피하기 위해선 각 테스트들이 동일한 환경에서 실행될 수 있도록 작업을 해주어야 한다.
- DirtiesContext는 이러한 문제를 해결하기 위한 방법들 중 하나이다.
    - SpringBootTest는 테스트 시에 실제로 ApplicationContext를 실행시키고 모든 빈들을 등록한다. 그리고 테스트가 진행되는 내내 같은 Context를 공유하여 사용하도록 한다.
    - DirtiesContext란 말 그대로, Context를 오염시켜 지정한 단위마다 새로운  Context를 생성하도록 강제한다. 
    예를 들어 테스트 클래스 레벨에 `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)` 설정을 해주면 각 테스트가 실행될 때마다 새로운 context가 생겨 모든 테스트들이 다른 context 아래에서 동작하게 된다.
    - 확실히 독립적이고 동등한 테스트환경을 제공하긴 하지만, 매우 비싸고 비효율적인 방식이므로 사용하지 않는 것이 권장된다.
- 다른 방법
    - @Transactional
        - 사용시 각 테스트들이 끝날때마다 자동으로 롤백 처리를 해준다.
        - 하지만, webEnvironment를 RandomPort 혹은 DefinedPort(즉 실제로 서버를 띄울 시 그 서버는 별도의 스레드에서 실행되기 때문에) 롤백이 되지 않는다.
    - BeforeEach, AfterEach || @Sql("/test.sql")
        - 개발자가 Dao나 sql 파일로 직접 쿼리문을 작성하여 테스트 마다 롤백시키도록 하는 방법이다.
        - 지하철 1단계 미션에서도 이 방법을 활용하여 DirtiesContext 를 대체하였다.
- 링크, 출처
    - [https://goddaehee.tistory.com/211](https://goddaehee.tistory.com/211)
    - 브라운강의

## 태그

- SPRING, TEST, DIRTIESCONTEXT

# 학습 로그

## Layered Architecture & 애플리케이션 흐름

- 정리 내용
    - WEB, SERVICE, REPOSITORY 레이어로만 이루어진 애플리케이션의 충분성
    - 레이어 통신의 매개체, convert 해주는 위치( Service vs Controller)
- [https://www.notion.so/Layered-Architecture-a5c936b0280b439c8c482549cdfe48a5](https://www.notion.so/Layered-Architecture-a5c936b0280b439c8c482549cdfe48a5)
- [https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md](https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md)

## 태그

- SPRING, LAYER, DTO, ENTITY, ARCHITECTURE

# 학습 로그

## Restassured vs Mock

- RestAssured
    - 의존성 추가 필요
    - 설정

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b072f90d-515c-4eef-8594-49c2a8956590/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b072f90d-515c-4eef-8594-49c2a8956590/Untitled.png)

        - SpringvBootTest를 사용해서 실제 서버를 띄우고 빈들을 주입받음 = 속도가 느림
        - DB를 사용할 경우 DirtiesContext 혹은 @Sql을 통한 설정을 통해 테스트들 끼리의 독립성을 확보해야함.
    - 실제 요청과 응답 사이의 과정을 거치므로, E2E 테스트에서 많이 사용.

    - 비슷 = MockMvc

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a6117836-f627-4884-b4ad-0a28895166f8/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a6117836-f627-4884-b4ad-0a28895166f8/Untitled.png)

        - @MockMvcTest, @AutoConfigureAMockMvc 를 통해 요청 - 응답 과정을 테스트 할 수 있다.
        - SpringBootTest가 아닌 WebMvcTest 어노테이션을 사용하기 때문에 속도는 더 빠름.
- Mock
    - SpringTest 에 이미 포함되어 있어 따로 의존성을 추가하지 않아도 된다.
    - 설정

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/bd51da7e-f4ed-41b5-aed8-68a7b229765f/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/bd51da7e-f4ed-41b5-aed8-68a7b229765f/Untitled.png)

        - 특정 클래스에 대한 테스트를 하고 싶은 경우 주입받는 빈들을 흉내내도록 설정.
            - `when()` , `thenReturn()` 을 통해 Mock 된 빈들에 대한 처리를 강제함.
                - 즉, 주입된 빈들의 기능은 잘 작동한다고 가정하고, 테스트 하려는 클래스의 로직이 잘 작동되는지에 대해 단위테스트를 할 수 있다.
- 링크, 출처
    - [자바블 MockMvc vs RestAssured](https://woowacourse.github.io/javable/post/2020-08-19-rest-assured-vs-mock-mvc/)
    - [지하철 노선도 미션](https://github.com/Sehwan-Jang/atdd-subway-map/tree/step2)

## 태그

- SPRING, TEST, MOCK, RESTASSURED

# 학습 로그

## TCP, 핸드쉐이크, IP (배포)

- 링크
    - [https://www.notion.so/HTTP-81b63a376cdd4800b194e77250c39778#06c4fd59cf364fdda18989eef498e45e](https://www.notion.so/HTTP-81b63a376cdd4800b194e77250c39778#06c4fd59cf364fdda18989eef498e45e)

## 태그

- TCP, IP, HANDSHAKE

2021-05-19 17:18 UTC, Sehwan-Jang commented
# 학습 로그

## DirtiesContext & Transactional

- 테스트에서 실제 db를 사용하게 되면 여러 테스트들을 한번에 실행할때 서로에게 영향을 미쳐 문제가 발생할 수 있다.
- 이러한 문제를 피하기 위해선 각 테스트들이 동일한 환경에서 실행될 수 있도록 작업을 해주어야 한다.
- DirtiesContext는 이러한 문제를 해결하기 위한 방법들 중 하나이다.
    - SpringBootTest는 테스트 시에 실제로 ApplicationContext를 실행시키고 모든 빈들을 등록한다. 그리고 테스트가 진행되는 내내 같은 Context를 공유하여 사용하도록 한다.
    - DirtiesContext란 말 그대로, Context를 오염시켜 지정한 단위마다 새로운  Context를 생성하도록 강제한다. 
    예를 들어 테스트 클래스 레벨에 `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)` 설정을 해주면 각 테스트가 실행될 때마다 새로운 context가 생겨 모든 테스트들이 다른 context 아래에서 동작하게 된다.
    - 확실히 독립적이고 동등한 테스트환경을 제공하긴 하지만, 매우 비싸고 비효율적인 방식이므로 사용하지 않는 것이 권장된다.
- 다른 방법
    - @Transactional
        - 사용시 각 테스트들이 끝날때마다 자동으로 롤백 처리를 해준다.
        - 하지만, webEnvironment를 RandomPort 혹은 DefinedPort(즉 실제로 서버를 띄울 시 그 서버는 별도의 스레드에서 실행되기 때문에) 롤백이 되지 않는다.
    - BeforeEach, AfterEach || @Sql("/test.sql")
        - 개발자가 Dao나 sql 파일로 직접 쿼리문을 작성하여 테스트 마다 롤백시키도록 하는 방법이다.
        - 지하철 1단계 미션에서도 이 방법을 활용하여 DirtiesContext 를 대체하였다.
- 링크, 출처
    - [https://goddaehee.tistory.com/211](https://goddaehee.tistory.com/211)
    - 브라운강의

## 태그

- SPRING, TEST, DIRTIESCONTEXT

# 학습 로그

## Layered Architecture & 애플리케이션 흐름

- 정리 내용
    - WEB, SERVICE, REPOSITORY 레이어로만 이루어진 애플리케이션의 충분성
    - 레이어 통신의 매개체, convert 해주는 위치( Service vs Controller)
- [https://www.notion.so/Layered-Architecture-a5c936b0280b439c8c482549cdfe48a5](https://www.notion.so/Layered-Architecture-a5c936b0280b439c8c482549cdfe48a5)
- [https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md](https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md)

## 태그

- SPRING, LAYER, DTO, ENTITY, ARCHITECTURE

# 학습 로그

## Restassured vs Mock

- RestAssured
    - 의존성 추가 필요
    - 설정

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b072f90d-515c-4eef-8594-49c2a8956590/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b072f90d-515c-4eef-8594-49c2a8956590/Untitled.png)

        - SpringvBootTest를 사용해서 실제 서버를 띄우고 빈들을 주입받음 = 속도가 느림
        - DB를 사용할 경우 DirtiesContext 혹은 @Sql을 통한 설정을 통해 테스트들 끼리의 독립성을 확보해야함.
    - 실제 요청과 응답 사이의 과정을 거치므로, E2E 테스트에서 많이 사용.

    - 비슷 = MockMvc

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a6117836-f627-4884-b4ad-0a28895166f8/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a6117836-f627-4884-b4ad-0a28895166f8/Untitled.png)

        - @MockMvcTest, @AutoConfigureAMockMvc 를 통해 요청 - 응답 과정을 테스트 할 수 있다.
        - SpringBootTest가 아닌 WebMvcTest 어노테이션을 사용하기 때문에 속도는 더 빠름.
- Mock
    - SpringTest 에 이미 포함되어 있어 따로 의존성을 추가하지 않아도 된다.
    - 설정

        ![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/bd51da7e-f4ed-41b5-aed8-68a7b229765f/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/bd51da7e-f4ed-41b5-aed8-68a7b229765f/Untitled.png)

        - 특정 클래스에 대한 테스트를 하고 싶은 경우 주입받는 빈들을 흉내내도록 설정.
            - `when()` , `thenReturn()` 을 통해 Mock 된 빈들에 대한 처리를 강제함.
                - 즉, 주입된 빈들의 기능은 잘 작동한다고 가정하고, 테스트 하려는 클래스의 로직이 잘 작동되는지에 대해 단위테스트를 할 수 있다.
- 링크, 출처
    - [자바블 MockMvc vs RestAssured](https://woowacourse.github.io/javable/post/2020-08-19-rest-assured-vs-mock-mvc/)
    - [지하철 노선도 미션](https://github.com/Sehwan-Jang/atdd-subway-map/tree/step2)

## 태그

- SPRING, TEST, MOCK, RESTASSURED

# 학습 로그

## TCP, 핸드쉐이크, IP (배포)

- 링크
    - [https://www.notion.so/HTTP-81b63a376cdd4800b194e77250c39778#06c4fd59cf364fdda18989eef498e45e](https://www.notion.so/HTTP-81b63a376cdd4800b194e77250c39778#06c4fd59cf364fdda18989eef498e45e)

## 태그

- TCP, IP, HANDSHAKE