[Spring 지하철 노선도 관리 - 3단계] 검프(김태정) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #132
Opened 2021-05-11 13:54 UTC by Livenow14

안녕하세요 김고래! 두번째 PR입니다. 

이번 미션에서는 각 객체들의 책임에 대해 많이 고민해봤어요. 

### 중점적으로 한 부분은

### 1. 일급 컬렉션 도입 및 사용

처음에는 DB로직을 통해 전반적인 서비스 흐름을 관리했는데, 이렇게하면 객체지향의 장점을 최대한 누리지 못한다고 생각했어요. 

1:N 관계인 Line과 Section에서 Line이 Sections라는 일급 컬렉션을 가지게 했어요. 

그래서인지 현재 일급 컬렉션에 과도한 비즈니스 책임이 할당되어 있는거 같아요. 

> 여기서 질문은

```java
Service 객체는 최대한 비즈니스의 흐름을 담당하게 하고, 비즈니스 로직은 도메인 객체에게 주도록 했어요 

그래서 Service는 왜소하고 도메인이 뚱뚱해졋네요..! 

이런 흐름대로 애플리케이션을 작성하는 게 맞는지 확신이 서질 않아요! 김고래의 생각은 어떤가요? 😊
```

### 2. 레이어별 테스트 실행

Repository는 @JDBCTest를 통해,  Service는 Mockito로, Controller는 @Restassured를 사용했어요. 

기능이 하나 생길 때마다 3개 이상의 테스트가 생김을 확인할 수 있어요. 

힘들었지만, 최대한 배우고 싶어 최대한 테스트를 진행하려 했어요 (이 과정에서 배운게 정말 많았어요!)

> 여기서 질문은

```java
위에서 말했듯이, 비즈니스 처리 로직은 도메인에게 있는데, 흐름을 Service에서 관리하다 보니, Service테스트가 곧 도메인 테스트가 되어버렸어요. 

이후 도메인도 따로 테스트를 진행해야할까 생각을 했는데, 엄두가 나질 않았어요..  코드 작성 시간보다 테스트에 고민하는 시간이 정말 많아지는 거 같아요. 

테스트 커버리지 100%를 목표 한다는 것은, 결국 모든 객체의 테스트를 100%진행 한다는 의미겠죠..?  

이런경우 DTO와 public한 static 메소드는 어떻게 해야할지 감이 잡히질 않아요. 

테스트를 어떻게 진행하는지 김고래의 의견을 듣고싶어요!!
```

### 3. validate 사용시 적용

요구사항을 해결하다, Validate를 언제 진행해야 할지에 대한 의문이 들었어요.

Service에서 진행하는 것이 좋은것인지, 도메인에서 진행하는것이 좋은것인지 몰라 우선 도메인에 검증 로직을 넣는 것으 우선적으로 생각했어요. 

```java
서비스는 결국 비즈니스의 흐름을 담당하는 친구이니,, 검증은 도메인에서 하는게 맞을거 같긴 한데.. 또 그렇다고 검증 로직을 보기 위해 도메인 내부까지 봐야한다는 점이 불편하지 않을까? 하는 생각이 들어요.

사용하는 모든곳(service, domain)에서 validation을 진행하는 것이 맞을거 같기도하네요.

이부분도 질문 남겨요..!
```

코드를 작성하면 할수록 의문점이 점점 커지는 거 같아요. 

정답은 없겠지만, 코드 작성의 이유를 더 찾아가고싶어요! 

이번에도 잘 부탁드려요 🙇🏻‍♂️🙇🏻‍♂️

2021-05-13 04:16 UTC, ep1stas1s commented
아직 코드를 보기 전이라 제 의견을 위주로 남기겠습니다ㅎㅎ
(아마 오늘 저녁은 되야 볼 수 있을 것 같아요ㅠ_ㅠ)

> 일급 컬렉션 도입 및 사용

Service는 왜소하고 도메인이 뚱뚱해지는 건 좋은 현상이라고 봅니다ㅎㅎㅎ 다만 하나의 도메인이 너무 비대해지면 도메인을 쪼갤 필요가 있겠죠?
어쩌면 아래 질문과도 조금 연관되어 있는데, 비즈니스 로직이 서비스가 아니라, 도메인에 몰리면 테스트하기에도 용이하고 중복 로직도 많이 줄어들 것 같네요

> 레이어별 테스트 실행

테스트는 특히나 개인적인 의견일텐데요ㅎㅎ; 
우선 테스트 커버리지 100%는 사실상 불가능하(~~고 의미없~~)다고 봐요! 
예를 들어 repository같은 경우는 단순 저장, 조회가 많기 때문에 꼭 필요한 부분이 아니라면 테스트를 하지 않아도 된다고 생각해요. (DTO도 로직이라고 볼 수 있는 메서드는 없기때문에 마찬가지라고 생각합니다)
반대로 도메인같은 경우는 어플리케이션에서 가장 중요한 요소기 때문에 필수적으로 테스트를 견고하게 짜야한다고 생각해요.

우테코에서 귀가 닳도록 들으셨겠지만, 테스트는 불안감을 해소시켜주는 역할이에요. 
사실 저도 검프처럼 테스트에 드는 비용이 너무 크다고 생각해서 테스트를 좋아하는 편은 아니었습니다 ^_^; 하지만… 실제로 다수의 사용자에게 서비스가 나간다고 생각하니까 무서워서 테스트를 짜게 되더라구요ㅎㅎㅎ
너무 부담갖진마시고 모든 메서드를 테스트 한다는 느낌보단, 로직 위주로 테스트를 만들어가시면 좋을 것 같아요 :smile:

> validate 사용시 적용

레이어마다 방어로직을 넣는 것이 정석이나, 상황에 따라 service또는 domain에만 있을 수 있을 것 같아요~ 
혹시 코드를 보다가 관련 있는 부분을 발견하면 추가적으로 코멘트 남기겠습니다^_^

2021-05-14 05:48 UTC, kang-hyungu requested changes
안녕하세요 검프
3단계 구현하신 내용 확인했어요
몇 가지 피드백 남겼으니 확인해보시고 궁금한 점 생기면 찾아오시거나 dm 주세요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = {IllegalArgumentException.class, IllegalStateException.class, DuplicateKeyException.class})
DuplicateKeyException을 bad request로 처리해야되는 이유가 무엇일까요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        if (lineDao.findByName(lineRequest.getName()).isPresent()) {
`lineDao.exsistsByName(lineRequest.getName())`

이런 쿼리를 만들어보면 좀더 읽기 쉽지 않을까요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Line line = new Line(savedLineEntity.id(), savedLineEntity.name(), savedLineEntity.color());
Line과 LineEntity로 분리한 이유가 있을까요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Section section = new Section(line, findStationById(lineRequest.getUpStationId()), findStationById(lineRequest.getDownStationId()), lineRequest.getDistance());
한 줄에서 너무 많은 일들을 처리하고 있네요
findStationById 메서드를 변수로 분리해보아요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public void update(final Long id, final LineUpdateRequest lineUpdateRequest) {
이 메서드는 db에 의존적으로 작성되어 있네요
lineDao로 직접 업데이트 하지 말고 lineEntity 객체로 업데이트 해서 lineDao로 업데이트 해보면 어떨까요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void deleteDirtyChecking(final Sections originSections, final Sections sections) {
이 메서드가 너무 읽기 어렵게 되어 있네요.
어떤 의도로 작성한 메서드인지 알려주세요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void dirtyChecking(final Sections originSections, final Sections sections) {
이 메서드도 너무 복잡하네요
왜 더티 체킹인데 save 작업이 있나요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>  public class DBLineDao implements LineDao {
```suggestion
public class JdbcLineDao implements LineDao {
```

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>      public DBLineDao(final JdbcTemplate jdbcTemplate) {
```java
    public DBLineDao(final JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.lineRowMapper = (rs, rowNum) -> new LineEntity(
                rs.getLong("id"), 
                rs.getString("name"),
                rs.getString("color"));
    }
```
위 생성자 하나면 충분하지 않을까요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
> +        if (rowCount == 0) {
delete 메서드에서 유효성 검증 할 필요는 없어 보이네요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        return null;
왜 null을 반환하나요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        return Optional.empty();
왜 empty를 반환하나요

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        List<SectionEntity> lineEntity = jdbcTemplate.query(sql, sectionEntityRowMapper, id);
```suggestion
        return jdbcTemplate.query(sql, sectionEntityRowMapper, id);
```

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final Name name;
왜 Name을 인터페이스로 구현했나요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final State state = StateFactory.initialize(new Sections());
1. 왜 생성자가 아닌 인스턴스 변수에 직접 할당하나요?
2. State 객체가 맡은 역할은 무엇인가요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    public String nameAsString() {
반환 타입이 String인데 메서드명에 또 String을 쓸 필요가 있나요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        if (state.containStation(upStation) && state.containStation(downStation)) {
state 객체에 중복 체크하는 메서드를 추가하면 어떨까요?

2021-05-14 05:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/MemoryLineDao.java
> +public class MemoryLineDao implements LineDao {
```suggestion
public class InMemoryLineDao implements LineDao {
```

2021-05-15 16:38 UTC, Livenow14 commented on src/main/java/wooteco/subway/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = {IllegalArgumentException.class, IllegalStateException.class, DuplicateKeyException.class})
DuplicateKeyException은 DB의 unique제약사항이 걸려있는 column에 동일한 값이 들어올 시 생기는 예외라 생각해요.

처음엔 Dao에서 Validaion을 진행했지만, 검증의 책임이 Dao있으면 어색하다는 피드백을 받고 Service로 검증을 인가했어요. 

```java
# LineService.class 
private void validateDuplication(final LineRequest lineRequest) {
        if (lineDao.findByName(lineRequest.getName()).isPresent()) {
            throw new IllegalStateException("이미 등록된 이름임!");
        }

        if (lineDao.findByColor(lineRequest.getColor()).isPresent()) {
            throw new IllegalStateException("이미 있는 색깔임!");
        }
    }
```

DB에 접근전 service에서 Validation을 진행하고 있어 실질적으로는 IllegalStateException 예외를 던지지만, LineDao의 단위테스트를 진행하다 중복된 key값이 있을 때 DuplicateKeyException이 발생한다는 사실을 알게되고, 이를 ExceptionHandler에 넣게 됐어요.

작성을 하다보니, Service에서는 예외를 충분히 던지고 있고, DB에서 DuplicateKeyException이 난 다는 것은 클라이언트의 잘못이 아닌 서버의 잘못이 될 가능성이 높은거 같아요. 

우선 DB관련 예외는 `DataAccessException` 를 통해 예외를 잡게 했는데, 이와 같이 작성하는 것이 괜찮은 접근 방식일까요..?

0702973f

2021-05-15 16:38 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        if (lineDao.findByName(lineRequest.getName()).isPresent()) {
dao에게 책임을 전달하는 방법을 생각하지 못했네요..! 좋은 지적 감사합니다 😊😊

b06d498a

2021-05-15 16:38 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Line line = new Line(savedLineEntity.id(), savedLineEntity.name(), savedLineEntity.color());
어제 대화를 통해 전반적인 수정이 필요하다 생각했어요. 

우선 lineEntity와 이를 의존하는 객체들을 수정했어요.

Section관련 부분또한 수정했어요. 

(이 부분에서 엄청 오래걸렸네요....)

b06d498a ~ 1e75460e

2021-05-15 16:39 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Section section = new Section(line, findStationById(lineRequest.getUpStationId()), findStationById(lineRequest.getDownStationId()), lineRequest.getDistance());
Eneity관련 객체를 제거하며 리팩토링 완료햇습니다 :) 

> 여기서 질문은,

Section을 만드는 책임을 가지는 private 메소드를 만들었어요.

프로퍼티는 같지만 타입이 다른 DTO가 생겼을 때 이 메소드를 어떻게 관리할지가 의문이예요.

현재는 아래와 같이 DTO(동일한 프로퍼티를 가지는 LineRequest, SectionRequest))의 주입에 따라 toSection을 오버로딩 했는데요,

```java
private Section toSection(final Line line, final LineRequest lineRequest) {
        Station upStation = findStationById(lineRequest.getUpStationId());
        Station downStation = findStationById(lineRequest.getDownStationId());
        return new Section(line, upStation, downStation, lineRequest.getDistance());
    }

private Section toSection(final Line line, final SectionRequest sectionRequest) {
        Station upStation = findStationById(sectionRequest.getUpStationId());
        Station downStation = findStationById(sectionRequest.getDownStationId());
        return new Section(line, upStation, downStation, sectionRequest.getDistance());
    }
```

이전 방식은 인자를 풀어서 넘기는 방식이었어요. 

```java
private Section toSection(final Line line, final Long upStationId, final Long downStationId, final int distance) {
        Station upStation = findStationById(upStationId);
        Station downStation = findStationById(downStationId);
        return new Section(line, upStation, downStation, distance);
    }
```

어느 방식이 더 좋다고 말할 수 없지만, 우선 private한 메소드이기 때문에 오버로딩을 해도 괜찮을거라 생각했어요. 

구구는 혹시 어떤 방식이 더 괜찮다 생각하시나요..?

10e6b94b

2021-05-15 16:39 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public void update(final Long id, final LineUpdateRequest lineUpdateRequest) {
업데이트 시, Line 객체를 넘기도록 변경했습니다 :) 감사합니다.

```java
@Transactional
public void update(final Long id, final LineUpdateRequest lineUpdateRequest) {
        Line line = findLineById(id);
        line.changeName(lineUpdateRequest.getName());
        line.changeColor(lineUpdateRequest.getColor());
        lineDao.update(line);
}
```

2021-05-15 16:40 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void deleteDirtyChecking(final Sections originSections, final Sections sections) {
jpa의 더티체킹을 모방한 메서드였어요..ㅎㅎㅎ

넣어야 할 로직이 많아지다 보니, 가독성을 해치게 되었어요. 

0a94e397

2021-05-15 16:40 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void dirtyChecking(final Sections originSections, final Sections sections) {
이부분도 삭제완료 했습니다 :)
0a94e397

2021-05-15 16:40 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>  public class DBLineDao implements LineDao {
DB를 명시하는 것이 안좋을거라 생각했어요..! 

JDBC로 변경함에 따라 더 명확해지게 됐어요. 좋은 리뷰 감사합니다 😊

77f3a918

2021-05-15 16:40 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>      public DBLineDao(final JdbcTemplate jdbcTemplate) {
인자로 들어오지 않는 값을 생성 할 땐, 부생성자에서 생성 후, 주 생성자에게 (this를 통해) 전달 것이 더 자연스럽다고 생각햇어요.. 

부생성자가 많아지면 많아질 수록 객체가 수행할 수 있는 능력이 풍부해진다고 생각해요. 

(주 생성자는 상태 초기화만 수행하도록 함) 

혹시 이런 관점이 오히려 가독성을 떨어뜨리게 하는걸까요..?

2021-05-15 16:41 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
> +        if (rowCount == 0) {
Dao에 유효성 검증책임이 있다면, 비즈니스 로직의 책임을 가지게 하는거 같아요..! 

변경후 테스트 완료 했습니다 감사합니다. :) 

dae95622

2021-05-15 16:41 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        return null;
사용하지 않는 메서드 삭제했습니다..!( 가독성을 해치는 부분이었네요. 죄송합니다.. ) 

7f7e1c7c

2021-05-15 16:41 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        return Optional.empty();
불필요한 객체 생성을 하지 않고, 바로 반환하게 변경했어요. 감사합니다 🙂

d371f8fc

2021-05-15 16:42 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        List<SectionEntity> lineEntity = jdbcTemplate.query(sql, sectionEntityRowMapper, id);
윗 부분과 동일해요 😊

d371f8fc

2021-05-15 16:42 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final Name name;
어제 구구의 조언대로, Name 인터페이스를 삭제 후, LineName, StationName 객체를 사용하는 것으로 리펙토링을 진행했어요.

하지만, 이후 요구사항에 따라 Null 객체를 생성해야할 부분이 생겼어요. ( 우선 Id로만 객체 생성, 다른 상태값은 null로 초기화 후 이후 상태값 변경 ) Null 로 객체를 초기화 할 수 있었지만, `Null 객체 디자인 패턴을 적용`하는게 더 좋을 거 같았어요. 그래서 다시 인터페이스를 도입하게 됐어요..ㅎㅎㅎ

혹시 잘못된 접근을 하고 있는 중일까요..??

2021-05-15 16:42 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final State state = StateFactory.initialize(new Sections());
1. Line과 Section의 책임이 변겸됨에 따라, 인스턴스에 직접 할당하는 부분을 제거 했어요.
2. 이미 변경이 된 노선에 변경을 추가로 할 수 없게 상태를 통해 관리하도록 했어요. ( 이부분은 이후에 추가적으로 변경할 예정이에요..!)

2021-05-15 16:42 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    public String nameAsString() {
string으로 타입을 명시하는 것이 아닌 rawName()으로 변경했습니다. 😊

bf3b5eb0

2021-05-15 16:43 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        if (state.containStation(upStation) && state.containStation(downStation)) {
state객체에게 책임을 수행하도록 변경했어요. ( 책임을 더 깊게 생각해봐야 할 것 같아요..ㅎㅎ )

2021-05-15 16:43 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/MemoryLineDao.java
> +public class MemoryLineDao implements LineDao {
InMemory라 표현합으로써, 객체의 역할을 더 잘 드러내게 됐어요. 갑사합니다. 

🙇🏻‍♂️🙇🏻‍♂️

2021-05-15 16:44 UTC, Livenow14 commented
안녕하세요  구구..! @kang-hyungu  영광스러운 두번째 만남입니다 ㅎㅎㅎㅎ

소소한 부분들은 금방 수정했으나, 도메인의 책임의 이동으로 많은 부분들이 변경됐어요. 

코드를 수정하다보니, 상대 개발자를 배려하고 있었나? 라는 의문점이 들더라고요.

저만 읽기 쉬운 코드를 작성하고 있는 저를 보고, 부끄러웠어요. 

구구의 피드백을 통해 많은 고민을 해보는 시간이 됐어요. 고마워요.

질문 사항들은 👀 이모지를 통해 남겼습니다. ㅎㅎ 

이상한 부분들이 있으면 마구 혼내주세요..!!

많은 피드백 기다리겠습니다...!!  

감사합니다 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2021-05-16 04:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = {IllegalArgumentException.class, IllegalStateException.class, DuplicateKeyException.class})
네 db 관련 예외를 DataAccessException로 잡아서 사용자에게 5xx로 응답하면 됩니다 👍 
특히 DuplicateKeyException은 사용자가 발생 시킬 수 없는 예외라서 피드백 남긴거였어요

2021-05-16 04:32 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Section section = new Section(line, findStationById(lineRequest.getUpStationId()), findStationById(lineRequest.getDownStationId()), lineRequest.getDistance());
두 메서드가 거의 동일한 로직이니 중복을 제거해주는 방향으로 가는게 좋다고 생각합니다

2021-05-16 04:34 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void deleteDirtyChecking(final Sections originSections, final Sections sections) {
현재 구현하는 기능들은 지하철 노선 관리와 관련된 기능인데 jpa 더티 체킹이라는 다른 관심사까지 섞이면서 코드 복잡도가 올라갔네요.
jpa를 구현해본다는 시도는 신선했지만 라이브러리로 분리해서 구현하면 어땠을까 싶네요

2021-05-16 04:36 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>  public class DBLineDao implements LineDao {
추상화하는 LineDao에 구체적인 db 드라이버, 라이브러리 등을 쓰면 문제가 됩니다.
인터페이스로 추상화한 이유는 언제든지 변경하기 쉽도록 하기 위해서죠.
실제 구현하는 클래스는 세부적인 사항을 써둬야 클래스명만 보고 어디에 의존하는지 파악할 수 있고, 갈아끼우기도 쉽겠죠

2021-05-16 04:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>      public DBLineDao(final JdbcTemplate jdbcTemplate) {
lineRowMapper를 다르게 생성해야된다면 그럴수도 있다고 생각이 들지만 지금은 고정된 객체니 나눌 필요는 없어보입니다.
생성자가 많아지면 객체 관리하기 복잡해져요

2021-05-16 04:38 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/DBSectionDao.java
> +        return null;
가독성보다 null을 반환하지 않도록 하세요
메서드의 null 반환은 npe 발생하는 원인이 됩니다.

2021-05-16 04:40 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final Name name;
제가 보기엔 과해보여요.
디자인 패턴을 적용하는게 항상 좋은 건 아니에요.
코드 복잡도를 높이기 때문에 정말 필요한 곳에서만 사용하는게 좋습니다.
지금은 그냥 String name으로 하고 임시로 null을 줘도 충분하지 않을까요?

2021-05-16 04:42 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    public String nameAsString() {
raw를 붙일 필요가 있을까요?
line 객체를 사용하는 클라이언트 입장에서는 그냥 name 아닐까요?
raw가 붙으면 문자열이 아닌 다른 뭔가가 더 있는지 코드를 뜯어봐야합니다.

2021-05-16 05:37 UTC, kang-hyungu requested changes
검프, 수정하신 코드 확인했어요
좀더 구조를 간결하게 가져가면 좋을 부분에 피드백 남겼어요
그리고 도메인 클래스의 유닛 테스트도 추가해서 코드가 의도한대로 동작하는지 검증해보면 좋겠어요

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        return lineDao.findById(id).orElseThrow(() -> new IllegalArgumentException("없는 노선임!"));
IllegalArgumentException 보다는 not found exception을 새로 추가해보면 어떨까요?
아이디로 라인을 못찾은 것이니 IllegalArgumentException가 적절해보이진 않네요

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private Name name;
Name을 추상화 해야되는 이유가 있을까요?
LineName으로 두고 NullName 대신에 LineName에 이름을 빈값으로 둘 수 있는 팩터리 메서드를 두면 어떨까요?
클라이언트가 LineName, NullName만 객체로 주입하는게 아니라 StationName 객체로 주입할 수 있도록 열려있는데 정말 추상화하는게 맞을까요?

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        this(id, new LineName(name), color, StateFactory.initialize(new Sections(sections)));
StateFactory에 initialize 메서드로 하니까 잘 읽히지가 않네요
기존 객체를 초기화하는게 아니라 새로운 객체를 생성하는 것이니 create, getInstance, of 같은 이름이 더 적절하지 않을까요?

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        if (state.sections().sections().size() < 1) {
객체지향 생활체조
규칙 4: 한 줄에 점을 하나만 찍는다.

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Line.java
> +            this.state.sections().addSection(targetSection);
sections를 꺼내서(getter) 추가하지 말고 객체에게 처리하라고 메세지를 보내세요

```suggestion
            this.state.addSection(targetSection);
```

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            if (findSection.isPresent()) {
객체지향 생활체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            if (!this.sections.contains(section)) {
객체지향 생활체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +        return null;
null 대신 optional로 처리해보면 어떨까요?

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/state/Change.java
> +    public State addSection(final Section targetSection) {
이 메서드의 반환 타입을 활용하는 곳이 없네요
실제 하는 일은 section을 추가하는 것 뿐인데 State가 필요한가요?
그냥 Line 클래스가 Sections를 가지면 되지 않나요?

2021-05-16 05:37 UTC, kang-hyungu commented on src/main/java/wooteco/subway/name/domain/Name.java
> +@JsonTypeInfo(
도메인 객체에 Json 관련된 어노테이션은 없는게 좋습니다.
dto에서 json 관련 처리를 해주세요

2021-05-16 05:37 UTC, kang-hyungu commented on src/test/java/wooteco/subway/line/application/LineServiceTest.java
> +    private Station station1;
1. 테스트 코드도 유지보수해야되는 코드입니다. 1,2,3 같은 값을 붙여주면 유지보수하기 어렵습니다.
2. 테스트가 추가될 때마다 인스턴스 변수가 늘어나겠네요. 각 테스트 메서드에 지역변수로 선언하는게 낫지 않을까요?

2021-05-16 05:37 UTC, kang-hyungu commented on src/test/java/wooteco/subway/station/ui/StationAcceptanceTest.java
> +    private ExtractableResponse<Response> saveStationToHTTP(StationRequest stationRequest) {
line, station 인수 테스트에 http request 관련 중복된 메서드가 많네요
get, post, put, delete를 호출하는 메서드를 각 하나씩 만들고 상위 클래스인 AcceptanceTest에 정의해두면 중복을 줄일 수 있겠네요

2021-05-16 07:11 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        Section section = new Section(line, findStationById(lineRequest.getUpStationId()), findStationById(lineRequest.getDownStationId()), lineRequest.getDistance());
피드백 반영했습니다..! 

8d1a2843

2021-05-16 07:12 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private void deleteDirtyChecking(final Sections originSections, final Sections sections) {
라이브러리로 구현할 수도 있는 부분이었군요..! 

라이브러리를 생성하는 법은 이후 더 공부한 후, 추가하겠습니다 😊

2021-05-16 07:12 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>  public class DBLineDao implements LineDao {
추상클래스, 인터페이스에선 범용적인 이름을,

구현 클래스에서는 세부내용을 작성해야하는 것 이군요..! 좋은지적 감사합니다..!

2021-05-16 07:12 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/DBLineDao.java
>      public DBLineDao(final JdbcTemplate jdbcTemplate) {
생성자가 현재 서비스에서 정말 필요한지 생각해 봐야할 부분인거 같아요

rowMapper관련 부분 수정 했습니다.

78c90509

2021-05-16 07:13 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private final Name name;
정답은 없다! 라는 말을 잊고, 디자인 패턴이 정답이라 생각했어요.

추상화 로직을 제거후, 각 Domain별 Name을 생성햇어요.

b0064044

2021-05-16 07:13 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    public String nameAsString() {
원시값 포장이 된 (StationName.class와 같은) 객체가 사용될 것이라 생각했어요.

하지만 로직중 사용되는 부분이 전혀 없다는 걸 알게됐고, 또한 메세지를 보내 책임을 수행하면 불러올 이유가 없어지는 것을 알게됐어요..! 

좋은 관점 감사합니다. :)

2021-05-19 06:18 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        return null;
null을 리턴하고 있었네요..! 

Section이 없는경우,  Throw를 뱉게 변경했어요. 

또한 예외 처리부분을 커스텀 예외를 만들어 처리하도록 했어요. 

2dc778a2

2021-05-19 06:19 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        return lineDao.findById(id).orElseThrow(() -> new IllegalArgumentException("없는 노선임!"));
위와 동일하게, 커스템 예외를 통해 예외의 의도를 더 드러나게 변경했어요 🙂

좋은 피드백 감사합니다!

2021-05-19 06:20 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    private Name name;
앞선 피드백을 통해, 추상화를 제거하고, 각 도메인 이름으로 변경했어요.

2021-05-19 06:20 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        this(id, new LineName(name), color, StateFactory.initialize(new Sections(sections)));
네이밍을 제대로 생각해보지 않았던거같아요.

기존 객체를 추가한다는 의미로, create로 변경했어요 감사합니다 😊😊

91ec4d38

2021-05-19 06:21 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +        if (state.sections().sections().size() < 1) {
디미터 법칙을 제대로 준수하지 않았네요..

기본적으로 생각해야할 부분인데 고려하지 못했던거 같아요. 전반적으로 두번 이상의 참조를 가지는 부분들을 전부 수정했어요.

9f38cc19

2021-05-19 06:22 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +            this.state.sections().addSection(targetSection);
위 수정사항과 동일해요 😁

 9f38cc1

2021-05-19 06:22 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            if (findSection.isPresent()) {
위 수정사항과 동일해요 😁

 9f38cc1

2021-05-19 06:22 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            if (!this.sections.contains(section)) {
위 수정사항과 동일해요 😁

 9f38cc1

2021-05-19 06:24 UTC, Livenow14 commented on src/main/java/wooteco/subway/line/state/Change.java
> +    public State addSection(final Section targetSection) {
State를 삭제하면서, 과한 패턴 사용을 지향하고 있었다는것을 알게됐어요..!

좋은 피드백 감사합니다 ㅎㅎ

2021-05-19 06:25 UTC, Livenow14 commented on src/main/java/wooteco/subway/name/domain/Name.java
> +@JsonTypeInfo(
이부부분도 Name인터페이스를 삭제하며, 변경됐어요! 

좋은 피드백 감사합니다 ㅎㅎㅎ

2021-05-20 06:17 UTC, Livenow14 commented on src/test/java/wooteco/subway/station/ui/StationAcceptanceTest.java
> +    private ExtractableResponse<Response> saveStationToHTTP(StationRequest stationRequest) {
상위 클래스에 get, post, put, delete의 httpRequest관련 메서드를 올림으로써, 중복이제거 됐어요..! 

중복을 제거한다는 생각을 못했던거 같아요..! 이후 미션에서도 항상 생각하겠습니다.

7dc5e665

2021-05-20 12:35 UTC, Livenow14 commented on src/test/java/wooteco/subway/line/application/LineServiceTest.java
> +    private Station station1;
전반적인 리팩토링 이후, 유지보수 쉽게 변경했어요..ㅎㅎ 
좋은 피드백 감사해요..!

2021-05-20 12:45 UTC, Livenow14 commented
안녕하세요 구구 @kang-hyungu 영광스러운 세번째 만남입니다 ㅎㅎㅎㅎ

구구의 피드백을 통해, 이전까지 가볍게 생각했던 부분들을 깊게 생각해봤어요.

코드 작성자가 의미없는 로직을 짜게 된다면, 이를 체크해야하는 다른 개발자들에게 혼란을 키운다는 것을 알게됐어요.

### 중점적으로 한 부분은

### 일급컬렉션 로직 수정

일금컬렉션의 중복 코드들을 전부 제거했어요. 조금만 더 깊게 살펴보면, 짧고, 명확한 코드를 작성할 수 있다는 것을 배웠어요.

### 일급컬렉션 테스트 코드 작성

TDD의 중요성을 다시한번 알게됐어요. 

일급컬렉션의 구현을 테스트 먼저하지 않고, 구현에만 집중했어요. 그러다보니, 테스트를 제대로 못해봤고, 오류를 찾을 수 있었어요. 

처음부터 테스트를 잘 작성했어야, 로직에 신뢰할 수 있게된다는 것을 배웠어요.

### 도메인과 프레임워크 사이

이전까지는, 서비스에 프레임워크가 들어가게 된다면, 어떠한 객체든 프레임워크 위에서 움직여야 한다 오해했어요. 

그래서 일급컬렉션, 도메인 로직등을 깊게 생각하지 않았어요. 

도메인과 테스트를 작성하다보니, 스프링 프레임워크가 객체지향 개발을 지향하고, 이러한 개발을 쉽게해준다는 것을 배웠어요. 

### 결론적으로.

모든 테스트를 진행하려 해봤어요. 이를통해 테스트가 확실해야, 서비스의 품질이 높아진다는 것을 알게됐어요.

테스트를 하면 할수록, 로직이 어떻게 짜여져 있었고, 이상한 부분이 어디였는지 확실히 알게됐어요.

개발관련 시간만큼 테스트의 유지보수 시간도 중요하다는것을 알게된 소중한 시간이었어요.

수정완료 후, 2차 피드백 처음 코드를 보며, 장인정신이 없는, 그냥 동작만 되게하는 코드였다는것을 알게됐고, 이번에도 부끄러웠어요.. 제 코드를 제가 보기 싫어짐을 느껴진다면 자신이 없는 코드라 의심치않아요.

이후 코드 작성에 어떠한 마음가짐을 가져야하는지 알게됐어요. 항상 기억하고 또 기억할게요.

이번에도 많은 피드백 기다릴게요..! 항상 좋은 피드백 남겨주셔서 감사해요 🙇🏻‍♂️🙇🏻‍♂️

2021-05-20 15:39 UTC, Livenow14 commented
# 학습 로그

## 베포인프라

- Dos와 DDos의 차이를 공부했어요 ([https://livenow14.tistory.com/48](https://livenow14.tistory.com/48))
- EC2 인스턴스의 용량을 늘리는 법을 정리했어요 ([https://livenow14.tistory.com/49](https://livenow14.tistory.com/49))
- 우분투, 도커 설치법을 정리했어요([https://livenow14.tistory.com/50](https://livenow14.tistory.com/50))

## 태그

- Ddos, ec2, ubuntu

## map미션

- 레이어별 테스트를 어떻게 진행해야하는지에 대해 알게됐어요
    - Controller(통신 과정의 request, response 확인)
    - Service(비지니스  흐름)
    - Repository(DB관련 로직)
    - domain(비즈니스 로직)

## 태그

- 인수 테스트, 유닛 테스트, 단위 테스트

2021-05-20 15:40 UTC, Livenow14 commented
안녕하세요 구구 @kang-hyungu 영광스러운 세번째 만남입니다 ㅎㅎㅎㅎ

구구의 피드백을 통해, 이전까지 가볍게 생각했던 부분들을 깊게 생각해봤어요.

코드 작성자가 의미없는 로직을 짜게 된다면, 이를 체크해야하는 다른 개발자들에게 혼란을 키운다는 것을 알게됐어요.

### 중점적으로 한 부분은

### 일급컬렉션 로직 수정

일급컬렉션의 중복 코드들을 전부 제거했어요. 조금만 더 깊게 살펴보면, 짧고, 명확한 코드를 작성할 수 있다는 것을 배웠어요.

### 일급컬렉션 테스트 코드 작성

TDD의 중요성을 다시한번 알게됐어요. 

일급컬렉션의 구현을 테스트 먼저하지 않고, 구현에만 집중했어요. 그러다보니, 테스트를 제대로 못해봤고, 오류를 찾을 수 없었어요. 

처음부터 테스트를 잘 작성했어야, 로직에 신뢰할 수 있게된다는 것을 배웠어요.

### 도메인과 프레임워크 사이

이전까지는, 서비스에 프레임워크가 들어가게 된다면, 어떠한 객체든 프레임워크 위에서 움직여야 한다 오해했어요. 

그래서 일급컬렉션, 도메인 로직등을 깊게 생각하지 않았어요. 

도메인과 테스트를 작성하다보니, 스프링 프레임워크가 객체지향 개발을 지향하고, 이러한 개발을 쉽게해준다는 것을 배웠어요. 

### 결론적으로.

모든 테스트를 진행하려 해봤어요. 이를통해 테스트가 확실해야, 서비스의 품질이 높아진다는 것을 알게됐어요.

테스트를 하면 할수록, 로직이 어떻게 짜여져 있었고, 이상한 부분이 어디였는지 확실히 알게됐어요.

개발관련 시간만큼 테스트의 유지보수 시간도 중요하다는것을 알게된 소중한 시간이었어요.

수정완료 후, 2차 피드백 처음 코드를 보며, 장인정신이 없는, 그냥 동작만 되게하는 코드였다는것을 알게됐고, 이번에도 부끄러웠어요.. 제 코드를 보기 싫어짐이 느껴진다면 자신이 없는 코드라 의심치않아요.

이후 코드 작성에 어떠한 마음가짐을 가져야하는지 알게됐어요. 항상 기억하고 또 기억할게요.

이번에도 많은 피드백 기다릴게요..! 항상 좋은 피드백 남겨주셔서 감사해요 🙇🏻‍♂️🙇🏻‍♂️

2021-05-21 01:13 UTC, kang-hyungu commented
전체 테스트를 돌려보니 깨지는 테스트가 있네요
테스트 점검해보아요~!

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/15669435/119067454-1ee3de00-ba1d-11eb-8c92-bf94454335ca.png">

2021-05-21 01:27 UTC, kang-hyungu requested changes
검프 리팩토링 정말 잘하셨어요 👏 👏 
코멘트 남긴 것만 점검해보시고 리뷰 재요청주시면 빠르게 머지 처리할게요

2021-05-21 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/station/domain/Station.java
> +    public Station() {
기본 생성자를 사용하지 않고 특별히 제공하는 기능이 없다면 삭제하는게 어떨까요

2021-05-21 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/station/ui/StationController.java
> +    private final StationService stationService;
```java
    private final Logger logger = LoggerFactory.getLogger(StationController.class);

    private final StationService stationService;
```

logger를 먼저 써주는게 좋겠네요

2021-05-21 01:27 UTC, kang-hyungu commented on src/main/java/wooteco/subway/station/ui/StationController.java
> +    public ResponseEntity deleteStation(@PathVariable final Long id) {
```suggestion
    public ResponseEntity<Void> deleteStation(@PathVariable final Long id) {
```

2021-05-22 14:32 UTC, Livenow14 commented on src/main/java/wooteco/subway/station/domain/Station.java
> +    public Station() {
특별히 사용되지 않는 기본 생성자는 필요가 없었군요..!

다른 부분에서도 사용되지 않는경우 삭제를 진행했어요 :)

좋은피드백 감사합니다! 

2e3054cb

인자를 포함하는 생성자를 작성 할 때 묵시적인 생성자는 생기지 않는다고 알고있어요.

이런경우 기본생성자를 private, 혹은 protected으로 관리해도 괜찮을듯 한데..

또, 관리해야하는 포인트가 늘어나는거 같기도해요. 저만의 기준만 잡으면 되는 걸까요?

 구구의 의견을 말씀해주실 수 있을까요..?

2021-05-22 14:33 UTC, Livenow14 commented on src/main/java/wooteco/subway/station/ui/StationController.java
> +    private final StationService stationService;
Logger의 순서를 깊게 생각해보지 못한거같아요! 

다른부분도 수정했어요!!
43d1295b

2021-05-22 14:46 UTC, Livenow14 commented
안녕하세요 구구..!

뭔가,, 마지막 PR이 될꺼같아 아쉬워요..ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

저의 개발 태도에 대해 생각해보는 진짜.. 진짜 값진 시간들이었어요. 

아직 정말 모르는게 많은걸 느끼게 됐고, 또, 어떠한 마음가짐으로 코드를 작성해야하는지에 대해 진지하게 고민해봤어요.

구구 피드백을 받기전에는 어쩌면 대충, 어쩌면 당연하게 넘어갔던 부분들이 많았어요. 

이번에 코드작성에 당연한건 없고, 대충 작성되야할 코드는 없다는걸 뼈저리게 느꼈어요.

저를 정말 성장시켜주신거 같아요 고맙습니다 🙇🏻‍♂️🙇🏻‍♂️

우선, 이번 피드백에서 배운 부분을 적어볼까해요.

### 테스트 깨지는 부분

테스트 깨지는부분이 간단한줄 알았는데, 생각해야 할 포인트가 2군데 있었어요.

1. `공유참조 문제`, Factory에서 static으로 도메인을 관리하다보니, 다른 테스트에서 static 필드를 수정했고,  때문에 각 원하던 테스트를 얻지 못했어요. static필드는,  값 비교, 혹은 새로 할당받아 사용하게 변경했어요.
2. `순환참조 문제`, 공유참조 문제는 해결했는데 그래도 테스트가 깨졌어요. 살펴보니, Line이 Sections를 참조하고 있고, Section이 Line을 참조하고 있었어요. 그로인해 Line에만 참조값이 제대로 들어가고, Section에는 Line의 참조값이 들어가지 않는 예외였어요.

```java
# Sections 테스트
@BeforeEach
    void init() {
        singleSection = new Sections(인천1호선.sortedSections());
        doubleSections = new Sections(인천2호선.sortedSections());
        인천1호선_흑기백기구간.changeLine(인천1호선);
        인천2호선_흑기백기구간.changeLine(인천2호선);
        인천2호선_백기낙성대구간.changeLine(인천2호선);
    }
```

해결책으로, Sections의 테스트들이 실행 되기전, 초기화 시, 각 Section에 Line의 참조를 할당하도록 변경했어요. 

순환참조의 무서움을 알게되는 계기였어요.

### 질문점

질문점은 이번에도 👀표시를 해뒀어요..! 

좋은 주말 되길 바랍니다!!

2021-05-22 14:50 UTC, Livenow14 commented on src/main/java/wooteco/subway/station/ui/StationController.java
> +    public ResponseEntity deleteStation(@PathVariable final Long id) {
이부분도 페어와 많이 고민했던 부분이었어요! 반환값이 없는 경우 Void로 명시하는 것이 더 의도를 잘 드러내게 하는군요! 

da70321e

2021-05-23 12:57 UTC, kang-hyungu commented on src/main/java/wooteco/subway/station/domain/Station.java
> +    public Station() {
private으로 기본생성자를 막아도 문제는 없어 보이네요
이 객체를 사용하려면 기본생성자를 쓰지 말라는 의미로 쓸 수 있을 것 같아요

protected는 상속하면 기본 생성자를 쓸 수 있게 되니 안쓰는게 좋죠
나중에 jpa를 쓰게 되면 private으로 기본 생성자를 막으면 안되니 차선책으로 protected를 쓰기는 하는데 이외에는 특별히 쓸 이유가 없겠네요

2021-05-23 13:00 UTC, kang-hyungu approved these changes
검프 피드백 반영 잘 하셨어요 👍 
pr은 머지 처리할게요 수고하셨어요~!

2021-05-23 13:00 UTC, merged