[Spring 지하철 노선도 관리 - 3단계] 에어(김준서) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #140
Opened 2021-05-11 16:19 UTC by KJunseo

안녕하세요 구구!!
어우 3단계가 쉽지 않네요.. 좋은 방식으로 코드를 짠지 확신이 없네요 😭
피드백을 통해 발전해보겠습니다!!

TDD로 진행하려고 해봤는데, 너무 막혀서 결국 거의 프로덕션코드부터 짜고 테스트를 추가하는 식으로 진행했어요ㅠㅠ

### 궁금증
Q1. 이번에 미션을 진행하면서 어떤식으로 의존 관계를 가지게 해야할지에 대해 고민을 많이 했어요.
1) 컨트롤러가 여러 서비스를 가지도록
2) 서비스가 다른 서비스를 가지도록
3) 서비스가 여러 Dao를 가지도록 

다른 경우가 더 있을 수는 있지만, 저는 이번 미션을 진행할때 이 3가지 경우를 고려해봤어요!  결국 서비스에 해당 도메인에 관련된 역할만 주는게 맞다고 생각하여 1번 형식으로 진행했습니다! 상황에 따라 다르겠지만 구구는 보통 어떤 방법을 선호하시는지 궁금해요!

Q2. 3단계를 진행하면서 인수테스트, 도메인 테스트, service 테스트, dao테스트도 함께 작성했어요. 작성하다보니 dao테스트는 굳이 필요한가? 라는 생각이 들었어요. jdbcTemplate이 잘 동작하는지를 확인하는 듯한 느낌이 들어서 믿고 사용해야하는게 아닌가? 라는 생각이 들었어요. 구구는 어떻게 생각하시나요??

Q3. 보통 실무에서 프로젝트를 하거나 할때 설계 순서가 궁금해요! 이번 미션을 진행해보면서 스키마가 주어져서 그런지 설계를 나름 수월(?)하게 할 수 있었던 것 같은데 보통 스키마를 먼저 설계하고 도메인을 설계하는식으로 이루어지나요??

늘 감사합니다! 잘 부탁드려요 🙏🙏🙏

2021-05-12 02:50 UTC, kang-hyungu requested changes
에어 구현하신 내용 확인했어요
피드백 남긴 부분 수정해서 리뷰 재요청주시면 추가 피드백 남길게요
궁금한 점 생기면 언제든 질문주세요

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/Sections.java
> +            if (section.isSameUpStation(lastBase.getDownStationId())) {
객체지향 생활체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2021-05-12 02:50 UTC, kang-hyungu commented on src/test/java/wooteco/subway/section/SectionsTest.java
> +                new Section(2L, 1L, 2L, 3L, 4),
생성자 인자로 숫자 값을 전달하고 있네요
1. 협업하는 개발자가 봤을 때 이 숫자가 어떤 것을 의미하는지 어떻게 알 수 있을까요?
2. section 객체가 각 도메인의 아이디만 갖고 있는게 적절할까요?

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/Section.java
> +    public void updateDistance(Integer distance) {
메서드명이 적절한가요?

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/dao/JdbcSectionDao.java
> +        jdbcTemplate.update(query, downStationId, section.getDistance(), section.getLineId(), section.getUpStationId());
db에는 up_station_id 필드를 수정하는데 변수명은 downStationId라서 헷갈리네요

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +    private SectionCreateResponse updateUpStation(Sections sections, Section newSection) {
updateDownStation 메서드와 거의 동일한 로직이네요
1. 중복을 줄일 방법이 없을까요?
2. 이 메서드는 객체지향적이지 않네요. section 객체에서 업데이트하고 dao로 업데이트 해도 되지 않나요?

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +                downStationSection.getDistance() + upStationSection.getDistance())
거리 계산하는 로직은 서비스가 아닌 도메인 객체에서 처리하도록 변경해보아요

2021-05-12 02:50 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +            sectionDao.deleteByLineIdAndUpStationId(lineId, stationId);
db에 의존적인 코드네요
sections에서는 관련 객체를 삭제하지 않아도 되나요?

2021-05-12 02:54 UTC, kang-hyungu commented
Q1. 이번에 미션을 진행하면서 어떤식으로 의존 관계를 가지게 해야할지에 대해 고민을 많이 했어요.
1) 컨트롤러가 여러 서비스를 가지도록
2) 서비스가 다른 서비스를 가지도록
3) 서비스가 여러 Dao를 가지도록 

다른 경우가 더 있을 수는 있지만, 저는 이번 미션을 진행할때 이 3가지 경우를 고려해봤어요!  결국 서비스에 해당 도메인에 관련된 역할만 주는게 맞다고 생각하여 1번 형식으로 진행했습니다! 상황에 따라 다르겠지만 구구는 보통 어떤 방법을 선호하시는지 궁금해요!

A. 위 세 가지 상황이 다 생길 수 있죠. 중요한 건 각 계층에서 처리해야 할 객체와 의존관계를 가졌는지가 중요하겠네요

Q2. 3단계를 진행하면서 인수테스트, 도메인 테스트, service 테스트, dao테스트도 함께 작성했어요. 작성하다보니 dao테스트는 굳이 필요한가? 라는 생각이 들었어요. jdbcTemplate이 잘 동작하는지를 확인하는 듯한 느낌이 들어서 믿고 사용해야하는게 아닌가? 라는 생각이 들었어요. 구구는 어떻게 생각하시나요??

A. 저도 dao에 대한 테스트는 학습 테스트가 아니면 크게 의미가 없다고 생각합니다. 쿼리가 어떻게 작성되는지 확인하는 용도로 테스트를 짤 수도 있겠네요.

Q3. 보통 실무에서 프로젝트를 하거나 할때 설계 순서가 궁금해요! 이번 미션을 진행해보면서 스키마가 주어져서 그런지 설계를 나름 수월(?)하게 할 수 있었던 것 같은데 보통 스키마를 먼저 설계하고 도메인을 설계하는식으로 이루어지나요??

A. 딱 어떤 것 먼저 한다고 말하긴 어렵네요 ㅎㅎ 요구사항 먼저 파악해보고 먼저 떠올리는 부분 먼저 설계해보는 편이에요 ㅋㅋㅋ

2021-05-15 23:15 UTC, KJunseo commented
안녕하세요 구구! 드디어 다시 제출하네요😄

이번에 구조가 많이 바뀌면서 리팩토링하기가 쉽지 않았어요.
이렇게 구조 자체가 바뀔 때 리팩토링을 어떻게 해야할지 모르겠더라고요.
막 하다보니 3번 정도 다시 시작했어요ㅠㅠ 구구는 대규모(?) 리팩토링을 해야할 때 어떻게 해나가시는지 궁금하네요. 
혹시 tip이 있으시면 알려주실 수 있으실까요??

최대한 객체 지향적이게 짜려고 했어요! 그래서 가능하면 도메인에서 로직을 처리하도록 바꿔봤어요! 그러다보니 sections에서 주로 로직을 처리하게 되었어요.
그런데, sections 자체를 가지고 삽입, 삭제 등을 하다보니 DB에 저장할때 해당 노선의 모든 section을 다 지우고, sections 객체에 들어있는 section을 다시 다 추가하는 식으로 하게되었어요. batchInsert도 쓰긴했지만 그래도 바뀌는 부분만이 아닌 전체를 지우고 다시 넣고 하는 방식이 조금 비효율적이라는 생각이 들긴하네요ㅠㅠ..

이번 미션을 하면서 많이 배워가는 것 같아요!! 이번에도 빡세게 부탁드립니다!🙏🙏🙏

+) 추가로 Entity에 대해 한 가지 궁금한 것이 있는데, 식별자만 가지고 있다면 전부 Entity로 볼 수 있나요? 
예를 들어 이런 테이블이 있을 때

```java
create table if not exists LINE
(
    id bigint auto_increment not null,
    name varchar(255) not null unique,
    color varchar(20) not null,
    primary key(id)
);
```

```java
// 테이블의 모든 필드가 아닌 식별자와 name만을 필드로 가진 객체 
public class Line {
    private Long id;
    private String name;
}
```
```java
// 식별자를 포함한 테이블의 모든 필드 뿐만 아니라 테이블에 없는 다른 필드도 가지는 경우
public class Line {
    private Long id;
    private String name;
    private String color;
    private Sections sections; // 다른 필드
}
```

이런 경우들도 entity라고 볼 수 있는 걸까요?

2021-05-16 06:07 UTC, kang-hyungu commented
1. 대규모 리팩토링이 쉽지 않죠. 현업에서도 대규모 리팩토링이 쉽지 않다보니 레거시가 축적되다가 차세대 프로젝트를 띄워서 다시 만들고 하는 안타까운 상황이 생기기도 하죠.
리팩토링을 하기 위해서 선행되어야 하는 일은 테스트 코드 작성입니다. 내가 수정한 내용이 정상적으로 동작하는지 확인하는게 오래 걸리고, 수동으로 매번 확인해야된다면 너무 힘들어요. 그냥 새로 만들고 말지라는 생각을 수차례하게 되죠 ㅎㅎ;
그래서 테스트 코드를 처음부터 작성해둬야 변경사항이 생겼을 때 두려움 없이 빠르게 개선해나갈 수 있습니다. 테스트 코드 작성도 쉬운 일은 아니지만 한 번에 크게 바꾸는 것보다 비용이 적습니다.
결론은 테스트 코드를 작성하시면 됩니다!

2. 이미 Line 테이블이 Line 객체와 매핑된 상태에서 다른 필드로 구성된 객체가 있다면 엔티티로 보기 어려울 것 같네요
예시의 내용만 봤을 때는 식별자가 Line과 동일하게 사용되는걸로 보여서요 ㅎㅎ;
다른 객체와 구별되는 식별자를 두는 것을 엔티티라고 부르지만 보통 db 테이블에 매핑하는 객체도 엔티티라고 부릅니다.
테이블과 완벽히 필드가 동일해야 엔티티라는 규칙이 있는 건아니고 특정 테이블과 매핑되고 식별자를 가지면 엔티티로 보시면 됩니다.

2021-05-16 06:39 UTC, kang-hyungu requested changes
에어, 수정하신 내용 확인했어요
코드 아주 깔끔하게 잘 변경하셨네요 👏 
살짝 다듬어보면 좋을 부분에 피드백 남겼으니 수정해서 리뷰 재요청주세요
질문주신 내용도 코멘트 남겼으니 참고하세요~

2021-05-16 06:39 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +        if (errors.hasErrors()) {
보통 validation 어노테이션을 사용하면 exception advice에서 처리하도록 만듭니다.
안그러면 매번 컨트롤러에서 메서드마다 지금처럼 if절로 조건을 체크하는 로직을 만들어야 하니깐요.

2021-05-16 06:39 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/service/LineService.java
> +    public void addSection(Long id, SectionCreateRequest request) {
```suggestion
    public void addSection(Long lineId, SectionCreateRequest request) {
```
id만 쓰니까 헷갈리네요 ㅎㅎ;

2021-05-16 06:39 UTC, kang-hyungu commented on src/main/java/wooteco/subway/line/service/LineService.java
> +        line.updateSections(sections);
updateSections 이라고 쓰면 라인 객체 내에서 section과 관련된 변경 작업이 있는 것으로 오해합니다
지금은 jdbc를 써야하는 상황이니 어쩔 수 없이 setter로 표현하는게 낫겠네요

```suggestion
        line.setSections(sections);
```

2021-05-16 06:39 UTC, kang-hyungu commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +    public void synchronizeDB(Line line) {
메서드명이 이상합니다. db랑 싱크를 맞추는 일이 아닌 section 테이블에 line과 관련된 처리를 하는 것으로 보입니다.
비즈니스 용어로 읽을 수 있는 메서드명 없을까요?

2021-05-16 06:39 UTC, kang-hyungu commented on src/test/java/wooteco/subway/DummyData.java
> +public class DummyData {
한 클래스에 모아두면 이 클래스가 너무 비대해질거에요.
각 클래스마다 픽스쳐(fixture) 클래스를 만들어주는걸 추천해요

2021-05-16 06:39 UTC, kang-hyungu commented on src/test/java/wooteco/subway/section/SectionRequestForm.java
> +public class SectionRequestForm extends RequestForm {
RequestForm으로 추상화하고 각 도메인마다 확장해서 사용한다면 관리해야될 클래스가 너무 많아지지 않을가요?
RequestForm에 구현한 내용을 상위 클래스인 AcceptanceTest로 옮기면 인수테스트 하려는 클래스들이 자연스럽게 구현된 http 요청 메서드를 사용할 수 있겠네요

2021-05-17 07:14 UTC, KJunseo commented
구구 말씀해주신 부분 반영했습니다!
리팩토링 할 때는 힘들었지만 이런 코멘트 받으니 기분이 엄청 좋네요 ㅎㅎ
>코드 아주 깔끔하게 잘 변경하셨네요 👏

더 보완할 부분 보이시면 얼마든지 말씀해주세요!! 구구랑 미션 진행하면서 많이 발전하는 것 같아 매우 좋습니다!
리뷰 잘 부탁드려요!!🙏

2021-05-17 07:32 UTC, KJunseo commented
궁금증이 하나 떠올랐어요!
현재 LineService가 StationService와 SectionService를 가지고 있는데, StationService의 findById() 메서드 같이, service 계층에서만 호출하는 메서드들은 반환 값이 dto가 아니라 도메인이어도 상관 없을까요? 

저는 개인적으로 Controller - Service 사이 통신은 dto로 해주고, Service - Dao 사이의 통신은 엔티티나 도메인으로 해주는 게 맞다고 생각하는데 service - service인 경우는 도메인으로 해도 되지 않을까라는 생각이 들어서요! 구구 생각이 궁금합니다!

2021-05-17 08:05 UTC, kang-hyungu commented
Q.
궁금증이 하나 떠올랐어요!
현재 LineService가 StationService와 SectionService를 가지고 있는데, StationService의 findById() 메서드 같이, service 계층에서만 호출하는 메서드들은 반환 값이 dto가 아니라 도메인이어도 상관 없을까요?

저는 개인적으로 Controller - Service 사이 통신은 dto로 해주고, Service - Dao 사이의 통신은 엔티티나 도메인으로 해주는 게 맞다고 생각하는데 service - service인 경우는 도메인으로 해도 되지 않을까라는 생각이 들어서요! 구구 생각이 궁금합니다!

A.
저는 서비스도 용도에 따라 나누는 편이에요. 도메인 서비스는 도메인을 반환하도록 설계합니다. 이것도 개발자마다 설계하는데 차이가 있을 수 있어서 에어가 규칙을 정하고 진행하시면 됩니다. 나중에 현업에서는 팀에서 정한 룰을 따르시면 될거에요!

2021-05-17 08:05 UTC, kang-hyungu approved these changes
에어 피드백 반영 잘 하셨어요 👏 
이번 미션은 머지 처리해도 되겠네요.
추가 피드백은 다음 미션 진행할 때 참고하세요
구현하느라 수고하셨어요~!

2021-05-17 08:06 UTC, merged

2021-05-20 17:02 UTC, KJunseo commented
# [학습로그] 배포 인프라 미션

총 정리 : [[새배내] 배포 인프라 미션을 하며 새로 배운 내용](https://velog.io/@max9106/wtc-learning6)

## bastion 서버
침입 차단 소프트웨어가 설치되어 내부와 외부 네트워크 사이에서 일종의 게이트 역할을 수행하는 호스트. 
보호해야할 네트워크에 접근하기 위해 유일하게 외부에 노출되는 호스트를 말한다.

WAS나 DBMS 서버 등은 외부에 노출되어서는 안된다. 따라서 이번 서버들은 사설망에 위치시키고 IP 또한 public이 아닌 private IP로 접근하도록 해야한다.

이때 bastion 서버를 public subnet에 두어 public IP로 접근할 수 있도록 하고, 내부 서버들은 bastion 서버를 통해서만 접근한다.

이를 위해 bastion 서버에는 여러 보안 관련 처리를 해줘야한다.

## 태그
bastion host

<hr>

## 스레드 덤프
프로세스에 속한 모든 스레드의 상태를 기록해놓은것. 직접 실행시킨 Java 응용 프로그램의 스레드와 JVM 내부적으로 존재하는 스레드로 나뉘게 됨.

스레드 덤프를 통해 어플리케이션에 발생한 문제를 분석하거나, 성능 최적화에 필요한 정보들을 보여준다.

### 스레드 덤프 분석
스레드 상태 
- NEW : 생성되었지만 실행되지 않은 상태
- RUNNABLE: 현재 CPU를 점유하고 작업 수행 중인 상태
- BLOCKED: Monitor를 획득하기 위해 다른 스레드가 락을 해제하기를 기다리는 상태
- WAITING: 대기하고 있는 상태
- TIMED_WAITING: 대기하고 있는 상태. WAITING과 다른 점은 최대 대기 시간을 명시해주면 외부 변화 뿐만 아니라 시간에 의해서도 대기상태가 해제될 수 있다는 점.

`쓰레드이름 우선순위 쓰레드ID 쓰레드상태`로 쓰레드 정보가 나타난다.

## 태그
스레드 덤프

<hr>

## Docker
컨테이너 기반의 오픈소스 가상화 플랫폼이다.

#### 컨테이너 
컨테이너는 격리된 공간에서 프로세스가 동작하는 기술을 말한다.

다양한 프로그램(백엔드 프로그램, DB서버 등), 실행 환경을 컨테이너로 추상화하고 동일한 인터페이스를 제공하여 프로그램의 배포 및 관리를 단순하게 해주는 것이다.

컨테이너는 이미지를 실행한 상태라고 볼 수 있다. 

#### 이미지
이미지는 컨테이너 실행에 필요한 파일과 설정 값 등을 포함하고 있는 것으로 상태 값을 가지지 않고 변하지 않는다.  

같은 이미지에서 여러개의 컨테이너를 생성할 수 있으며 컨테이너의 상태가 바뀌거나 컨테이너가 삭제되더라도 이미지는 그대로 남아있다.

이미지는 컨테이너를 실행시키기 위한 모든 정보를 가지고 있기 때문에, 따로 의존성을 설치하거나 할 필요가 없다. 미리 만들어 놓은 이미지를 다운받고 컨테이너를 만들면 된다.

## 태그
docker

<hr>

## Proxy
서버와 서버 사이에서 중간 다리 역할을 한다. 보안상 이유로 직접 통신할 수 없는 두 서버 사이에서 대신 통신을 수행해주는 것을 말한다.

### Forward Proxy
프록시 서버를 클라이언트와 원격 리소스 사이에 위치시키는 방법이다. 프록시 서버는 클라이언트가 요청한 리소스를 원격 리소스에서 가져와 클라이언트에게 응답해준다. 캐시를 이용하여 다음 요청시 캐시된 데이터를 제공해주기도 한다.

Forward Proxy는 대역폭을 감소시킬 수 있고, 접근 정책 구현에 있어 다루기 쉬우면서 비용도 저렴하여 기업 환경에서 많이 사용한다.

### Reverse Proxy
프록시 서버를 인터넷 리소스 또는 인트라넷 리소스 앞에 위치시키는 방법이다. 보안 때문에 사용하는 방법이다. 

보통 기업 네트워크 환경에서는 내부 네트워크(WAS, DB서버)와 외부 네트워크 사이에 DMZ라고 부르는 구간이 존재한다. DMZ에는 메일 서버, 웹 서버, FTP 서버 등 외부 서비스를 제공하는 서버가 위치하게 된다.Reverse Proxy를 DMZ에 두고 실제 서비스 서버는 내부망에 위치시킨다. 

WEB(Apache, nginx) - WAS(Tomcat)으로 분리된 구조에서 WEB부분이 Reverse Proxy라고 볼 수 있다.(한 서버에 WEB, WAS가 둘 다 존재한다면 reverse proxy라고 볼 수 없다.)

보안성 향상, 확장성 향상, 웹 가속(압축/SSL 처리로 백엔드 리소스 확보/캐싱)의 이점이 있다.

## 태그
proxy, forward proxy, reverse proxy

<hr>

## Nginx
경량 웹 서버이다. 더 적은 자원으로 더 빠르게 서비스한다. 클라이언트의 요청에 맞게 정적 파일을 응답해주는 HTTP 웹 서버로 활용할 수도 있고, Reverse Proxy로 활용하여 WAS의 부하를 줄여주는 로드 밸런서로 활용되기도 한다.

Event-Driven 구조로 동작하며 비동기 방식으로 요청들을 동시에 수행할 수 있다. 한 개 또는 고정된 프로세스만 생성해서 사용한다. 새로운 요청이 들어오더라도 새로운 프로세스와 스레드를 생성하지 않는다. 따라서 단일 서버에서도 수만 개의 동시 연결을 처리할 수 있다.

Nginx는 하나의 Master Process와 여러 Worker Process로 구성되어 있다. Master는 설정 파일을 읽기, 유효성 검사, Worker 프로세스 관리의 역할을 한다. Worker는 모든 요청을 처리한다. 

## 태그
Nginx, web server, reverse proxy