[Spring 지하철 노선도 관리 - 3단계] 파즈(강승윤) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #144
Opened 2021-05-11 17:16 UTC by Be-poz

안녕하세요 코니~! 월,화 불태웠습니다!! 구현하면서 리팩토링 할 것들 조금씩 하긴했는데 막판에 시간 쫓겨서 마지막 리팩토링을 못한 상태에요!  
디미터 법칙 어긴 것도 눈에 보이던게 있었는데... 아무튼 그거는 내일 중으로 더 고쳐보겠습니다! 테스트 코드는 꼼꼼히 짰어요!  
이번 단계에서 트랜잭션 엮어주려고 학습로그 정리한 것도 있는데 아직 적용을 못했네요,,, 리뷰 잘 부탁드리겠습니다!!  
<br/>
# 학습로그
## @Transactional에 대해
* [링크](https://github.com/Be-poz/TIL/blob/master/Spring/%40Transactional%20%EC%97%90%20%EB%8C%80%ED%95%B4.md)
## 키워드
* {@Transactional}, {isolation level}

2021-05-13 15:43 UTC, choihz requested changes
안녕하세요, 파즈!

지하철 노선도 미션 3단계를 잘 구현해 주셨네요 💯 궁금한 점 또는 의견이 있으시다면 언제든 DM 또는 코멘트 주세요~!

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/line/LineRequest.java
>      private Long downStationId;
`upStationId`, `downStationId`가 `null`이면 어떻게 되나요?

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/line/LineDao.java
> +            line.setSections(new Sections(sectionDao.findSectionsByLineId(id)));
DAO에서 다른 DAO를 사용하는 구조가 괜찮은 건지 고민이 되네요.... DAO는 보통 테이블과 1:1이고 딱 DB 접근의 역할만을 가지는 게 좋다는 생각이 들어서 이런 구조가 좀 어색하게 느껴지긴 해요. 파즈도 구현하시면서 고민이 많으셨을 것 같은데 어떤 이유로 이 방법을 선택하셨는지 궁금해요~

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/line/LineDao.java
> +        }
반복문 안에서 DB에 접근하는 것은 지양해야 하는데요, 어떻게 이를 개선할 수 있을까요?

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
1 - 2가 있고 3 - 2를 추가하는데, 3 - 2의 거리가 1 - 2의 거리 이상이어도 추가되고 있네요.

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/line/LineService.java
>          }
노선을 삭제하면 구간은 어떻게 되나요?

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionDao.java
> +        String sql = "insert into SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) values(?,?,?,?)";
여기서만 컬럼명에까지 대문자를 사용하신 이유가 있으신가요?

2021-05-13 15:43 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    public void deleteSectionWithContainingEndStatonCase() {
```suggestion
    public void deleteSectionWithContainingEndStationCase() {
```

테스트를 아주 꼼꼼하게 작성해 주셨네요!

2021-05-13 15:43 UTC, choihz commented on src/test/java/wooteco/subway/station/StationServiceTest.java
> +        jdbcTemplate.execute("alter table STATION alter column ID restart with 1");
변경이 없어 여기에 남겨요.
`stationName`은 한곳에서만 사용되는데 인스턴스 변수로 뺄 필요가 있을까요?

2021-05-13 15:43 UTC, choihz commented on src/test/java/wooteco/subway/station/StationDaoTest.java
> +        jdbcTemplate.execute("alter table STATION alter column ID restart with 1");
변경이 없어 여기에 남겨요.
1. 클래스의 상수 네이밍 컨벤션은?!
2. 상수와 인스턴스 변수 사이에는 공백 라인을 두는 게 좋아요~ 가독성이 훨씬 좋아집니다.

2021-05-13 15:43 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionDao.java
> +    public boolean isEndStation(Long lineId, Long stationId) {
DAO에 로직이 다소 많은데, DAO의 역할을 다소 벗어난 게 아닐까 하는 생각이 들어요. 코드를 읽고 파악하기도 좀 어렵고요. 최대한 도메인 객체로 뺄 수 있을까요?

2021-05-13 16:20 UTC, Be-poz commented on README.md
> +- [ ] 구 삭제
요즘 한글을 치면 마지막 글자가 이렇게 빠지더라구요.... 리드미도 누락됐네요 ㅜ

2021-05-14 03:08 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionsTest.java
> +    private LineDao lineDao;
맞네요!! 수정했습니다!!

2021-05-14 05:36 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionService.java
> +    private SectionDao sectionDao;
```java
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        Set<ConstraintViolation<Line>> result = validator.validate(line);
```


``Line`` 필드 내부에 ``@NonNull``과 같은 어노테이션을 두고 ``Line``을 사용하는 곳에서 위와 같이 사용하려했는데 무리가 있다고 생각했습니다. 그래서 내부 메소드로 그냥 값 검증 하는식으로 했는데 코니는 어떤식으로 처리할 것 같은지 의견 정말 듣고싶습니다!!

2021-05-14 05:37 UTC, Be-poz commented on src/main/java/wooteco/subway/line/Line.java
>      public Line(Long id, String name, String color) {
```java
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        Set<ConstraintViolation<Line>> result = validator.validate(line);
```


``Line`` 필드 내부에 ``@NonNull``과 같은 어노테이션을 두고 ``Line``을 사용하는 곳에서 위와 같이 사용하려했는데 무리가 있다고 생각했습니다. 그래서 내부 메소드로 그냥 값 검증 하는식으로 했는데 코니는 어떤식으로 처리할 것 같은지 의견 정말 듣고싶습니다!!

2021-05-14 07:54 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionController.java
> +@Controller
리턴 타입들이 모두 ``ResponseEntity`` 이기 때문에 ``@RestController`` 를 사용할 필요가 없다고 생각해서 ``@Controller``를 사용했습니다. 명시를 하기위해서 ``@RestController`` 를 사용하는 것이 더 적절할까요 ??

2021-05-14 07:58 UTC, Be-poz commented on src/main/java/wooteco/subway/station/StationService.java
>      public void deleteStation(Long id) {
이 부분은 항상 고민이 드는 문제입니다! 클래스 명이 ``XXXService`` 라면 ``deleteXXX``, ``modifyXXX``, ``createXXX`` 에서 ``XXX``를 생략해도 되는걸까요!? 생략을 했을 시에 만약 XXX가 아닌 다른 것 들을 create, delete, modify 할 일이 생겼을 시에 그 경우에만 명시하면 되는걸까요!?

2021-05-14 07:59 UTC, Be-poz commented on src/main/java/wooteco/subway/station/StationService.java
>      public void deleteStation(Long id) {
그런데 현재 제 파일에는 생략한 것도 있고 붙여준 것도 있네요,,, 생략하는걸로 통일시키겠습니다~!

2021-05-14 08:10 UTC, Be-poz commented on src/main/java/wooteco/subway/line/LineRequest.java
>      private Long downStationId;
``@NotNull``을 추가해주었습니다. 궁금한 것이 있습니다! ``int``, ``long`` 과 같이 ``null``을 넣을 수 없는 타입으로 변경한다면 괜찮나요?? 아니면 컴파일 에러가 발생하니깐 문제가 생길 수도 있을 것 같은데 그렇다면 모든 도메인 필드의 타입은 primitive 타입이 아니라 reference 타입으로 사용하는 것이 옳은건가요 ?

2021-05-14 08:19 UTC, Be-poz commented on src/main/java/wooteco/subway/line/LineDao.java
> +            line.setSections(new Sections(sectionDao.findSectionsByLineId(id)));
```java
    public Optional<Line> findById(Long id) {
        String sql = "select id, name, color from LINE where id = ?";
        try {
            Line line = jdbcTemplate.queryForObject(sql, lineRowMapper(), id);
            line.setSections(new Sections(sectionDao.findByLineId(id)));
            return Optional.ofNullable(line);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }
```

``Line``에는 ``Section``에 대한 정보를 가지고 있습니다. 해당 정보를 가지고 오기 위해서 처음에는 조인을 사용할까 라고 생각을 했습니다. 그런데 ,``lineDao``인데 ``Section`` 테이블을 땡겨오는 것이 과연 맞는 것인가 라는 의문이 들었습니다. ``Section``테이블에 대한 데이터를 담당하는 ``SectionDao``를 이용하는 것이 맞지 않나? 라고 생각해서 사용하게 되었습니다.  

물론 ``Section``에 관한 정보는 제외하고 ``Line``을 채우고 난 뒤에, ``LineService``에서 ``SectionService``를 호출해서 값을 가져온 뒤에 ``Line``을 완성하는 방법도 있기에 고민했습니다. 서비스에서 다른 서비스를 호출해서 값을 가지고 온 뒤에 서비스에서 객체를 조합하는 방법이나 다오에서 다오를 호출하고 객체를 조합하는 방법이나 그렇게 큰 차이가 있을까? 라고 생각했습니다.  

무엇보다도 ``lineDao.findById``인데, 미완성된 ``Line``을 반환해준다는 것이 어색하다고 느껴졌습니다. 그래서 ``SectionDao``를 이용해서 ``Line``을 완성시켜준 뒤에 반환해주었습니다.

2021-05-14 08:58 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
``refactor: 거리 예외에 대한 테스트 보강``  
이 커밋 한 번 봐주시겠어요?! 업스테이션이 겹치는 경우에는 테스트 되어있는데 다운스테이션이 겹치는 경우에 테스트를 못해서 그런 것인가 하고 테스트를 보강해봤는데 통과가 돼요!  
그리고 방금 Postman으로 둘 다 확인해봤는데 추가가 안되고 있어요!! 다시 한 번 확인 해보시겠어요!?

2021-05-14 11:50 UTC, Be-poz commented on src/main/java/wooteco/subway/line/LineService.java
>          }
``foreign key (line_id) references line (id) on delete cascade``  
``Section``에 해당 속성을 걸어주었습니다. 외래키를 보통 사용을 안한다고는 하지만요 . ..

2021-05-14 11:57 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionDao.java
> +        String sql = "insert into SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) values(?,?,?,?)";
테이블 명만 대문자로 일치시켰습니다~!

2021-05-14 11:59 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    public void deleteSectionWithContainingEndStatonCase() {
이런거는 어떻게 발견하시는거죠... 매의 눈 인정합니다

2021-05-14 12:38 UTC, Be-poz commented on src/test/java/wooteco/subway/station/StationServiceTest.java
> +        jdbcTemplate.execute("alter table STATION alter column ID restart with 1");
맞습니다 ... 수정완료..!!

2021-05-14 17:00 UTC, Be-poz commented on src/test/java/wooteco/subway/station/StationDaoTest.java
> +        jdbcTemplate.execute("alter table STATION alter column ID restart with 1");
이거를 왜 소문자로 썼던 걸까요... ㅜㅜㅜㅜ 수정했습니다

2021-05-16 13:08 UTC, choihz commented on src/main/java/wooteco/subway/line/Line.java
>      public Line(Long id, String name, String color) {
네, 저도 여태까지 해온 것처럼 내부 메서드에서 검증할 것 같아요~

2021-05-16 13:09 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionController.java
> +@Controller
넵! 요즘은 디폴트가 `@RestController`이고 필요한 경우에만 `@Controller`를 사용하는 것 같아요.

2021-05-16 13:11 UTC, choihz commented on src/main/java/wooteco/subway/line/LineRequest.java
>      private Long downStationId;
타입은 일괄적으로 정하는 게 아니라 그 값의 특성에 맞게 정하는 게 옳은 것 같아요. `LineRequest`에서 보면 `distance`는 `int`인 게 적절하고 `upStationId`와 `downStationId`는 nullable한 게 적절해 보여요.

2021-05-16 13:13 UTC, choihz commented on src/main/java/wooteco/subway/line/LineService.java
>          }
연관 객체 삭제 문제는 정책적인 부분인 거 같은데, 노선과 구간 관계는 노선이 삭제되면 이 노선 안의 구간이 삭제되도록 해도 무방해 보여요! 요구사항에 명시된 건 아니므로 선택의 여지가 있긴 합니다.

2021-05-16 13:15 UTC, Be-poz commented on src/main/java/wooteco/subway/line/LineDao.java
> +        }
코니 지금 확인중이시군요! 오늘까지 데드라인인 스터디가 하나 있어서... 아마 내일 리뷰요청 누를 것 같아요! 이 피드백하고 마지막 피드백인 도메인으로 로직 빼는거를 아직 못했습니다 ㅜㅜ  

안그래도 이 피드백 잘 모르겠어서 물어보려고 했어요... 쿼리문으로 조인 걸어서 한 번에 들고와야 되는걸까요 ?! 아니면 다른 방법이 있다면 키워드 하나만 알려주시면 감사하겠습니다..

2021-05-16 13:28 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
저는 아래 순서로 직접 요청해서 테스트해 보았어요!

```
POST /stations

{
  "name": "삼성역"
}
```

```
POST /stations

{
  "name": "강남역"
}
```

```
POST /stations

{
  "name": "신도림역"
}
```

```
POST /lines

{
  "name": "2호선",
  "color": "green",
  "upStationId": 1,
  "downStationId": 2,
  "distance": 3
}
```

```
POST /lines/1/sections

{
  "upStationId": 3,
  "downStationId": 2,
  "distance": 3
}
```

이렇게 했을 때 200 응답이 오고, 여기서 `GET /lines/1` 요청을 보내면 아래 응답이 와요.

```
{
    "id": 1,
    "name": "2호선",
    "color": "green",
    "stations": [
        {
            "id": 1,
            "name": "삼성역"
        },
        {
            "id": 2,
            "name": "강남역"
        }
    ]
}

```

제가 뭔가 잘못한 부분이 있을까요?

2021-05-16 13:35 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
삼성 - 강남 거리:3  
신도림 - 강남 거리:3으로 추가 시도   => 거리가 기존의 삼성-강남과 같은 3이기 때문에 추가 실패  

그 결과  
```java
{
    "id": 1,
    "name": "2호선",
    "color": "green",
    "stations": [
        {
            "id": 1,
            "name": "삼성역"
        },
        {
            "id": 2,
            "name": "강남역"
        }
    ]
}
```

정상 출력된거 아닌가요?!

2021-05-16 13:42 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
```
POST /lines/1/sections

{
  "upStationId": 3,
  "downStationId": 2,
  "distance": 3
}
```

위 요청에 200 응답이 오고 있어요! 그리고 위 응답을 받은 후 DB를 조회해 보면

<img width="431" alt="스크린샷 2021-05-16 오후 10 41 55" src="https://user-images.githubusercontent.com/18049492/118399409-f3b56380-b697-11eb-88e4-ea4e819bf174.png">
위와 같은 상황이에요.

2021-05-16 13:49 UTC, choihz commented on src/main/java/wooteco/subway/line/LineDao.java
> +        }
천천~히 해주셔도 돼요! 저도 리뷰가 많이 쌓여 있어서 😭

`SELECT * FROM SECTION WHERE LINE_ID IN (:ids)` 같은 쿼리를 생각했어요! 잘 안 된다면 넘어가셔도 됩니다~

2021-05-16 13:49 UTC, Be-poz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
오잉!? 한 번 알아보겠습니다! 꼼꼼히 봐주셔서 감사해요...

2021-05-16 13:51 UTC, Be-poz commented on src/main/java/wooteco/subway/line/LineDao.java
> +        }
ㅋㅋ쿠ㅜㅜ 뭔가 웃기면서도 슬픈 상황이네요... 코니 화이팅!!! 여유롭게 제출하겠습니다!!

2021-05-17 14:20 UTC, Be-poz commented
안녕하세요 코니! 피드백 반영했습니다.  
``SectionService``에 있던 로직들을 ``Sections``에 빼는 작업을 하며 느낀 장점은 처음에 그냥 서비스에서 처리하려고 할 때에는 dao에 쿼리를 날리는 회수가 굉장히 많았는데 도메인에서 처리를 하게되니 이 횟수가 굉장히 줄어들었다는 점입니다. 그리고, 도메인에 따로 빼면 예외 처리가 귀찮을 것이라고 예상했는데 오히려 더 편하게 예외처리에 대한 로직을 사용할 수가 있었습니다.  

api 오류 또한 도메인으로 로직을 빼는 과정에서 고쳐놨습니다!!  
``Line``이 ``Sections``에 대한 정보를 가져오는 과정에서 n번 쿼리를 날리는 부분도 처리했습니다. 생각해보니 ``in:ids``를 사용할 필요없이 ``Section`` 테이블의 모든 정보를 가져오면 되는거였어서 가져오는데에는 큰 문제가 없었습니다. 문제는 ``Line``에 ``Sections``를 할당하는 과정이었습니다. 이 부분은 부득이하게 2중 for문을 돌렸고 혹시 몰라서 이전의 코드를 지우지 않고 주석처리를 해놓고 depth 관리를 해두지 않았습니다!  

리뷰해주셔서 감사합니다~!

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/line/LineServiceTest.java
> +    private Station station2;
사용하지 않는다면 지워 주세요~

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionDaoTest.java
> +class SectionDaoTest {
DAO 테스트는 컨텍스트를 다 띄울 필요 없이 `@JdbcTest`를 이용해도 괜찮을 것 같네요.

- [Spring Boot Features: 26.3.17. Auto-configured JDBC Tests](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-jdbc-test)
- [Spring JdbcTemplate Unit Testing](https://www.baeldung.com/spring-jdbctemplate-testing)

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    public void saveSectionWithUpEndStiationCase() {
```suggestion
    public void saveSectionWithUpEndStationCase() {
```

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    public void deleteSectionWithContainingEndStatonCase() {
오타 수정이 안 됐어요!

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/station/StationDaoTest.java
>          assertThat(stationDao.findByName(savedStation.getName()).isPresent()).isTrue();
```suggestion
        assertThat(stationDao.findByName(savedStation.getName())).isPresent();
```

😎

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/section/Sections.java
> +                && !stations.contains(new Station(sectionDto.getUpStationId(), "temp")))
`temp`....?

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/section/Sections.java
> +    public boolean canAttachesAfterEndStation(SectionDto sectionDto) {
```suggestion
    public boolean canAttachAfterEndStation(SectionDto sectionDto) {
```

1. 조동사 다음엔 동사 원형~ 😎
2. 도메인이 DTO를 아는 구조가 된 것 같은데 어떻게 생각하시나요?

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/line/LineDao.java
> +        }
`List<Section> sections`에서 `lineId`를 키로 하는 `Map` 만들어서 처리 가능하지 않을까요?

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/station/StationDao.java
> +            return Optional.ofNullable(new Station(id, jdbcTemplate.queryForObject(sql, String.class, id)));
이런 경우는 가독성 고려해서 변수로 빼는 게 더 좋겠네요 ㅎㅎ

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/station/StationController.java
>      }
이미 특정 구간에 속한 역을 삭제하면 어떻게 되나요~?

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/station/StationDaoTest.java
> +    private static final String STATIONNAME1 = "잠실역";
```suggestion
    private static final String STATION_NAME1 = "잠실역";
```

또는 테스트 코드니까 그냥 `잠실역` 한글 변수명 사용해도 되지 않을까요?

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        jdbcTemplate.execute("alter table LINE alter column ID restart with 1");
초기화 코드가 너무 기네요 😭

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        stationDao.save("fifth");
테스트 코드지만 그래도 이왕이면 진짜 데이터처럼(~~역) 넣어 주세요. 나중에 헷갈릴 수도 있어요.

2021-05-18 14:52 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    }
이거는 두 케이스 각각 단독으로 테스트 메서드 및 이름을 가질 만한 것 같아요. 단언문이 여러 개인 것들 중 분리될 만한 건 분리해 볼까요?

2021-05-18 14:52 UTC, choihz commented on src/main/java/wooteco/subway/section/SectionController.java
> +    }
```
HTTP/1.1 400 
Connection: close
Content-Type: application/json
Date: Tue, 18 May 2021 14:43:36 GMT
Transfer-Encoding: chunked

{
    "detail": "역 사이에 새로운 역을 등록할 경우 기존 역 사이 길이보다 크거나 같으면 등록을 할 수 없습니다.",
    "message": "SECTION_EXCEPTION",
    "timeStamp": "2021-05-18T23:43:36.71324"
}

```
💯

2021-05-18 14:52 UTC, choihz requested changes
안녕하세요, 파즈!

피드백을 잘 반영해 주셨네요~! 마지막으로 코멘트 몇 개 더 남겼는데 확인 부탁드려요. 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2021-05-19 08:35 UTC, Be-poz commented on src/main/java/wooteco/subway/section/Sections.java
> +                && !stations.contains(new Station(sectionDto.getUpStationId(), "temp")))
내부에서 동등성 비교를 할 때에 ``id``값으로만 진행을 합니다.  ``stations``에 해당 ``Station``이 들어가있는지 확인하기 위해 ``sectionDto.getUpStationId()``의 값을 가진 ``Station``을 만들고 확인해주는 작업이여서 ``name``이 어떤 값이 들어가도 상관이 없어서 ``temp``로 그냥 넣어줬어요!

2021-05-19 08:45 UTC, Be-poz commented on src/main/java/wooteco/subway/section/Sections.java
> +    public boolean canAttachesAfterEndStation(SectionDto sectionDto) {
해당 dto가 클라이언트한테 돌려주는 view의 성질을 가지고 있는 dto가 아니고,  ``SectionDto``의 내부 값이 추가되거나 삭제된다고 하더라도 ``upStationId``와 ``downStationId``는 계속해서 가지고 있을 것이라고 생각했기 때문에 크게 상관없다고 생각했습니다!!  
하지만, 이런 이유가 있다고 하더라도 결합도가 생긴다는 점이 굉장히 걸리긴 합니다!! 그래서 수정했습니다!!

2021-05-19 11:07 UTC, Be-poz commented on src/main/java/wooteco/subway/station/StationController.java
>      }
이걸 생각못했었네요 .. 구간에 등록되어 있지 않은 경우에만 삭제할 수 있게끔 수정했습니다~!

2021-05-19 11:08 UTC, Be-poz commented on src/test/java/wooteco/subway/station/StationDaoTest.java
> +    private static final String STATIONNAME1 = "잠실역";
주어진 테스트코드들을 보면 한글명으로 다 되어있었는데 이걸로 해도 되는지 아리송 했어요! 다음번 테스트코드 부터는 한글명 적극 사용하겠습니다~!

2021-05-19 11:09 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        jdbcTemplate.execute("alter table LINE alter column ID restart with 1");
이거 따로 sql 파일로 뺼까요............

2021-05-19 11:13 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        jdbcTemplate.execute("alter table LINE alter column ID restart with 1");
그게 나을 듯해요 😭

2021-05-19 17:50 UTC, Be-poz commented
안녕하세요 코니 ,``@JdbcTest``를 이용해서 DaoTest들을 수정해봤습니다. 빈으로 ``JdbcTemplate``만 주길레 추가로 주입이 필요한 것들은 ``@Import``를 이용했습니다. ``@JdbcTest``에 대해서 한 가지 궁금한 점이 있었는데요!  

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/jdbc/JdbcTest.html  

이곳 링크를 보면 다음과 같은 문구가 있습니다.  

> By default, tests annotated with `@JdbcTest` are transactional and roll back at the end of each test. They also use an embedded in-memory database (replacing any explicit or usually auto-configured DataSource).

인 메모리 디비를 사용하는 것이라면 어차피 테스트 종료 시에 날아가버리는데 롤백이 의미가 있는건가요 ??  
만약, 인 메모리 디비가 아닌 제가 따로 mysql을 dataSource에 등록해놓고 해당 dataSource로 돌아가게끔 했을 그런 경우에만 의미가 있는거라고 생각해도 되는건가요 ??  

그리고 each test 라길레 메소드 단위로 롤백될 줄 알고 truncate 구문들이 필요없겠구나 했는데 그건 아니더라구요 이 부분은 너무 아쉬웠습니다...  

<br/>

https://github.com/woowacourse/atdd-subway-map/pull/144#discussion_r634457451  

그리고 이 리뷰에 대해서 고민을 조금 해봤습니다!  

처음에는 모든 테스트 메소드에 ``@Rollback``을 붙이고 alter, truncate 와 같은 DDL문을 생략하고 DML만 ``BeforeAll``에 하면 되지 않을까? 라고 생각했는데 빈 주입이 안되는지 NPE가 뜨더라구요!! 그리고 위에서 언급했던 each test 별로 롤백이면 저것만 쓰지 않을까 했는데 안됐고... 그 다음에 ``@Sql``을 일단 해보자라고 생각했습니다.  

클래스 위에 붙이자니 메소드 테스트 별로 테이블을 초기화 시켜야하니 의미가 없었습니다. 그래서 ``@BeforeEach``가 붙어있는 ``setUp`` 위에 붙이면 되지 않을까 싶었지만 에러가 떴습니다. 외래키 관련 에러더라구요.. 그래서 메소드 위에다가 하나씩 다 붙이니깐 통과 됐습니다!! 그런데 너무 더러운 느낌이고 각 테스트 별로 추가로 ``insert``하는 쿼리들이 추가가 되어있어서 테스트별 sql 파일을 만드는 것도 이상하다고 생각해서 일단 ``SectionServiceTest`` 에만 추가를 해놓은 상태입니다!!  

sql파일을 쓰지말고 이 ``setUp``만을 가지고 있는 파일을 만들고 해당 클래스를 상속받아 사용하는 식은 어떨까도 생각해봤습니다(현재의  ``AcceptanceTest.java`` 처럼요).  

<br/>

나머지 피드백들도 다 반영했습니다! ``lineId``를 키로 하는 ``Map``으로 만들어서 잘 처리했습니다! 좋은 아이디어였어요!

2021-05-21 11:41 UTC, choihz approved these changes
안녕하세요, 파즈!

피드백을 잘 반영해 주셨네요~ 지하철 노선도 미션은 여기서 마무리하도록 할게요. 그동안 정말 고생 많으셨고, 즐거운 배움의 시간이었길 바랍니다. 다음에 또 만나요~ 👋

2021-05-21 11:41 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionDaoTest.java
> +@JdbcTest
> 인 메모리 디비를 사용하는 것이라면 어차피 테스트 종료 시에 날아가버리는데 롤백이 의미가 있는건가요 ??  
만약, 인 메모리 디비가 아닌 제가 따로 mysql을 dataSource에 등록해놓고 해당 dataSource로 돌아가게끔 했을 그런 경우에만 의미가 있는거라고 생각해도 되는건가요 ??  
>
> 그리고 each test 라길레 메소드 단위로 롤백될 줄 알고 truncate 구문들이 필요없겠구나 했는데 그건 아니더라구요 이 부분은 너무 아쉬웠습니다... 

당연히 의미가 있죠! 왜냐하면 각 메서드마다 롤백되는 게 맞기 때문이에요! 실제로 테스트 로그를 보셔도 메서드 개수만큼 아래 로그가 있을 거예요.

```
2021-05-21 20:13:17.387  INFO 32416 --- [    Test worker] o.s.t.c.transaction.TransactionContext   : Rolled back transaction for test: [DefaultTestContext@2f01a215 testClass = SectionDaoTest...
```

더 직관적으로 눈으로 보고 싶으시다면, 가령 이 테스트 클래스에서의 경우 `setUp()` 메서드 안에서 TRUNCATE 문을 주석 처리하고 각 테스트 메서드의 맨 앞에서 `stationDao.findAll()`을 실행해 역의 개수를 출력해 보세요. 테이블을 따로 초기화하지 않아도, 모든 테스트 메서드에서 역의 개수는 5개로 나올 거예요. 역의 이름에 유니크 인덱스가 걸려 있는데도 오류 없이 잘 저장되는 건 각 테스트 메서드마다 롤백되기 때문이죠.

이렇게 편리한 기능을 제공해 주고 있는데도 왜 `setUp()` 메서드에 테이블 초기화를 위한 긴 코드가 필요한 걸까요? 이유는 전체 테스트를 돌렸을 때의 로그를 보면 짐작할 수 있는데요, 롤백이 되어도 PK는 초기화되지 않고 있기 때문인 것으로 보여요.

```
size of stations : 5
Station{id=21, name='가양역'}
Station{id=22, name='증미역'}
Station{id=23, name='등촌역'}
Station{id=24, name='염창역'}
Station{id=25, name='신목동역'}
```

위의 출력 내용은 제가 파즈의 코드에 출력 코드를 삽입하여 긁어온 것으로, 이 테스트 클래스에서 다섯 번째로 실행된 메서드에서 출력된 내용이에요. 롤백 덕분에 역 이름 충돌 없이 데이터는 잘 들어갔지만, PK는 초기화되지 않은 것을 확인할 수 있죠?

지금 파즈의 테스트 코드를 보면 엔티티의 ID를 직접 하드코딩하는 모습을 많이 볼 수 있는데, 이렇게 테스트가 ID에 의존하도록 작성되어 있으니 ID까지 초기화하지 않으면 테스트 여러 개를 한번에 돌렸을 때 실패하게 됩니다. 즉, 테스트가 직접 작성한 ID에 의존하지 않게 만들면 굳이 테이블 초기화 코드를 직접 작성하지 않아도 될 거예요.

2021-05-21 11:41 UTC, choihz commented on src/test/java/wooteco/subway/section/SectionServiceTest.java
> +    @Sql({"classpath:sectionServiceTestSet.sql"})
> 처음에는 모든 테스트 메소드에 ``@Rollback``을 붙이고 alter, truncate 와 같은 DDL문을 생략하고 DML만 ``BeforeAll``에 하면 되지 않을까? 라고 생각했는데 빈 주입이 안되는지 NPE가 뜨더라구요!! 그리고 위에서 언급했던 each test 별로 롤백이면 저것만 쓰지 않을까 했는데 안됐고... 그 다음에 ``@Sql``을 일단 해보자라고 생각했습니다.  
>
> 클래스 위에 붙이자니 메소드 테스트 별로 테이블을 초기화 시켜야하니 의미가 없었습니다. 그래서 ``@BeforeEach``가 붙어있는 ``setUp`` 위에 붙이면 되지 않을까 싶었지만 에러가 떴습니다. 외래키 관련 에러더라구요.. 그래서 메소드 위에다가 하나씩 다 붙이니깐 통과 됐습니다!! 그런데 너무 더러운 느낌이고 각 테스트 별로 추가로 ``insert``하는 쿼리들이 추가가 되어있어서 테스트별 sql 파일을 만드는 것도 이상하다고 생각해서 일단 ``SectionServiceTest`` 에만 추가를 해놓은 상태입니다!!  

위에 남겨드린 코멘트를 참고하시면 문제를 스스로 해결하실 수 있지 않을까 해요 😉

2021-05-21 11:41 UTC, merged

2021-05-22 05:24 UTC, Be-poz commented on src/main/resources/sectionServiceTestSet.sql
> +SET foreign_key_checks=0;
그렇겠네요! 수정할게요!

2021-05-22 05:26 UTC, Be-poz commented on src/test/java/wooteco/subway/line/LineDaoTest.java
> +@Import({LineDao.class, SectionDao.class, StationDao.class})
맞습니다...🙄

2021-05-22 05:26 UTC, Be-poz commented on src/test/java/wooteco/subway/line/LineDaoTest.java
>      }
assertj 공부해볼게요!

2021-05-22 05:30 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionDaoTest.java
> +@JdbcTest
너무 좋은 피드백인 것 같아요! 저도 이번에 리팩토링을 수행하면서 id 하드코딩말고 그냥 name으로 따로 station 찾던지해서 했으면 이렇게 고생안했겠다 싶더라구요! 앞으로 테스트를 짤 때에 이렇게 짜면 안되겠다는 생각이 팍 머리에 꽂혔습니다!  
따로 프로젝트 생성해서 ``@JdbcTest`` 메서드 별 롤백이 이루어지는지 다시 한 번 확인해보겠습니다!

2021-05-22 05:30 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionDaoTest.java
> +@JdbcTest
이 피드백은 따로 질문과 답변으로 저장해서 보관해둬야 겠어요 ... 감사합니다!

2021-05-22 05:46 UTC, Be-poz commented on src/test/java/wooteco/subway/section/SectionDaoTest.java
> +@JdbcTest
새로파서 해보니깐 메소드 별로 초기화가 되고있어요!! 다른 부분에서 문제가 생겼던거를 초기화가 안됐었다고 착각했나봐요.. 좋은 답변 다시 한 번 감사드립니다