[Spring 지하철 노선도 관리 - 3단계] 피케이(박유진) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #152
Opened 2021-05-12 00:16 UTC by pkeugine

안녕하세요 데이브!
피케이입니다 🙌

이번 단계에서는 도메인 로직을 짜면서 생각을 할 시간을 오래 가졌네요!
그 시간동안 궁금했던 점과 함께 리뷰요청 드립니다!

### 서비스 안의 서비스 또는 레포지토리
이번 미션에서 가장 고민이 많았던 부분이 바로 "서비스 안에 다른 도메인 관련 서비스 / 레포지토리가 있어도 괜찮은가"였습니다. 

노선에 대한 정보를 알기 위해서는 구간 정보, 그리고 역 정보를 알아야되니까요. 그래서 Line 서비스에서 구간 정보를 알아낼 때는 Section 서비스에 해당 일을 위임하고, Section 서비스에서는 역 정보가 필요로 할 때 Station 서비스에 관련 일을 위임하도록 만들었어요. 해당 구조에 대한 리뷰 부탁드립니다!

### 테스트 기본 세팅
`테스트 코드를 재활용할 수는 없을까?` 라는 생각에 TestUtils 클래스를 만들어봤습니다. 그런데 재활용은 좋지만 가독성이 떨어진다는 생각이 들었어요. `아예 DB에 정보를 저장해 놓고 시작하는게 더 좋지 않을까?` 하는 생각도 들었네요. 지금처럼 재활용하는 것도 좋지만, 역을 저장하는 api에 오류가 생기면 노선을 저장하는 테스트가 망가질테니까요. 리팩토링할 때 수정해볼까 하는데, 이 부분에 대한 데이브의 생각이 궁금합니다.

이번 단계에도 잘 부탁드립니다!

2021-05-13 15:18 UTC, dave915 requested changes
피케이 안녕하세요! 
비즈니스 로직을 최대한 도메인으로 넣으려고 한 부분이 인상적이네요 👍 
몇가지 코멘트 남겼습니다. 확인 부탁드릴게요! 
궁금한점 있으면 언제든지 편하게 질문 주세요 :)

2021-05-13 15:18 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +    private List<Long> createOrderedStationIdList(final Long beginningUpStation, final Map<Long, Long> stationIdMap) {
괜찮은 방법이라고 생각합니다 👍

2021-05-13 15:19 UTC, dave915 commented
>서비스 안의 서비스 또는 레포지토리

코멘트 남겼습니다! (https://github.com/woowacourse/atdd-subway-map/pull/152#discussion_r631863338)

>테스트 기본 세팅

given에 해당하는 부분을 `@Sql`을 이용해서 셋팅 하도록 하면 좋을 것 같네요 :)

2021-05-16 01:55 UTC, pkeugine commented on src/main/java/wooteco/subway/section/service/SectionService.java
> +        }
그러네요! 처음에는 "stationId를 포함하는 section을 하나씩 지우면 DB에 괜히 여러번 접근하는게 아닌가" 했었는데, repository에 deleteByStationId를 추가해서 한 번에 다 지워버리면 된다는 걸 깨달았습니다 😂 리팩토링하니까 훨씬 가독성도 좋아졌네요!!

2021-05-17 13:36 UTC, pkeugine commented
안녕하세요 데이브! 🙌

리뷰와 대화를 토대로 리팩토링 해봤어요.
아직 `@Sql` 을 사용하지 않았지만,
지금까지의 상황에 대해 리뷰를 받고 싶어서 리뷰 요청합니다!

현재 제 코드의 변경사항이자 제가 데이브의 리뷰를 받고 싶은 부분입니다:

### Bean Validation 사용
`@Valid` 어노테이션을 이용하여 클라이언트로부터 받는 정보를 검증해요.
이걸 사용하니 역/노선의 이름에 대한 제한을 설정하거나, 역간 거리를 양수로 받을 수 있다는 점이 정말 좋았습니다.
그리고 검증에 실패하면 `MethodArgumentNotValidException`을 controller advice에서 잡도록 했어요.

### Sections 에서 구간을 추가하는 부분 리팩토링
`Sections`를 만들며 가장 신경 쓴 부분은 '가독성이 좋은가' 였어요. 아무래도 지하철 서비스의 가장 핵심적인 로직이 들어가는 곳이다 보니, 이 부분의 가독성이 좋아야 '유지 보수’하기 좋다고 생각했거든요. 그래서 이 클래스의 메서드 이름, 메서드의 위치, 줄 바꿈, 그리고 전체적인 로직의 흐름이 잘 읽히도록 리팩토링 해봤습니다 (하면서 버그도 찾았답니다...ㅎㅎ) 이 부분을 데이브가 봤을 때 드는 생각이 궁금합니다!

### 구간 추가, 그리고 구간 제거에 관련하여
바로 위에서 말한 것과 비슷한데, 특별히 궁금한 점이 있어서 나눴어요. 제 `Sections` 클래스에서 구간을 추가하는 메서드인 `change()`는 `Optional<Section>` 을 반환하고, 구간을 제거하는 메서드인 `removeStation()`은 `List<Section>`을 반환하고 있습니다. 각각 변화가 생긴 구간, 그리고 지워야 할 구간들을 반환하는거죠. 제가 만들었으니 이런 구조가 저는 잘 보이지만, 막상 다른 사람이 보면 한 번에 이해 못 할수도 있겠다는 생각이 들더라구요! 데이브가 봤을 때는 어떤지 궁금합니다.

### exception
기존에는 `StationException`, `LineException`, 그리고 `SectionException`으로 도메인별로 커스텀 예외를 만들었는데요, 이번에는 말해주신 것처럼 제가 생각했을 때 커스텀 예외가 필요한 상황별 예외처리를 했습니다. BusinessException을 만들고 이를 상속받는 `RequestException`과 `DatabaseException`을 만들었는데, 막상 리팩토링을 하다보니 `RequestException`만 사용해도 충분하겠다는 생각이 들었어요. DB에서 Line이나 Station을 찾지 못했을 때 `DatabaseException`을 던질 예정이었는데, `HttpStatus` 400 말고 어떤 다른 코드를 건내줄지 생각이 잘 안났거든요... 물론 데이브의 말만 듣고 제 방식을 바꾸는 것은 아니지만, 지금 제 예외처리 방식이 어떤지 리뷰해 주셨으면 좋겠습니다! (다음 미션에서는 다른 방식으로 에러를 처리해보고 있어요!)

### 일부 dto 패키지 변경
controller와 service간의 데이터 전송에 쓰이는 dto는 service 패키지 아래 dto 패키지를 따로 만들어서 넣어줬어요. 기존에는 controller 패키지에 Response, Request dto 들과 함께 있었는데, 서비스와 같이 있는게 맞다고 생각되었거든요.

### DTO의 이름은 어떻게 지어야할까?
이번 미션의 1,2 단계에서 제가 데이브에게 "서비스가 컨트롤러에 종속되는 것이 싫어서" 그 사이에 정보를 전달하는 dto를 만들었다고 했죠. 그런데 dto라는 표현이 클래스 이름에 추가되는게 이질감이 느껴졌어요. 그래서 찾아보니 이건 사람들마다 의견이 다 다른, 정답이 없는 주제라는 것을 알 수 있었습니다. 데이브는 dto를 만들 때 이름을 어떻게 지으시나요?

만약 제가 적은 글이 잘 이해가 안가시면 **꼭** 알려주시면 감사하겠습니다!
리뷰 잘 부탁드려요!!! :)

2021-05-19 14:33 UTC, dave915 commented
>일부 dto 패키지 변경
controller와 service간의 데이터 전송에 쓰이는 dto는 service 패키지 아래 dto 패키지를 따로 만들어서 넣어줬어요. 기존에는 controller 패키지에 Response, Request dto 들과 함께 있었는데, 서비스와 같이 있는게 맞다고 생각되었거든요.

Controller에서 사용되어 있는 dto, Service에서 사용되는 dto 패키지 나눈 부분은 괜찮다고 생각해요 :) 

>DTO의 이름은 어떻게 지어야할까?
이번 미션의 1,2 단계에서 제가 데이브에게 "서비스가 컨트롤러에 종속되는 것이 싫어서" 그 사이에 정보를 전달하는 dto를 만들었다고 했죠. 그런데 dto라는 표현이 클래스 이름에 추가되는게 이질감이 느껴졌어요. 그래서 찾아보니 이건 사람들마다 의견이 다 다른, 정답이 없는 주제라는 것을 알 수 있었습니다. 데이브는 dto를 만들 때 이름을 어떻게 지으시나요?

저도 이름 뒤에 dto라고 표현하는것이 이질감이 들어서 빼보려고 하고 있어요. 뺐을때 확실히 이질감은 덜 들지만.. 도메인과 dto의 이름이 겹치는 경우 고민이 많아지네요 😭

2021-05-19 14:37 UTC, dave915 requested changes
피케이 안녕하세요! 
질문 주신 부분에 대해 답변 남겼어요 :) 
확인 후 추가로 궁금한 부분이 있다면 질문 주세요!

2021-05-19 14:37 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        final Long beginningUpStation = findBeginningUpStation(stationIdMap);
개인적으로는 이 부분은 메소드에서 사용할 변수들을 선언 하는 부분이라고 생각해서 공백으로 구분 안하면 좋을 것 같아요 :) 
```suggestion
        final Map<Long, Long> stationIdMap = createIdMap(sections);
        final Long beginningUpStation = findBeginningUpStation(stationIdMap);
```

2021-05-19 14:37 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +public class Sections {
말씀 주신대로 비즈니스 로직이 쉽게 읽히는 것 같네요 👍 

`change` 와 `removeStation` 도 저는 파악이 잘 된다고 생각해요 ㅎㅎ

2021-05-19 14:37 UTC, dave915 commented on src/main/java/wooteco/subway/GlobalAdvice.java
> +    @ExceptionHandler({RequestException.class, DatabaseException.class})
`DatabaseException` 같은 경우 로직 상에서 무언가 처리해주는게 없다면, 말씀 주신대로 `DatabaseException.class` 는 필요 없을 것 같아요. 
`@ExceptionHandler(RuntimeException.class)` 에서 충분히 커버 해 줄 수 있을 것 같아요!

2021-05-19 14:37 UTC, dave915 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +@Sql("classpath:stationInit.sql")
👍

2021-05-19 14:49 UTC, dave915 approved these changes
미션 진행 하느라 고생 많으셨습니다! 
이번 미션은 이만 머지할게요 :)

2021-05-19 14:49 UTC, merged

2021-05-20 16:28 UTC, pkeugine commented
# 학습로그

## @Valid
* @RequestBody를 이용하여 클라이언트가 요청에 포함한 데이터를 검증할 때 사용함.
* 이번 미션에서 사용 예시:
```java
public class LineRequest {

    @Pattern(regexp = "^[가-힣a-zA-Z0-9]*선$", message = "지하철 노선 이름은 'XX선' 으로 끝나야합니다.")
    @Size(min=3, max=12, message = "지하철 노선 이름은 최소 3글자, 최대 12글자로 이루어져야합니다.")
    private String name;

    @NotBlank
    private String color;

    @Positive
    private Long upStationId;

    @Positive
    private Long downStationId;

    @Positive
    private int distance;

    // ...
}
```
* 데이터가 잘못 들어왔을 경우 MethodArgumentNotValidException을 잡아서 에러 핸들링을 하거나 BindingResult를 이용하여 controller에서 처리를 할 수 있다.
* Pattern, String의 길이, 정수의 최소/최대값 등을 검증할 수 있다.
* NotNull - null이 아닌 값인지 검증. 다양한 데이터타입에서 활용가능.
* NotEmpty - null이 아니고, 비어있는 값이 아닌지 검증 (ex: ""). Collection, Map, Array 와 같은 자료구조 등에서 이 어노테이션을 활용할 수 있다.
* NotBlank - String이 null이 아니고, trim 했을 경우 역시 비어있는 문자열이 아닌지 검증.

## 태그
* Validation
---

## 퍼사드 패턴
* 프로그램의 여러 부분을 아우르는 간략화된 통합 인터페이스.
* 가독성이 증가한다.
* 바깥쪽의 코드가 안쪽 코드에 덜 의존하게 된다. 즉, 개발에서의 유연성이 향상된다.
* 서비스 안의 서비스 현상을 해결하기 위해 퍼사드 패턴을 이용할 수 있다. 그 경우 여러 서비스를 감싸는 하나의 클래스를 만들어서 컨트롤러에 둔다.
* 나는 해당 미션에서 도입하지 않았다. 아직은 서비스 안에 서비스가 존재해도 괜찮다고 생각하기 때문.

## 태그
* facade pattern

---

## 순환 참조
* A 클래스가 생성되기 위해서는 B 클래스가 필요한데, B 클래스가 생성되기 위해서는 A 클래스가 필요할 때를 순환 참조라 한다.
* 꼭 A->B->A 만 해당하는 것은 아니다. A->B->C->D->A 구조 역시 순환 참조이기 때문에 더욱 조심해야 하는 것.
* service 안에 다른 service 넣을 때 주의를 기울이지 않으면 프로젝트 규모가 커질수록 발생하기 쉬운 현상.
* 스프링의 의존성 주입방법 중 생성자 주입을 할 때 더욱 조심해야 한다.
* 이러한 순환 구조 자체를 지양야하기 때문에, 오히려 생성자 주입이 권장된다. Setter로 의존성을 주입하는 것은 우회적으로 순환 구조를 피하는 것이기 때문.

## 태그
* 순환 참조

---

## @Sql
* 테스트 하기 전에 실행되어야 할 sql 스크립트를 지정할 수 있는 어노테이션
* 클래스 레벨, 메서드 레벨 모두 사용 가능
```java
@Test
@Sql({"/test-schema.sql", "/test-station-data.sql"})
public void stationTest() {
    // station 관련 초기화 따로 진행해주지 않아도 됨.
}
```

## 태그
* sql, test

2021-06-18 04:30 UTC, kang-hyungu commented
어노테이션은 \`\`으로 감싸주세요
\@를 사용하면 해당 아이디를 사용하는 사람에게 알림이 갑니다.
ex) `@Pattern`