[Spring 지하철 노선도 관리 - 3단계] 우기(박병욱) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #154
Opened 2021-05-12 06:44 UTC by jujubebat

2021-05-13 16:05 UTC, dave915 requested changes
우기 안녕하세요! 
구현 잘 해주셨네요! 도메인 객체에 최대한 로직 넣으려는 점이 좋았습니다 👍 
몇가지 피드백 남겼습니다. 확인 부탁드릴게요! 
궁금한점 있으면 언제든지 편하게 질문 주세요 :)

2021-05-13 16:05 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        return stationIds;
코드 전체적으로 이런 여러일을 하는 메소드들에 대해 메소드 분리를 진행해보면 좋을 것 같아요!

2021-05-16 07:13 UTC, jujubebat commented on src/main/java/wooteco/subway/section/domain/SectionAdder.java
> +            stationIds.get(stationIds.size() - 1).equals(section.getUpStationId());
읽기 쉬운 코드가 되도록 해당 부분을 메서드로 분리하고 적절한 네이밍을 갖도록 리팩토링했습니다 !

2021-05-16 07:13 UTC, jujubebat commented on src/main/java/wooteco/subway/section/domain/SectionAdder.java
> +                || it.getDownStationId().equals(section.getDownStationId()))
객체에 메세지를 던져서 로직을 수행하도록 수정했습니다 !!

2021-05-16 07:14 UTC, jujubebat commented on src/main/java/wooteco/subway/line/service/LineService.java
> +        sectionRepository.delete(sectionAdder.originSection(section));
이렇게 할 수 있다니.. 감탄했습니다!! 감사합니다 👍 👍

2021-05-16 07:15 UTC, jujubebat commented on src/main/java/wooteco/subway/line/controller/LineController.java
> +        sectionService.createSection(section(newLine.getId(), lineRequest));
컨트롤러에 비즈니스 로직이 포함되어 있어서 발생하는 문제라고 생각했고,
해당 로직을 서비스로 내려서 동작하게 했습니다 !!

2021-05-16 07:16 UTC, jujubebat commented on src/main/java/wooteco/subway/line/controller/LineAdvice.java
>  public class LineAdvice {
반영했습니다!! 질문이 있어서 댓글 남겼습니다 🙏[https://github.com/woowacourse/atdd-subway-map/pull/106#discussion_r632982903](https://github.com/woowacourse/atdd-subway-map/pull/106#discussion_r632982903)

2021-05-16 07:17 UTC, jujubebat commented on src/main/java/wooteco/subway/line/service/LineService.java
>      @Transactional
반영했습니다 ㅠㅠ 
이것도 질문이 있어서 댓글 남겼습니다 😭[https://github.com/woowacourse/atdd-subway-map/pull/106#discussion_r633053204](https://github.com/woowacourse/atdd-subway-map/pull/106#discussion_r633053204)

2021-05-16 07:21 UTC, jujubebat commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        return stationIds;
최대한 메서드 분리를 진행해봤는데, 더 짚어주시면 개선해보겠습니다!!

2021-05-16 07:45 UTC, jujubebat commented
안녕하세요 데이브 이번 리팩토링 정말 쉽지 않았던 것 같습니다. 😢
많은 고민을 하면서 진행했어요. 궁금한 점 정리해서 질문드리겠습니다!!!

# 질문 1
`LinService`에서 라인 조회, 구간 추가, 삭제에 대한 비즈니스 로직을 처리할 때, `Station`, `Section`의 서비스, 레포지토리 레이어가 필요했습니다. 

그래서 처음에는 `LineService`에 `SectionRepository`, `StationRepository`을 인스턴스 변수로 두고 비즈니스 로직을 구현했습니다. 하지만 여기에 문제가 있었습니다. 

저는 비즈니스 로직 예외 서비스에서 판단하고, 서비스에서 던지도록 구현했습니다. 
그리고 레포지토리는 DB에서 데이터를 가져와서 객체를 넘겨주는 것만 하도록 했습니다.

`LineService`에서 다른 도메인의 레포지토리를 쓰려고 하니, 비즈니스 로직 예외 처리가 안 된다는 문제가 있었고, 비즈니스 예외 처리가 구현된 서비스를 두고 사용하는 방법으로 수정했습니다. 

저는 처음에 컨트롤러 - 서비스간 도메인을 주고 받게 했습니다. 그러다 보니 컨트롤러에서 도메인을 만드는 작업이 수행되었고 컨트롤러가 비대해지고, 하나의 비즈니스 로직에 대해 트랜잭션 보장이 되지 않는 상황이 발생했습니다. [https://github.com/woowacourse/atdd-subway-map/pull/154#discussion_r631915624](https://github.com/woowacourse/atdd-subway-map/pull/154#discussion_r631915624)

그래서 dto를 서비스에 넘겨줘서 도메인으로 만드는 식으로 리팩토링을 진행했습니다. 
하지만 여기서 고민이 생겼습니다. 저는 서비스가 서비스를 호출하는 구조를 가지고 있는데, 
위와 같은 리팩토링을 진행함으로써 서비스 호출시 dto를 만들어야 했습니다. 

컨트롤러 - 서비스 레이어간 데이터 전달 목적으로 사용되는 dto를 서비스 - 서비스간에도 사용한다는 점이 이상하게 느껴졌습니다. 그리고 dto 를 서비스로 전달하는 리팩토링을 진행하자 수많은 서비스 레이어 테스트 코드를 수정해야하는 상황이 발생했습니다. 

서비스가 dto에 의존적이게 됨으로써 dto 수정시 서비스 레이어의 변경이 필요하게 되었습니다. 저는 이런 상황을 방지해서 컨트롤러에서 서비스로 도메인을 넘겨주도록 설계를 했었습니다. 

하지만 계속 이야기했듯이 두 방법 모두 문제가 있었습니다.
- 컨트롤러가 서비스에게 dto를 넘길 때  -> 서비스가 dto에 의존적이게 됨
- 컨트롤러가 서비스에게 도메인 객체를 넘길 때 -> 컨트롤러가 비대해질 수 있음, 도메인이 컨트롤러에 노출됨, 컨트롤러에 비즈니스 로직이 생길 수 있음

2021-05-17 09:25 UTC, jujubebat commented on src/main/java/wooteco/subway/line/service/LineService.java
> +        sectionRepository.save(sectionRemover.createdSection(lineId, stationId));
좋은 아이디어 감사합니다. 수정했습니다 !!! [https://github.com/woowacourse/atdd-subway-map/pull/154/commits/4d2f9b1f63922c621dbcb9821e257005f8fe5df6](https://github.com/woowacourse/atdd-subway-map/pull/154/commits/4d2f9b1f63922c621dbcb9821e257005f8fe5df6)

2021-05-17 14:05 UTC, dave915 commented on src/main/java/wooteco/subway/line/controller/LineAdvice.java
>  public class LineAdvice {
>각 도메인 별로 Adivce를 분리하면, 각 도메인에 대한 예외를 관리할때 유지보수가 좋아질 것이라고 해서 분리했습니다.
exception도 도메인 별로 패키지를 나누어 관리하려고 했는데, 부모 예외를 상속하는 예외들이 떨어져 있는게 어색하다고 생각해서
한 패키지에 관리했습니다.
하나의 Advice가 모든 예외를 핸들링하게 해도 괜찮은가요? 예외가 많아질 경우 Advice가 커질 것 같은데 문제가 없는지 궁금합니다!

이미 Exception이 도메인별로 패키자 나누어져 있지 않기 때문에 한곳에서 처리해도 될 것 같아요! 
음.. Advice가 커질 경우가 걱정된다면 모든 Exception마다 Handler를 만드는 것이 아니라 상위 Exception 마다 Handler를 만들어 보세요 :) 
예를 들어 `NotExistLineException`, `NotExistStationException` 처럼 무언가 존재하지 않는 것에 대한 오류 처리 시 
`NotExistLineException`, `NotExistStationException` 각각 Handler를 만들지 말고 상위 Exception인 `NotExistItemException` 를 처리하는 Handler 하나만 만들어도 됩니다 ㅎㅎ

2021-05-17 14:07 UTC, dave915 commented on src/main/java/wooteco/subway/line/service/LineService.java
>      @Transactional
>반영 했습니다!!
DB에서 값을 조회하는 메서드에는 readOnly 옵션을 따로 붙여줬습니다.
어노테이션 순서에 대해서 궁금증이 생겼는데, 중요한 순으로 아래서 위로 배치하나요?
예를들어 LineService에 어노테이션들을 아래와 같이 붙이면 될까요?

이건.. 팀마다 다를 것 같아요. 만약 팀에서 정한 규칙이 없다면, 자유롭게 또는 우기의 규칙대로 하시면 될 것 같아요 :) 
저는 글자수가 긴걸 아래쪽으로 하고 있어요 ㅎㅎ

2021-05-19 09:53 UTC, dave915 commented
>고민 1

음.. 저는 우선 컨트롤러에서 Dto가 갖고 있는 정보 만으로 도메인 객체를 만들고 서비스에 가서 해당 정보들로 비즈니스에 필요한 새로운 도메인을 만드는 것이 좋지 않을까 생각하고 있어요. 기존에 컨트롤러에서 도메인을 만들어줄때 로직이 비대해졌다고 하셨는데, Dto가 가지지 않은 정보들을 얻기위해 여러 로직들을 추가 했는지 고민해볼 필요가 있을 것 같아요. 

우선은 dto 객체의 메서드 내에서 toDomain 같은 메소드를 도메인을 생성해서 서비스에서 해당 도메인을 이용해 비즈니스 로직을 태울 수 있는 새로운 도메인을 만들도록 해보세요.
필요하다면 DM으로 의견 나누면서 수정해가도 좋을 것 같아요! 

>고민 2

Sections를 꼭 상속해야하는 이유가 있을까요? 컴포지션 관계로 갖고가면 안되는지 한번 고민 해보세요 :) 
아니면.. 다른 크루 보니까 생성, 삭제에 전략 패턴을 적용했더라구요. 이 부분을 참고해도 좋지 않을까요?

>고민 3

저는 가능 하다면 한번에 조회 해오는 방법을 선호 하긴 합니다 ㅎㅎ 
만약 지금 같은 방법이 불편하고 따로 조회 하자니 setter가 불편하다면 Station을 받아 새로운 Section을 생성해서 리턴 하도록 하면 어떨까요?

2021-05-19 10:18 UTC, dave915 requested changes
우기 안녕하세요! 
코멘트 남겨주신 부분에 대한 답변과 간단한 피드백 몇개 남겼어요! 
확인 부탁드릴게요.
진행하면서 궁금한점 있으면 언제든 질문 주세요 :)

2021-05-19 10:18 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +    }
매번 for문을 도는 것 보다 upStationId를 키로 갖고 있는 map을 만들면 좋을 것 같아요 :)

2021-05-19 10:18 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        List<Long> upStationIds = stationIds(sections, true);
메소드에서 boolean 값으로 구분하기 보단 stream을 이용하거나 각각 메소드 분리 하는건 어떠신가요? 

```suggestion
        List<Long> upStationIds = sections.stream()
                .map(Section::getUpStationId)
                .collect(Collectors.toList());
```

2021-05-19 10:18 UTC, dave915 commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        정렬된_역_목록이_반환됨(lineResponse, Arrays.asList(A역, B역, C역, D역, E역, F역));
인수테스트가 다음 미션인 `스프링 - 경로 조회 / 로그인` 의 인수테스트와 비슷한 형태로 작성 되어있는 것 같네요 👍 
우기가 말씀하신 부분이 이 부분 맞을까요?

2021-05-20 02:49 UTC, jujubebat commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        List<Long> upStationIds = stationIds(sections, true);
upTerminalSection 메서드 길이가 길어져서 각각 메소드로 분리해봤습니다!!
메서드의 인자로 주어지는 boolean 값으로 로직 작동을 분기시키는 방법은 가독성 측면에서 안좋다고 생각했습니다!

2021-05-20 03:51 UTC, jujubebat commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +    }
말씀하신대로 map 자료구조를 활용해서, 좀 더 효율적으로 동작하도록 수정했습니다!!

2021-05-23 09:41 UTC, dave915 approved these changes
우기 안녕하세요! 
피드백 반영한 부분 확인 했습니다! 
그동안 미션 진행하느라 고생 많으셨습니다 😁
이번 미션은 이만 머지할게요~!

2021-05-23 09:41 UTC, dave915 commented on src/main/java/wooteco/subway/section/domain/Sections.java
> +        HashMap<Long, Section> sectionByUpStationId = sectionByUpStationId(sections);
👍

2021-05-23 09:41 UTC, merged