[Spring 지하철 노선도 관리 - 3단계] 파피(김태완) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #155
Opened 2021-05-12 16:36 UTC by TaewanKimmmm

안녕하세요, 닉! 3단계 미션 제출합니다 ..!

구간 추가와 삭제가 생각보다 어려워서 기능 구현..에 힘을 썼습니다..!

서비스 레이어에 조건문이 너무 많고 getter를 많이 써서 객체지향적으로 짜지 못했던 것 같습니다 😭😭

새로 나온 미션 바짝하고 테스트 추가와 리팩토링에 힘쓰겠습니다...!

---
Service끼리 의존하게 될 것 같아서 따로 StationService, LineService, SectionService로 나누지 않고 SubwayService 하나에서 모든 로직을 처리하고 있는데, 분리를 하는 게 맞을 것같은데 어떤 식으로 분리해야 좋을까요?

소중한 시간 내어주셔서 감사합니다!!!!!!!!🙏

2021-05-14 02:36 UTC, wbluke requested changes
3단계 기능 구현하느라 고생 많으셨어요 ㅎㅎ
테스트, 비즈니스 로직 관련해서 몇 가지 피드백 남겼으니 확인해 주세요 🙂

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/service/SubwayService.java
> +        return line;
```suggestion
        return lineDao.select(id);
```

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/service/SubwayService.java
> +                .map(stationId -> stationDao.select(stationId))
```suggestion
                .map(stationDao::select)
```

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +public class Sections {
어떻게 보면 핵심 비즈니스 로직을 담고 있는 객체인데 단위 테스트가 없네요 ㅎㅎ
다양한 케이스로 추가해보면 좋겠어요 :)

2021-05-14 02:36 UTC, wbluke commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest extends AcceptanceTest {
요구사항 문서에 있는 다양한 케이스들 검증 부탁드려요 :)

2021-05-14 02:36 UTC, wbluke commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +        assertThat(sectionResponse.header("Location")).isNotBlank();
구간이 잘 생성되었는지 실제 구간 조회를 해서 확인해보면 좋을 것 같아요 :)

2021-05-14 02:36 UTC, wbluke commented on src/test/java/wooteco/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("지하철 구간을 생성한다.")
구간 생성 테스트도 
- 상행역을 포함한 구간 추가
- 하행역을 포함한 구간 추가

이런 식으로 세분화하면 좋을 것 같아요 :)

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +    private final Map<Map<Long, Long>, Integer> sections = new HashMap<>();
이중 map이라 구조가 복잡해 보이는데요, map보다는 상행역/하행역 id를 가지는 DTO를 사용해보거나 하면 좋을 것 같아요.
더 좋은 설계가 있다면 리팩토링해보는 것도 좋고요 :)

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/service/SubwayService.java
> +            sectionDao.insert(lineId, new Section(upwardSection.get().getUpStationId(), downwardSection.get().getDownStationId(), newSectionDistance));
`get()`은 로컬변수로 추출할 수 있겠네요 ㅎㅎ

2021-05-14 02:36 UTC, wbluke commented on src/main/java/wooteco/subway/service/SubwayService.java
> +        if (section.getDownStationId() == line.getUpwardTerminalId()) {
Section에 메시지를 보내서 질의해보면 어떨까요? :)

2021-05-14 07:07 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/dto/SectionRequest.java
> +    private long downStationId;
- 실제 null이 들어오면 NPE가 발생합니다..
- 또한 long으로 두면 기본 값이 0으로 초기화되어있기 때문에 존재하지 않는 값인 것인지, id가 0인 것인지 분간하기 어렵군요

아..오히려 정말 존재하지 않는 값이라는 것을 표현하는 null을 사용하기 위해 Long을 사용하는 군요..!

2021-05-14 07:08 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    private long downStationId;
이해했습니다 감사합니다!!

2021-05-17 11:38 UTC, TaewanKimmmm commented
안녕하세요, 닉! 피드백 반영하였습니다. 객체에 책임을 주려고 노력해봤습니다..!

소중한 시간 내어주셔서 감사합니다🙏🙏

2021-05-18 15:06 UTC, wbluke requested changes
많은 피드백 반영하시느라 고생 많으셨어요! 👏 
반영해주신 부분 중에 조금만 더 수정해보면 좋을 것 같은 부분이 보여서 추가 코멘트 남겼어요 ㅎㅎ
확인 부탁드려요 🙂

2021-05-18 15:06 UTC, wbluke commented on src/main/java/wooteco/subway/domain/repository/SectionRepository.java
> +    private final StationDao stationDao;
음, 저는 Repository가 DAO를 가지는 로직이 어색해보이는데요.
둘다 `@Repository` bean으로 관리, 역할을 감당하는 객체이고, 어떤 도메인의 DB Access를 담당하는 동등한 객체라고 생각해요.
실제로 LineRepository 같은 경우는 DAO에게 by-pass 하는 역할밖에 없는 상태고,
SectionRepository 같은 경우처럼 여러 DAO에서 각각 도메인을 조회하여 가공하는 로직은 Service 레이어에 있어야 마땅합니다 :)

즉, 현재 단계에서는 Repository와 DAO를 동등한 객체로 바라보면 좋을 것 같아요.
한가지만 사용하도록 바꿔볼 수 있을까요? :)

2021-05-18 15:06 UTC, wbluke commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +    }
upward, downward 탐색에 대한 공통 로직을 각각 메서드로 분리해볼 수 있겠네요 :)

2021-05-18 15:06 UTC, wbluke commented on src/main/java/wooteco/subway/dto/LineRequest.java
>      private int distance;
메시지까지 잘 적용해 주셨네요! 💯

2021-05-18 15:06 UTC, wbluke commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +public class SectionsTest {
꼼꼼한 테스트 👍

2021-05-18 17:19 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/domain/repository/SectionRepository.java
> +    private final StationDao stationDao;
아직 레이어 구조에 대해 파악이 부족했던 것 같습니다.

DAO만 사용하도록 수정하였습니다!

2021-05-18 17:24 UTC, TaewanKimmmm commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +    }
반영했습니다!!!!! :)

2021-05-18 17:32 UTC, TaewanKimmmm commented
안녕하세요, 닉! 피드백 반영했습니다. 많은 도움이 됐어요!

레이어 구조에 대해 항상 헷갈렸는데 기준을 많이 잡아주신 것 같아서 감사합니다 :)

궁금한 점이 있습니다!

현재 test 패키지의 모든 테스트를 실행 시키면 StationAcceptanceTest의 4개 케이스가 실패하는데, 따로 돌리면 모두 성공합니다.

AcceptanceTest 클래스를 상속하기 때문에 DirtiesContext가 동작하여 context를 다시 생성하기 때문에 성공해야 된다고 생각했는데 당황스럽네요.. 이유가 뭘까요? :(

소중한 시간 내어주셔서 감사합니다~!🙏🙏🙏🙏🙏

2021-05-20 09:12 UTC, wbluke approved these changes
피드백 반영 감사합니다 ㅎㅎ
질문하신 부분도 코멘트 달았으니 확인해 주시고, 다음 미션도 화이팅입니다! 🙂

2021-05-20 09:13 UTC, merged

2021-05-20 16:34 UTC, TaewanKimmmm commented
# 학습로그

## @Transactional

스프링에서의 트랜잭션 처리를 지원해주는 어노테이션이다.

클래스나 메서드 위에 @Transactional을 추가하면 해당하는 클래스나 메서드에 트랜잭션 기능이 적용된 프록시 객체가 생성된다.

그 후 PlatformTransactionManager를 사용하여 트랜잭션을 시작하고, 정상 동작 여부에 따라 Commit 혹은 Rollback한다.

이 중 readOnly 속성을 사용해 봤는데, 이 속성은 다음과 같은 효과가 있다.

- 트랜잭션을 읽기 전용으로 설정할 수 있다.

- 성능을 최적화하기 위해 사용할 수도 있고 특정 트랜잭션 작업 안에서 쓰기 작업이 일어나는 것을 의도적으로 방지하기 위해 사용할 수도 있다.

조회 (SELECT) 쿼리를 사용하는 메서드의 경우는 읽기 전용으로 지정하고, 테이블에 변경을 일으킬 수 있는 메서드는 따로 속성을 주지 않고자 하였다.

readOnly 속성의 default 값이 false이기 때문이다.

따라서 클래스 레벨에서 @Transactional(readOnly = "true")를, 변경을 일으키는 메서드 레벨에서는 @Transactional을 사용하였다.

# Reference
https://goddaehee.tistory.com/167