[Spring 지하철 노선도 관리 - 3단계] 조이(김주원) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #157
Opened 2021-05-13 13:21 UTC by Joyykim

안녕하세요 미립...!!! 도중에 한번 삐끗하니 계속 늦춰지다 이제야 첫 리뷰요청을 보냅니다..ㅎㅎ🥲

2021-05-14 00:31 UTC, seok-2-o requested changes
전체적인 그림을 그리고 개발을 시작하는 것은 매우 좋은 자세라고 생각합니다. 💯 
지금 당장은 더디게 느껴져도 좋은 방향으로 가고 있다고 생각해요.

다만, 이번 코드에서는 이전에 우리가 지켰어야할 기본적인 것들이 많이 지키지 못하신 것 같아요.
레벨1에서의 의식적인 연습을 다시한번 되돌아보면 좋을 것 같아요.

2021-05-14 00:31 UTC, seok-2-o commented on src/main/java/wooteco/subway/domain/line/SortedStations.java
> +    ArrayDeque<Long> result = new ArrayDeque<>();
접근제어자를 생략하신 이유가 있으신가요.

해당 과정에서 인스턴스 필드는 작게 (4개 이하로) 유지하는것으로 알아요 .
이렇게 많은 필드가 필요할까요?

2021-05-14 00:31 UTC, seok-2-o commented on src/main/java/wooteco/subway/domain/section/SectionDao.java
> +    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
👍 

JdbcTemplate 와 혼용해서 쓸 필요가 있을까요?

2021-05-14 00:31 UTC, seok-2-o commented on src/main/java/wooteco/subway/service/LineService.java
> +        List<StationResponse> sortedStations = new SortedStations(sections, stations).get();
쉽게 이해되는 구조는 아닌데, 어떤 구조인지 설명해주실 수 있나요? 🤔

2021-05-14 00:31 UTC, seok-2-o commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
전체적으로 매직 넘버 사용이 많네요. 오버엔지니어링이라그 느껴질 수 있지만 수업이니만큼 상수로 추출해보는것을 권장드려요.

2021-05-14 00:31 UTC, seok-2-o commented on src/main/java/wooteco/subway/service/SectionService.java
> +        }
규칙 2: else 예약어를 쓰지 않는다.

비지니스 로직이 복잡해질수록 지키기 어려운 규칙이긴하지만, 
오히려 지금 신경써서 연습해보는게 좋을 것 같아요.

2021-05-15 08:40 UTC, Joyykim commented on src/main/java/wooteco/subway/service/SectionService.java
> +        }
넵!😀

2021-05-15 08:40 UTC, Joyykim commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
넵!!

2021-05-15 08:40 UTC, Joyykim commented on src/main/java/wooteco/subway/domain/section/SectionDao.java
> +    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
`NamedParameterJdbcTemplate`만 사용하도록 변경했습니다!

2021-05-15 08:41 UTC, Joyykim commented on src/main/java/wooteco/subway/domain/line/SortedStations.java
> +    ArrayDeque<Long> result = new ArrayDeque<>();
헉 접근제어자를 빼먹었네요...ㅠ 필드 개수도 줄여보겠습니다!

2021-05-15 09:54 UTC, Joyykim commented on src/main/java/wooteco/subway/service/LineService.java
> +        List<StationResponse> sortedStations = new SortedStations(sections, stations).get();
공백 기준으로 3부분으로 분리해서 설명드릴게요!
1. 구간 리스트 조회: 노선 id를 통해 노선에 포함된 구간 리스트 조회
2. 역 리스트 조회: 구간 리스트 -> 구간에 포함된 역 id 리스트 구함, 역 id 리스트로 역 리스트 조회
3. 구간 리스트, 역 리스트를 통해 역 목록을 상행-하행 순으로 정렬
리팩터링해서 좀 더 이해하기 쉽게 만들어보겠습니다🥲

2021-05-16 12:17 UTC, Joyykim commented
안녕하세요 미립😀
저번 리뷰요청에서는 미립 말대로 레벨1에서부터 연습했던 것들을 지키는데 신경을 못썼던것 같아요🥲
과정이 진행될수록 새로운 정보를 습득하기 바빠서 가장 중요한 코드 품질을 놓치게 되는것 같아 반성했어요😭
좋은 피드백 주셔서 감사합니다ㅎㅎ 덕분에 많은 생각을 하게 되었어요!
---


잘 부탁드립니다!!

2021-05-17 00:16 UTC, seok-2-o approved these changes
피드백 반영 잘 해주셨어요 👍 
과제도 많은데 규칙도 지키시느라 고생 많으셨어요.

그래도 지금의 고생이 나중에 좋은 개발자로 성장하는데 조금아나마 도움이 되길 바라봅니다.

저와의 미션은 여기까지네요 :) 그래도 궁금한점이나 어려운 점 있으면 편하게 연락주세요.

감사합니다. 나머지 미션도 멋지게 해내시길 응원할게요.

2021-05-17 00:16 UTC, seok-2-o commented on src/main/java/wooteco/subway/web/dto/LineRequest.java
>      private int distance;
거리가 1보다 커야하는 제약조건이 있어서 큰 문제는 없겠지만 Request 로 받는 숫자타입은 Integer를 사용하는게 바람직해보여요. 어떤 특수한 경우로 distnace 가 누락 되 었을 경우 int 는 0이되어 문제가 발생 할 수도 있어요.

2021-05-17 00:16 UTC, merged

2021-05-17 00:40 UTC, Joyykim commented on src/main/java/wooteco/subway/web/dto/LineRequest.java
>      private int distance;
원시값은 null허용이 안되는군요! 감사합니다!