[Spring 지하철 노선도 관리 - 3단계] 손너잘(손민성) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #159
Opened 2021-05-13 16:51 UTC by bperhaps

empty

2021-05-16 06:45 UTC, dave915 commented
- 다른 도메인 참조에 관해 
	저도 DDD에 관해서 공부하고 있는 입장이라서 제 생각이 틀릴수도 있지만.. 답변 드려 볼게요! 
	[LineServcie에서 StationRepository를 참조한 부분]
	이 부분은 해결하는 방법이 파사드 패턴이나 아니면 지금 처럼 Service에서 다른 도메인 Repository를 참조 하는 방법 		뿐이라고 생각해요 ㅠㅠ 도메인 서비스를 사용한다고 해도 어플리케이션 레이어에서 두 도메인을 조회해서 도메인 서비스에게 	넘겨주는 것이기 때문에 사실상 `Service에서 다른 도메인 Repository를 참조 하는 방법` 과 동일한 것 아닌가 싶네요 ㅎㅎ
	저도 DDD를 공부하면서 지금 손너잘과 같은 고민을 했었는데, 어디까지를 도메인으로 볼 것인가에 관해 고민했어요. 그 중 	어플리케이션 레이어는 도메인과 리파지토리 또는 외부 요청으로 얻은 정보를 엮어주는 Layer라고 결론을 내렸고 다른 도메인 	리파지토리를 갖고와서 사용했습니다. 
	영 찝찝하면 말씀하신 DIP가 이 것을 말한것인지 모르겠지만.. Line 도메인 패키지에도 StationRepository 인터페이스를 
	만들어서 사용하는건 어떨까요? 두 도메인이 각 어플리케이션으로 분리 된다면 이부분 구현을 DB접근이아닌 API요청으로 	변경 하면 될 것 같아요 :) 

	[도메인이 각자 다른 서비스로 분리되었을때 API 요청]
	저는 말씀 주신대로 서로의 동작이 상태변화에 독립 적이기 때문에 괜찮다고 생각해요. 
	추가적으로 API 요청으로 변경 되면서 고려해야 할점은 보상 트랜잭션이라고 보았어요. 두 어플리케이션을 하나의 			트랜잭션으로 묶기 힘들기 때문에 예를들어 Line 에서 작업 처리 후 Station에도 변경작업이 있어야 하는데 Station에서 		오류가 났을 경우 Line에도 알려주어 Line을 작업 전 상태로 되돌리는것을 말해요.
	이런 처리는 보통 큐를 이용한 이벤트 소싱 패턴을 사용한다고 하네요! 
	
	저도 공부하고 있는 입장이라 틀린 내용이 있을 수 있지만 ㅠㅠ 손너잘 고민이 조금이라도 해결되었으면 하네요! 

- jdbcTest에 관해
	살펴보니까 @JdbcTest는 @Repository 빈들을 로드 하는것이 아니라 JdbcTemplate 관련 빈들만 로딩 하더라구요! 
	`@Import(LineDao.class)` 를 사용하면 원하던 대로 `LineDao`에 `@Autowired` 할 수 있을 거에요. 
- Transactional에 관해
	Repository 입장에서 봤을때 이부분이 Transactional 필요할 것 같다고 생각이 들면 해당 메소드에 붙이면 되지 않을까요? 
	
	```
	// LineRepositoryImpl.java

	@Transactional
	public Line save(Line line) {
	```

2021-05-16 07:39 UTC, dave915 requested changes
손너잘 안녕하세요! 고민이 많아 보이는 코드네요 💯 
질문에 관한 답변과 간단한 피드백 몇개 남겼어요. 
궁금한 점있으면 언제든 편하게 질문 주세요 :)

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/presentation/line/LineController.java
> +    public ResponseEntity<LineResponse> createNewLine(@RequestBody LineRequest lineRequest) {
`@Valid` 어노테이션을 이용해서 유효성 체크도 한번 해볼까요?

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/domain/line/section/Sections.java
> +        this.sectionDeleteRules = SectionDeleteRuleFactory.create();
섹션 추가 및 삭제 로직을 추상화 했군요 👍

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/domain/line/section/Section.java
> +        return Objects.equals(lineId, section.lineId) && Objects.equals(upStationId, section.upStationId) && Objects.equals(downStationId, section.downStationId) && Objects.equals(distance, section.d
줄바꿈이 필요할 것 같아요 😭

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/domain/line/section/rule/SectionAddRule/UpStationExists.java
> +                getSectionThatHasSameUpStationByFromSections(sections, section).get();
execute 메소드가 실행됬다면 `isSatisfiedBy` 메소드의 반환값이 true일 경우라고 생각해요. 
Optional값이 없는 경우 잘못된 정보가 들어온 것이기 때문에 orElseThrow로 에러를 던져주면 어떨까요?

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/domain/line/section/rule/SectionDeleteRule/MatchedSection.java
> +                .filter(section -> Objects.equals(section.getUpStationId(), stationId))
객체에게 메세지를 보내주세요 :) 
`Objects.equals` 사용한 곳이 많아 보이는데, 메세지 보내는 방식으로 수정 가능한지 살펴보면 좋을 것 같아요 :) 
```suggestion
                .filter(section ->section.isEqualsUpStationId(stationId))
```

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/application/line/LineService.java
> +                .collect(toList());
이 로직은  Line안에 있어도 되지 않을까요?

2021-05-16 07:39 UTC, dave915 commented on src/main/java/wooteco/subway/application/line/LineService.java
> +        stations.forEach(stationRepository::findById);
forEach로 돌면서 조회만 하는 것일까요?

2021-05-16 07:48 UTC, bperhaps commented on src/main/java/wooteco/subway/domain/line/section/Section.java
> +        return Objects.equals(lineId, section.lineId) && Objects.equals(upStationId, section.upStationId) && Objects.equals(downStationId, section.downStationId) && Objects.equals(distance, section.d
인텔리제이 기능에 기대다보니 이런 불상사가..... 수정하겠습니다 감사합니다ㅜㅜ

2021-05-16 07:49 UTC, bperhaps commented on src/main/java/wooteco/subway/domain/line/section/OrderedStationId.java
> +        long[] stationIndexesByUpStationId = new long[(int) maxStationsId + 1];
오.. 저 부분 보면서 상당히 거슬렸었는데 간단하게 해결이 가능했었네요.... 감사합니다!!!

2021-05-16 07:49 UTC, bperhaps commented on src/main/java/wooteco/subway/presentation/line/LineController.java
> +    public ResponseEntity<LineResponse> createNewLine(@RequestBody LineRequest lineRequest) {
한번 해보고싶었던 기능이었는데!! 진행하겠습니다!

2021-05-16 07:53 UTC, bperhaps commented on src/main/java/wooteco/subway/domain/line/section/rule/SectionAddRule/UpStationExists.java
> +                getSectionThatHasSameUpStationByFromSections(sections, section).get();
isSatisfiedBy에서 true가 나왔다는것은 ifPresent()를 통과한거고, 따라서 바로 get()을 해도 괜찮다고 생각했어요!
그런데 좀 더 견고한 로직을 위해서는 데이브의 의견이 확실히 맞네요ㅠㅜㅠ 수정하겠습니다@!

2021-05-16 07:54 UTC, bperhaps commented on src/main/java/wooteco/subway/domain/line/section/rule/SectionDeleteRule/MatchedSection.java
> +                .filter(section -> Objects.equals(section.getUpStationId(), stationId))
오.... 객체지향의 가장 기본 원칙을 놓쳤네요..... 감사합니다ㅠㅠ!!

2021-05-16 07:57 UTC, bperhaps commented on src/main/java/wooteco/subway/application/line/LineService.java
> +                .collect(toList());
오.... 서비스로직에서 validation이 가능하다는 이야기에 묻혀서 도메인 로직까지 밖으로 빼버렸네요....!!!! 감사합니다 수정하겠습니다!!

2021-05-16 07:57 UTC, bperhaps commented on src/main/java/wooteco/subway/application/line/LineService.java
> +        stations.forEach(stationRepository::findById);
이부분이 상당히 거슬리는 부분이긴 한데... station이 존재하는지 확인하는 로직인데, 없으면 레포에서 emptyException을 던져서 저렇게 짜놓은 것 이었어요.....
흠.... Repositroy에 따로 검증을 위한 메서드를 만드는게 맞는 것 같다는 생각이 확 스쳐 지나가네요!! 수정해 보겠습니다!

2021-05-16 07:57 UTC, bperhaps commented on src/main/java/wooteco/subway/application/line/LineService.java
> +        stations.forEach(stationRepository::findById);
이부분이 상당히 거슬리는 부분이긴 한데... station이 존재하는지 확인하는 로직인데, 없으면 레포에서 emptyException을 던져서 저렇게 짜놓은 것 이었어요.....
흠.... Repositroy에 따로 검증을 위한 메서드를 만드는게 맞는 것 같다는 생각이 확 스쳐 지나가네요!! 수정해 보겠습니다!

2021-05-16 07:58 UTC, bperhaps commented on src/main/java/wooteco/subway/application/line/LineService.java
> +                .collect(toList());
오.... 서비스로직에서 validation이 가능하다는 이야기에 묻혀서 도메인 로직까지 밖으로 빼버렸네요....!!!! 감사합니다 수정하겠습니다!!

2021-05-17 07:36 UTC, bperhaps commented
안녕하세요 데이브!! 손너잘입니다!! 리뷰 정말 감사합니다ㅜㅜ 덕분에 제가 혼자 생각하기 힘들었던 부분들에 대해서 많은 인사이트를 얻었어요!! 특히 보상 트랜젝션에 대해서는 생각 못했는데 역시.... 보는 눈이 다르십니다... 진짜진짜 너무 감사합니다 ㅜㅜㅜㅜ

수정 요청하신 부분은 모두 수정했어요! 이전 리뷰에서 답변을 너무 잘해주셔서 이번에는 크게 질문사항은 없어요!! 다만 아래부분 하나를 잘 모르겠어요.

> Transactional에 관해
> Repository 입장에서 봤을때 이부분이 Transactional 필요할 것 같다고 생각이 들면 해당 메소드에 붙이면 되지 않을까요?

인터넷이던지 여러곳을 보면 Transactional을 Service딴에 붙이는걸 추천하는데, Repository 혹은 Dao 내부에 Transactional을 붙여도 괜찮은 걸까요??? 잘 모르겠어요.....ㅜㅜ

이번 리뷰도 잘 부탁드립니다 데이브 항상 감사합니다!!

2021-05-19 10:24 UTC, dave915 commented
비즈니스 로직 단위에 Transaction을 걸고 싶으면 말씀 주신대로 Service에 붙이면 되고, 지금 손너잘 같은 경우처럼 Repository에서 수행되는 로직의 Transaction 을 관리 하고싶을땐 Repository에 걸면 됩니다 ㅎㅎ 

보통은 지금처럼 직접 구현한 Dao가 아닌 Jpa나 Mybatis같은 걸 써서 Repository에 붙일 일이 없다고 생각이 들어요 :) 
그래서 저 같은 경우엔 아래 처럼 기본으로 readOnly로 걸리도록 해두고 필요한 부분에만 다시 `@Transactional`을 걸고 있어요. 

```
@Service
@Transactional(readOnly = true)
public class LineService {

    public Line findLine(Long id) {
    }

    @Transactional
    public void deleteLine(Long id) {
    }
}
```

2021-05-19 10:34 UTC, dave915 approved these changes
손너잘 안녕하세요! 
질문 주신 부분에관한 답변과 간단한 피드백 남겼어요.
그동안 미션 진행 하느라 고생 많으셨습니다 👏
덕분에 저도 많이 고민하고 공부도 됐던 것 같아요 :) 
혹시 추가적으로 궁금한 점있다면 언제든 DM주세요! 
이번 미션은 이만 머지할게요!

2021-05-19 10:34 UTC, dave915 commented on src/main/java/wooteco/subway/ExceptionAdvisor.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
Exception.class 를 처리하는 핸들러 같은 경우 보통 개발자가 의도 하지 않은 에러가 발생 할 경우 처리가 되고 있어요. 
이때 e.getMessage를 그대로 내보내 줄 경우 내부 패키지 구조나 사용하고 있는 기술들이 외부로 노출 될 수 있어서, e.getMessage는 로그로 남기고 body로는 "서버에서 오류가 발생 했습니다." 와 같은 메세지로 대체해서 내보내줍니다 ㅎㅎ

2021-05-19 10:34 UTC, dave915 commented on src/main/java/wooteco/subway/presentation/line/dto/LineRequest.java
> +    private final Long distance;
custom annotation 까지 👏

2021-05-19 10:34 UTC, merged

2021-05-21 00:57 UTC, bperhaps commented
Chess 

# 학습 로그
## 1 : N 참조시 객체의 참조 방향성

## 태그
- 설계, DDD

## 서로 다른 모듈의 Repository를 service 에서 참조하는 행위에 대한 논의

## 태그
- 스프링, 설계

## API call의 양방향 의존성

## 태그
- 스프링, 설계

## Valid

## 태그
- 스프링, valid, jrs 303, 308, 380

## Transactional의 위치
- Repository에서 수행되는 로직의 Transaction을 관리하기 위함이면 Repository에 붙이는 것도 가능
- JPA를 사용하면 생각하지 않아도 될 문제

## 태그
- 스프링, 트랜젝셔널

## Advice
- 일반적으로 에러처리에  많이 쓰임

## 태그
- 스프링

## Interceptor vs Resolver

## 태그
- 스프링