[Spring 지하철 노선도 관리 - 3단계] 멍토(김유기) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #161
Opened 2021-05-13 19:22 UTC by daum7766

안녕하세요 코니!
기간안에 제출하고 싶었는데 3단계 미션이 난이도가 높았습니다 ㅜㅠ
구간을 추가,삭제하는 내용을 구현하는데 많은 어려움을 겪었습니다.
늦게 제출해서 죄송합니다!

1,2단계에서 달아주신 피드백까지 반영했습니다!

이번 미션을 하면서 생겼던 궁금한 점입니다.
1. 노선에 포함된 역을 정렬을 하기 위해서 sectionService에서 response가 아닌 일급 컬렉션을 가져오는데 괜찮을까요?
2. 일급 컬렉션에서 toResponse라는 메서드를 만들어도 괜찮을까요? (도메인이 DTO를 알고있다?)
3. section이 line패키지 안에 있습니다. section이 line에 의존적이라고 생각하여 line패키지 안에 만들었는데, 밖으로 분리해야 할지 고민입니다.
4. section과 관련된 요청을 lineController에서 받고 있습니다. section관련된 url이 앞에 있어서 lineController에 넣었는데 sectionController로 분리하는 것이 좋을까요?
5. 모든 Line을 가져올때 연관된 역들을 알기 위해서 DB에 많은 접근이 일어나게 됩니다. 고민을 했는데 어떻게 해결해야 할지 감이 오지 않습니다. 힌트를 주실 수 있을까요?
6. Section Station을 사용중이면 Station을 삭제할때 에러가 발생하게 만들었습니다. station이 삭제되면 구간을 자동으로 정리를 시켜줘야 할까요?

감사합니다!

2021-05-15 20:05 UTC, choihz requested changes
안녕하세요, 멍토!

지하철 노선도 3단계도 잘 구현해 주셨네요! 피드백 보시고 궁금한 점 또는 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2021-05-15 20:05 UTC, choihz commented on src/main/java/wooteco/subway/line/LineService.java
> +            }).collect(Collectors.toList());
> 모든 Line을 가져올때 연관된 역들을 알기 위해서 DB에 많은 접근이 일어나게 됩니다. 고민을 했는데 어떻게 해결해야 할지 감이 오지 않습니다. 힌트를 주실 수 있을까요?

반복문에서 DB 접근이 일어나는 것은 지양하는 것이 좋기는 해요. 그래서 `IN` 절 등을 이용해 반복문 바깥에서 한번에 조회하도록 하는 편입니다. 다만 지금 구조에서는 수정하는 게 조금 어려울 것 같아서 고민만 해 보셔도 좋을 것 같네요~!

2021-05-15 20:05 UTC, choihz commented on src/main/java/wooteco/subway/station/StationService.java
> +    }
> Section Station을 사용중이면 Station을 삭제할때 에러가 발생하게 만들었습니다. station이 삭제되면 구간을 자동으로 정리를 시켜줘야 할까요?

연관된 객체가 삭제될 때의 처리는 비즈니스적인 결정인데요, 요구사항에 명시되지 않았으니 멍토의 판단에 맡기도록 할게요.

2021-05-16 07:08 UTC, daum7766 commented on src/main/java/wooteco/subway/SubwayAdvice.java
>          System.out.println(e.getMessage());
넵! 로그로 수정하여 번영하도록 하겠습니다.

2021-05-16 07:10 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
>      public ResponseEntity<LineResponse> createLine(@RequestBody LineRequest lineRequest) {
존재하지 않는 station을 참조하기 때문에 EmptyReusltSetDataAccessException이 일어납니다.
따라서 ControllerAdvice에서 핸들링하여 400에러와 함께 존재하지 않는 아이템입니다. 라는 메시지가 가게됩니다.

그렇지만 코드상으로만 보았을 때는 어떻게 동작하는지 어려움이 있는 것 같습니다.
코드상으로 눈에 보이도록 변경하겠습니다!

2021-05-16 07:10 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Sections.java
> +            throw new IllegalUserInputException();
넵! 좀 더 세분화하여 메시지를 전달하도록 변경하겠습니다.

2021-05-16 07:12 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
> +    }
저도 해당 부분에 대해서 고민을 했었습니다. (이걸 질문에서 빼먹었네요 ㅜㅠ)
section과 같은 경우는 생성을 해도 보낼 url이 없다라고 생각 했습니다.
그렇지만 created를 보면 URI를 포함해야 하는데 이럴 경우에는 어떻게 해야 할지 찾지못하여 위와같이 사용하게 되었습니다.
저런 경우는 어떻게 해야 할지 검색할 만한 키워드를 주실 수 있을까요?

2021-05-16 07:13 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
>      @GetMapping()
매의눈!

2021-05-16 07:13 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
> +    public ResponseEntity<Void> createSection(@PathVariable Long id,
분리하도록 하겠습니다!

2021-05-16 07:13 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationController.java
>      @PostMapping("/stations")
넵! 반영하겠습니다.
감사합니다.

2021-05-16 07:15 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineService.java
>      }
전체 조회시에도 stations를 채워주고는 있는데
프론트엔드 코드를 확인하니 전체조회때는 stations를 사용하지 않고있습니다.

전체조회용 response를 따로 만들어서 stations에 접근하는 부분을 삭제하여 DB에 대한 접근을 줄이는 방법에 대해서는 어떻게 생각하시나요?

2021-05-16 07:17 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationService.java
> +    }
해당 부분에 대해서는 고민해보겠습니다.

2021-05-16 07:17 UTC, daum7766 commented on src/main/java/wooteco/subway/exception/NotInputDataException.java
>  public class NotInputDataException extends RuntimeException {
네이밍이 제일 어려운것 같습니다 ㅜㅠ
코니의 의견대로 InvalidInputDataException이 좋은 네이밍인것 같습니다!

2021-05-16 07:20 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Sections.java
> +    }
넵! 수직거리를 반영하도록 하겠습니다.

2021-05-16 07:20 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Sections.java
> +        }
메서드로 변경하여 분리하도록 하겠습니다.

2021-05-16 07:21 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Sections.java
> +    private int getStationCount(Long stationId, Set<Long> stationIds, int stationCount) {
고민해 보고 변경하도록 하겠습니다!

2021-05-16 07:24 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Section.java
> +    private Long id;
id가 가장 위에 있었는데 fianl을 붙이지 않으니 오토컨벤션을 사용할때 아래로 내려가게 됩니다. ㅜㅠ

id를 fianl로 하지 않은 이유는 Section을 등록할 때 리플렉션을 통해서 바꾸는 로직이 있었기 때문입니다.
그렇지만 불변성이 보장되지 않는 부분에서 서비스의 안정성이 떨어질 수도 있다고 생각이 듭니다.
해당 로직에 대해서 변경하도록 하겠습니다.

2021-05-16 07:24 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationService.java
> +public class StationService {
ㅜㅠ 죄송합니다.
다음에 더 꼼꼼하게 확인하도록 하겠습니다.
매의 눈 코니! 감사합니다.

2021-05-16 07:25 UTC, daum7766 commented on src/main/java/wooteco/subway/line/dto/LineResponse.java
> +    }
생성자는 확장성을 위해서 사용하지 않더라도 만들어 두는 것은 괜찮다는 이야기를 들었습니다.
제가 잘못 알고 있던 부분일까요?

2021-05-16 07:26 UTC, daum7766 commented on src/test/java/wooteco/subway/line/section/SectionDaoTest.java
> +    private final Section defaultSection = new Section(1L, 1L, 4L, 10);
Static이 아니어서 전부 카멜케이스로 변경했던 내용입니다.
이런 경우는 상수처럼 취급해도 될까요?

2021-05-16 07:27 UTC, choihz commented on src/main/java/wooteco/subway/line/LineController.java
> +    public ResponseEntity<Void> createSection(@PathVariable Long id,
엇 이거는 메서드 이름이 잘못되어 남긴 코멘트예요. `@DeleteMapping`!

2021-05-16 07:27 UTC, daum7766 commented on src/test/java/wooteco/subway/line/section/SectionDaoTest.java
> +    private final Section defaultSection = new Section(1L, 1L, 4L, 10);
상수로 변경하여 사용하도록 하겠습니다.

2021-05-16 07:27 UTC, choihz commented on src/main/java/wooteco/subway/line/LineService.java
>      }
네 저는 그렇게 하는 것도 좋다고 생각해요!

2021-05-16 07:28 UTC, daum7766 commented on src/test/java/wooteco/subway/line/section/SectionServiceTest.java
> +            .isEqualTo(Collections.singletonList(new Section(1L, 1L, 4L, 10)));
오오 감사합니다.

2021-05-16 07:28 UTC, choihz commented on src/main/java/wooteco/subway/line/dto/LineResponse.java
> +    }
의견이 다를 수는 있는데, 저는 굳이 그럴 필요 있나 하는 생각이 드네요 ㅎㅎ 필요할 때 만드는 게 어려운 것도 아니고요.

2021-05-16 07:29 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/SectionService.java
> +    }
이번에 Sprig이 처음이어서 모든것이 조심스러운 상황압니다.
다른 부분에서는 전부 Response를 반환하고 있는데 혼자 도메인객체를 반환하여 걱정을 했었습니다.
코니의 이야기를 들으니 상관다는 생각이 듭니다.

2021-05-16 07:30 UTC, daum7766 commented on src/main/java/wooteco/subway/station/Stations.java
> +    }
좋은 방법인 것 같습니다!
위와 같이 반영하도록 하겠습니다.

2021-05-16 07:30 UTC, choihz commented on src/main/java/wooteco/subway/line/LineController.java
> +    }
정답이 없는 문제죠~ 저는 보통 요청에 의해 생성된 리소스에 직접 접근할 수 없는 지금과 같은 경우에는 그냥 200 응답을 사용하고 있어요.

2021-05-16 07:31 UTC, daum7766 commented on src/main/java/wooteco/subway/line/section/Section.java
> +package wooteco.subway.line.section;
저도 아마 분리가 가능하다고 생각했기 때문에 답을 정해놓고 했던 질문 같습니다.
분리하도록 하겠습니다!

2021-05-16 07:31 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineService.java
> +            }).collect(Collectors.toList());
넵 해당 내용에 대해서는 좀 더 공부해보며 고민해보도록 하겠습니다.

2021-05-16 07:32 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationService.java
> +    }
그렇다면 지금의 구조로 가져가겠습니다!

2021-05-16 07:34 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
> +    public ResponseEntity<Void> createSection(@PathVariable Long id,
!?!
그렇군요?
테스트 코드는 어떻게 통과했는지 잠시 당황스러워 집니다.
고치도록 하겠습니다.

2021-05-16 07:34 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
> +    }
하나하나 피드백을 달아주시다니 ㅜㅠ
코니 너무너무 감사해요! 많은 도움이 되고 있습니다!

2021-05-16 08:11 UTC, choihz commented on src/main/java/wooteco/subway/line/LineController.java
>      public ResponseEntity<LineResponse> createLine(@RequestBody LineRequest lineRequest) {
```
HTTP/1.1 400 
Connection: close
Content-Length: 44
Content-Type: application/json
Date: Sun, 16 May 2021 08:10:23 GMT

알 수 없는 에러가 발상했습니다.
```

```
PreparedStatementCallback; Referential integrity constraint violation: "CONSTRAINT_A03: PUBLIC.SECTION FOREIGN KEY(UP_STATION_ID) REFERENCES PUBLIC.STATION(ID) (1)"; SQL statement:
insert into SECTION (line_id, up_station_id, down_station_id, distance) values (?, ?, ?, ?) [23506-200]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_A03: PUBLIC.SECTION FOREIGN KEY(UP_STATION_ID) REFERENCES PUBLIC.STATION(ID) (1)"; SQL statement:
insert into SECTION (line_id, up_station_id, down_station_id, distance) values (?, ?, ?, ?) [23506-200]
```

😢

2021-05-20 16:18 UTC, daum7766 commented
# 학습로그

- 테코톡 준비로 인하여 공부시간이 부족했다. 방학때 추가적인 공부가 필요하다.



## 테스트 격리

- 테스트를 진행하니 테스트끼리 간섭을 일으켜 독릭접으로 실행했을 때는 통과했으나 전체를 테스트하니 실패하는 현상이 일어남
- 테스트끼리의 간섭이 생겼기 때문에 일어난 일이었으며, 이것을 해결하기 위해 테스트들 간의 격리가 필요해짐
- 순서를 보장하여 일시적으로 회피할 수 있지만 유지보수에서 비용이 크게 증가함으로 추천하지 않는 방식임
- 테스트를 위해 여러가지 방법을 시도해 보았으며 아래와 같은 일들이 있었다.
  - @Transectional : 테스트에서는 해당 테스트가 끝나면 데이터를 롤백시킨다. 그렇지만 auto_increment는 영향을 받아 id로 접근을 해야한다면 사용이 힘들다
  - @BeforeEach or @AfterEach 사용 : 매번 데이터를 초기화 시켜주는 방법이며, 모든 상황에서 대처가 가능하나 코드가 길어지는 단점이 생긴다.
  - @Sql : sql파일을 작성하여 해당 파일을 매 테스트마다 실행시킴
  - Entity Manager 사용법이 있다고 하는데 시간이 부족하여 공부하지 못함(방학때 하기)





## 스프링 사용법

- 확인과 함께 Response 데이터를 보낼때 아래와 같이 달라짐

```java
return ResponseEntity.ok().body(response);

return ResponseEntity.ok(response);
```

- ResponseEntity에 내용을 보내지 않을때 아래와 같이 처리`<Void>`

```java
public ResponseEntity updateLine(@PathVariable Long id, @RequestBody LineRequest lineRequest) {
...
}
    
public ResponseEntity<Void> updateLine(@PathVariable Long id, @RequestBody LineRequest lineRequest) {
...
}
```



## 테스트 사용법

- 객체간 비교코드를 추가하지 않더라도 비교를 해주는 메서드가 존재함
- usingRecursiveComparison() 메서드를 이용하면 된다.
- 현재 LineResponse는 비교코드가 정의되어 있지 않은 상태이다.

```java
assertThat(lineResponse).usingRecursiveComparison()
            .isEqualTo(new LineResponse(1L, "2호선", "bg-green-600"));
```

- 입력가능한 인자가 똑같다면 테스트코드는 메서드 체이닝을 통해 한번에 처리가 가능함

```java
assertThat(lines).hasSize(3);
assertThat(lines).containsExactly(line2, line3, line4);


assertThat(lines).hasSize(3)
            .containsExactly(line2, line3, line4);
```

- 리스트에 단 하나의 데이터만 있다면 이렇게 처리가 가능하다.

```java
assertThat(sectionService.findByLineId(1L).getSections()).hasSize(1)
            .usingRecursiveComparison()
            .isEqualTo(Collections.singletonList(new Section(1L, 1L, 4L, 10)));

assertThat(sectionService.findByLineId(1L).getSections()).hasSize(1)
    .containsOnly(new Section(1L, 1L, 4L, 10));
```





## 생성응답에 url을 넣지 못할경우

- 생성시 Location에 URI를 담아서 보내야 하는데 해당 URI를 담지 못할경우 정답이 없지만 불필요한 url을 담아서 클라이언트에게 혼란을 유발하는 것이 아니라 200으로 처리를 하는것이 좋다고 한다.

2021-05-20 16:19 UTC, daum7766 commented
# 학습로그



## public cloud 사용이유

- 사용자는 우리가 어떤 방식으로 서비스를 제공하는지 궁금해 하지 않는다
- public cloud를 이용하여 우리는 관심사를 분리하여 집중할 대상에게 보다 집중할 수 있다
- 개인PC, 사무실, 데이터센터 등을 이용할때 생기는 문제점을 신경쓰지 않아도 된다.



## 포트포워딩

- 특정 포트로 들어오는것을 원하는 포트와 연결을 해준다.
- 클라이언트와 서버를 해킹으로부터 보호하고 시스템을 개선하는데 도움을 준다.
  - 서버를 숨길 수 있다.
- 네트워크에서 원하지 않는 트래픽을 보호할 수 있다.(연결한 포트만 접속가능)



## 컨테이너

- 기존의 가상화 기술은 하이퍼바이저를 이용해 여러 개의 운영체제를 하나의 호스트에서 생성해 사용하는 방식이었다. 다수의 운영체제를 올려서 사용했기 때문에 일반 Host에 비해 성능의 손실이 발생했다. 운영체제를 사용하기 위해 필요한 라이브러리, 커널 등의 많은 정보가 필요했기 때문이다. 우리의 목적은 특정 환경에 종속되지 않은 상태로 애플리케이션을 띄우는 것으로 OS까지 운영하는 것은 낭비였다.
- 컨테이너는 호스트 커널을 공유해 사용하고 컨테이너 안에는 애플리케이션을 구동하는데 필요한 라이브러리 및 실행파일만 존재하게 함으로써 이미지의 용량을 줄일 수 있게 되었다

 



## 베스천 서버

- 메인서버를 지키기 위한 서버이다.
- 메인서버는 bastion서버에서 들어갈 수 있도록 변경을 하고 작업을 함으로써 보안성을 높인다. 
- 문제가 생기더라도 bastion서버만 재구축을 함으로써 문제가 발생할 여지를 줄일 수 있다.

 

## 프록시

- 클라이언트와 서버간의 중계서버로 통신을 대리 수행하는 서버
- 캐시/보안(포트포워딩)/트래픽분산(로드밸런싱) 등 가능하다.

- Forward Proxy
  - 클라이언트와 인터넷 사이에 위치
- Revers Proxy
  - 인터넷과 서버 사이에 위치한다.
  - 서버 정보를 클라이언트로부터 숨길 수 있다.(포워딩을 통해 서버는 자신의 주소를 노출시키지 않을 수 있다.)
  - 로드밸런싱 기능을 한다.(부하분산)
    - L4의 로드밸런싱 : 서버A, 서버 B로 로드밸런싱
    - L7의 로드밸런싱 : http/https/tcp , url에 따라서 다르게 처리 등

2021-05-22 16:40 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineController.java
>      public ResponseEntity<LineResponse> createLine(@RequestBody LineRequest lineRequest) {
없는 노선에 추가할때, 없는 역을 포함할 때 예외처리 했습니다!

2021-05-22 19:09 UTC, daum7766 commented
안녕하세요 코니!

다른미션과 발표가 겹쳐서 피드백 반영이 늦었습니다 ㅜㅠ

수정한 내용입니다.
1. 에러를 출력하기 위해 sout이 아닌 log를 이용했습니다.
2. 없는 노선에 구간을 추가할 때, 없는 역을 구간에 포함할 때 에러 상황을 추가했습니다.
3. 에러 메시지를 세분화 하였습니다.
4. section 생성디 201 created가 아닌 200 ok로 변경하였습니다.
5. Station path를 requestMapping을 이용하여 class공통으로 올렸습니다.
6. line 전체조회용 response를 만들어 stations에 접근하지 않도록 변경했습니다.
7. [링크](https://github.com/woowacourse/atdd-subway-map/pull/161#discussion_r632997753) findById에서 2가지 일을 하지않도록 변경하였습니다.
8. request와 domain객체의 id를 final로 변경하고 리플렉션이 아닌 객체를 새로 생성하도록 변경하였습니다.
9. 상수 네이밍을 컨벤션에 맞춰서 수정했습니다.
10. 일급컬렉션에서 dto로 변경하지 않도록 수정했습니다.
11. line과 section을 분리하였습니다.
12. service가 service를 가지고 있지 않고 dao를 가지고 있도록 변경했습니다.


진행하며 생긴 궁금증입니다.


1. 순환 참조를 방지하기 위해 service가 service를 들고 있지 않고 dao를 들고 있도록 변경했습니다.
그랬더니 LineService에서 Line을 생성하기 위해 필요한 Section을 만들기 위한 로직이 들어가게 되었는데
이것이 책임에 맞는지 고민입니다.

2. 인수 테스트를 할 때 노선과 구간을 테스트 하기 위해 Station을 추가합니다. 같은 역을 계속 추가해서 상수화를 하였는데 각 클래스마다 같은 상수가 존재합니다. 이것은 중복으로 봐야 할까요?

3. 테스트를 하다가 중복이 생긴 부분을 추출하다 보면 테스트 클래스마다 겹치는 함수가 생깁니다. 이것 역시 상수와 마찬가지로 중복으로 봐야할까요? 


감사합니다.

2021-05-23 17:04 UTC, choihz approved these changes
안녕하세요, 멍토!

피드백을 잘 반영해 주셨네요~ 지하철 노선도 관리 미션은 여기서 마치도록 할게요. 그동안 고생 많으셨고, 다음에 또 만나요! 👋

2021-05-23 17:04 UTC, choihz commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    }
아래에 있는 `downStationId에 0을 입력하여 노선을 생성하면 에러가 출력된다.` 테스트와 거의 동일하네요. `@ParameterizedTest` 사용해도 되지 않을까요?

2021-05-23 17:04 UTC, merged

2021-05-23 17:20 UTC, daum7766 commented on src/main/java/wooteco/subway/line/LineService.java
> +            Collectors.toList());
StationResponse가 List<StationResponse>를 만드는게 어색하다고 느껴저서 위와 같이 바꾸었었습니다.
Stations에 stream이 있으니 반복이 가능한 것처럼 보이기는 하네요 ㅜㅠ
변경하도록 하겠습니다!

2021-05-23 17:21 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationDao.java
>      }
내부에서 boolean으로 반환하고 싶었는데 IF쿼리를 넣으니 동작을 하지 않았습니다.
외부로 빼서 바꾸도록 하겠습니다!

2021-05-23 17:22 UTC, daum7766 commented on src/test/java/wooteco/subway/UnitTest.java
> +public class UnitTest {
고민하고 변경하도록 하겠습니다.

2021-05-23 17:23 UTC, daum7766 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    private static final Station SILLIM_STATION = new Station(4L, "신림역");
좋은 내용이네요!
감사합니다!!

2021-05-23 17:23 UTC, daum7766 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    }
null과 0을 한번에 넣는 방법을 찾지 못해서 분리를 하게 되었는데 방법이 있을까요?

2021-05-23 17:26 UTC, choihz commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    }
`@NullSource` 되지 않나요? ([Guide to JUnit 5 Parameterized Tests](https://www.baeldung.com/parameterized-tests-junit-5))

2021-05-23 17:51 UTC, daum7766 commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    }
찾아보고 적용해보겠습니다!

2021-06-17 10:48 UTC, daum7766 commented on src/main/java/wooteco/subway/station/StationController.java
> +@RequestMapping(value = "/stations", produces = MediaType.APPLICATION_JSON_VALUE)
필요 없습니다!
해당 내용은 공부하여 정리하였습니다. 감사합니다.
https://mungto.tistory.com/435