[Spring 지하철 노선도 관리 - 1, 2단계] 인비(김태희) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #64
Opened 2021-05-04 13:26 UTC by taehee-kim-dev

안녕하세요, 재연링!!

처음 뵙겠습니다!!

지하철 미션으로 만나게 되어 정말 반갑습니다. 😄 

ATDD를 처음 접해봐서, 잘 맞게 구현한건지 모르겠네요. 😅 

프론트 부분도 완성도 높게 만들어져 있어, 더욱 재밌는 미션이었습니다!!

소중한 시간 내어 리뷰해 주셔서 감사합니다. 

잘 부탁드립니다!! 🙇

2021-05-05 11:36 UTC, jaeyeonling requested changes
안녕하세요 인비! 지하철 노선도 관리 미션을 함께 할 재연링입니다~
요구사항에 맞게 잘 구현해주셨어요 👍 
질문의 답변과 추가적인 코멘트 남겨두었으니 확인 부탁드릴게요 :)

2021-05-05 11:36 UTC, jaeyeonling commented on src/main/java/wooteco/subway/controller/StationController.java
> +    public ResponseEntity deleteStationById(@PathVariable Long id) {
```suggestion
    public ResponseEntity<Void> deleteStationById(@PathVariable Long id) {
```

제네릭의 타입을 명시해주지 않을 경우 기능은 큰 차이가 없지만 컴파일 경고가 발생하게 되는데요!
컴파일 경고를 통해 매우 유용한 정보들을 많이 받을 수 있지만, 위와 같은 코드들로  불필요한 경고가 많아질 경우 개발자는 경고를 안보게 되는 문제가 발생합니다!
컴파일 시 경고가 발생한다면 바로바로 수정하는 습관을 들인다면 불필요한 버그를 줄이는데 도움이 될 것 같습니다 :)

2021-05-05 11:36 UTC, jaeyeonling commented on src/main/java/wooteco/subway/controller/advice/AdviceController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
표준 예외를 ExceptionHandler로 예외처리 할 경우, 인비가 의도하지 않은 곳에서 표준 예외 발생 시 클라이언트에 올바르지 않은 정보를 전달할 수 있습니다
모든 IllegalArgumentException가 Bad Request라는 것을 보장할 수 있을지 고민해보고, 해당 서비스의 예외는 따로 분리해보면 어떨까요!?

2021-05-05 11:36 UTC, jaeyeonling commented on src/main/java/wooteco/subway/dao/LineDao.java
> +
```suggestion
public class LineDao {
    private final JdbcTemplate jdbcTemplate;
    private final RowMapper<Line> lineRowMapper = (resultSet, rowNum) ->
        new Line(
            resultSet.getLong("id"),
            resultSet.getString("name"),
            resultSet.getString("color"));

    public LineDao(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }
```

클래스의 구현순서를

```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

순으로 작성해주시면 가독성이 상승합니다 :)

2021-05-05 11:36 UTC, jaeyeonling commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        return Optional.ofNullable(result);
Optional 👍

2021-05-05 11:36 UTC, jaeyeonling commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +class LineAcceptanceTest extends AcceptanceTest {
Q. 단위테스트? 인수테스트?
인수테스트(End to End 테스트)를 하니, 단위테스트와 혼동돼요.

결국 우리가 하고자 하는 것이 요구사항에 맞는 프로그램 개발 이라면,
인수테스트가 이 목적에 가장 적합한 테스트 아닐까? 라는 생각이 들어요.

근데 인수테스트는 특정 API 요청 직후의 데이터 저장 상태를 DAO에서 직접 꺼내서 확인하면 안되더라구요.
이런 부분은 순수하게 개발자 입장에서 봤을 때, 모든 검증을 API로 해야 하니 불편했어요.

"왜 DAO를 가져와서 직접 꺼내서 확인하면 안될까? 그럼 더 편한데.." 라는 생각이 들었어요.

포비에게 물어보니, 인수테스트는 DAO의 의존성을 갖지 않는게 좋기 때문에
모든 것을 API 요청과 응답으로 검증해야 한다고 하더라구요.

열심히 구글링 해 보고 있는데, 왜 굳이 그렇게 해야 하는지 모르겠어요.
"그냥 인수테스트 라는게 원래 그런건가?" 라는 생각도 들고요.

여러가지 테스트를 배우고 미션에 적용하다보니 혼란스럽네요.. 😢
"그럼 도대체 단위 테스트의 단위는 뭘까?" 라는 궁금증도 다시 생겼네요.

개발의 많은 부분들이 그렇듯, "상황과 목적에 맞게, 단위는 생각하기 나름" 인 걸까요?

재연링의 의견이 궁금해요!!

A.
먼저 E2E테스트와 인수테스트의 개념을 집고 넘어가면 혼란이 적을 것 같은데요!

E2E테스트: 해당 시스템의 전체적인 프로세스를 확인하는 테스트
인수테스트: 요구사항에 맞춰 비즈니스 관점에서의 테스트

테스트의 개념들과 개발자가 작성하는 테스트의 종류와 1:1로 매칭되는 것이 아닌 하나의 테스트로 여러 조건을 만족할 수 있고, 일반적으로 E2E테스트는 인수테스트 범위에 들어간다고 볼 수 있습니다
위 개념으로 본다면 테스트코드의 목적은 시스템의 전체적인 프로세스 테스트를 비즈니스 관점에서 한다! 보시면 될 것 같네요

본론으로 돌아와서 말씀해주신 내용은 `테스트`에 집중하여 접근한다면 원하는 결과를 DB를 통해 정확히 검증할 수 있고 편리하다고 말씀하시는 것 같은데요!
테스트가 아닌 `비즈니스 관점`에 집중하여 접근한다면 이해하는데 도움이 될 수 있을 것 같습니다

`비즈니스 관점`에서는 해당 데이터가 어떠한 방식으로 DB에 저장되는지는 중요하지 않습니다!
클라이언트 입장에서 API의 사이클을 통해 `비즈니스 로직`을 검증하는 과정이기 때문에 DB를 사용하여 검증하는 것은 인수테스트의 목적에 벗어나게 된다! 라는 것이 제 생각입니다 ㅎㅎ

2021-05-05 11:36 UTC, jaeyeonling commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +    @DisplayName("노선을 생성한다.")
위 질문과 연관이 되는 리뷰인데요!
해당 테스트는 `노선 생성`이기 때문에 생성 요청에 대한 응답으로만 검증을 끝내주셔도 좋을 것 같습니다!

지금 작성된 테스트의 DisplayName은 노션 생성 후 모든 노션 조회 시 조회된다. 가 더욱 적절할 것 같네요 :)

2021-05-05 11:36 UTC, jaeyeonling commented on src/test/java/wooteco/subway/station/StationAcceptanceTest.java
> +            .delete("/stations/" + stationIdToDelete)
```suggestion
            .delete("/stations/{stationId}", stationIdToDelete)
```

정확한 테스트 결과 확인을 위해 위와 같이 작성해보면 어떨까요!?

2021-05-05 12:32 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/controller/LineController.java
> +    @PostMapping(value = "/lines",
뺄까 말까 고민을 많이 했는데, 역시 빼는게 더 좋군요!! :)

2021-05-05 12:35 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/service/LineService.java
> +        return new LineResponseDto(foundLine);
오 확실히 더 깔끔하네요!!! 감사합니다. :)

2021-05-05 12:36 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/service/LineService.java
> +            throw new IllegalArgumentException("이미 존재하는 노선 색깔입니다.");
DB 테이블 컬럼에도 UNIQUE 제약조건을 추가해 주는게 확실히 더 안전하고 좋겠네요!! 감사합니다. :)

2021-05-05 12:41 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
오!! 그렇네요. 모든 필드가 final인게 확실히 더 안정감을 주는 것 같아요. 감사합니다. :)

2021-05-05 12:49 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/controller/StationController.java
> +    public ResponseEntity deleteStationById(@PathVariable Long id) {
이 부분을 페어와도 얘기하다가, Body가 없으니 제네릭을 선언하지 않는 것이 맞지 않냐는 의견에 위와 같이 작성했어요. 재연링의 피드백 대로 Void가 있는 줄은 몰랐네요ㅠ. 좋은 피드백 감사합니다! :)

2021-05-05 12:53 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/dao/LineDao.java
> +
앗, rowMapper가 함수처러 생겨 실수를 했네요. 😅 
꼼꼼한 피드백 정말 감사합니다. 🙇

2021-05-05 12:56 UTC, taehee-kim-dev commented on src/test/java/wooteco/subway/line/LineAcceptanceTest.java
> +class LineAcceptanceTest extends AcceptanceTest {
API 요청을 통한 __비즈니스 관점__ 에서의 테스트라서 그런 거군요!! 명쾌한 답변 정말 감사드립니다. 🙇 🙏

2021-05-05 12:58 UTC, taehee-kim-dev commented on src/test/java/wooteco/subway/station/StationAcceptanceTest.java
> +            .delete("/stations/" + stationIdToDelete)
오, 이런 방식도 가능하군요. 더욱 명시적이고 깔끔하네요!! 꿀팁 감사합니다!! 😆

2021-05-05 13:10 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/controller/advice/AdviceController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
아, 정말 그렇네요. BadRequest를 반환하기 위한 Exception을 따로 분리해서 처리해야 겠네요. 좋은 피드백 감사합니다. :)

2021-05-06 07:36 UTC, taehee-kim-dev commented
### 안녕하세요, 재연링!!

코드리뷰 코멘트와 DM 답변으로 받은 피드백들을 반영했습니다.

동시성 문제로 인해 중복 검사를 서비스 레이어 로직에서 제거하고, DB TABLE의 UNIQUE 제약 조건에 의존하도록 했습니다. DAO의 쿼리 실행문에서 `DuplicateKeyException`을 catch하여 커스텀 Exception인 `BadRequestException`으로 다시 던지도록 했습니다. 이 부분 괜찮은지 한 번 봐주시면 감사하겠습니다.

소중한 피드백과 DM 답변 정말 감사합니다!! 🙇

2021-05-07 03:53 UTC, jaeyeonling approved these changes
코멘트 내용을 잘 반영해주셨습니다 💯 
질문의 답변 남겨두었으니 확인해주시고 다음 단계에 반영해주세요 😄

2021-05-07 03:53 UTC, jaeyeonling commented on src/main/java/wooteco/subway/controller/advice/AdviceController.java
> +    @ExceptionHandler(BadRequestException.class)
피드백을 잘 반영해주셨네요 👍 
하지만 아직 HttpStatus마다 ExceptionHandler를 만들어야한다는 단점이 남아있네요!

```
Exception {
  HttpStatus httpStatus();
  HttpHeaders headers();
  Object body();
}
```

커스텀 익셉션을 위와 같은 구조로 만든다면 하나로 핸들링 할 수 있을 것 같은데 어떻게 생각하시나요!?
위 코드는 간단히 작성하였으니 참고만 해주세요 ㅎㅎ

2021-05-07 03:53 UTC, merged

2021-05-07 06:49 UTC, taehee-kim-dev commented
### 감사합니다, 재연링!!

피드백 반영해서 3단계 때 같이 제출할게요!!

감사합니다. 🙇

2021-05-17 04:39 UTC, taehee-kim-dev commented
### 학습로그
- [우아한테크코스 3기 백엔드 Lv2 [지하철 미션] 학습로그](https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EC%A7%80%ED%95%98%EC%B2%A0-%EB%AF%B8%EC%85%98-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8)

2021-05-17 06:00 UTC, taehee-kim-dev commented
### 배포 인프라 학습로그
- [우아한테크코스 3기 백엔드 Lv2 [배포 인프라] 학습로그](https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EB%B0%B0%ED%8F%AC%EC%9A%B4%EC%98%81-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8)