[Spring 지하철 노선도 관리 - 1, 2단계] 아마찌(신지혜) 미션 제출합니다.
woowacourse/atdd-subway-map pull request #86
Opened 2021-05-06 03:21 UTC by NewWisdom

안녕하세요 게이츠! 아마찌입니다! 
레벨 1때도 만났었는데, 레벨 2에서 지하철 미션으로 다시 만나뵙네요! 
다시 만나뵙게되어 정말 반갑습니다 👏

이전 미션까지는 MockMVC로 단위 테스트를 진행했는데,  
이번 미션에서는 RestAssured로 end to end 테스트를 진행했어요! 
MockMVC와 RestAssured로 테스트 하는 것이 어떤 차이가 있는지도 학습할 수 있었던 시간이었습니다! 

이번 미션, 잘 부탁드립니다 🙌
리뷰에 귀한 시간 내주셔서 정말 감사드려요 🙇‍♂️

2021-05-08 22:25 UTC, serverwizard requested changes
아마찌! 다시 한번 리뷰를 맡은 (빌)게이츠입니다. 😄

요구사항에 맞춰 기능 구현을 잘 해주셨어요. 👍
간단한 코멘트 몇 가지 남겼는데, 확인 부탁드릴게요! 

코멘트 참고해보시고 추가적으로 궁금한 부분 있으시면 언제든 DM 주세요

2021-05-08 22:25 UTC, serverwizard commented on src/main/java/wooteco/subway/line/LineController.java
> +@RequestMapping("/lines")
참고로 실무에서는 /api/v1(버전)/lines 식으로 버전 정보도 명시해준답니다.

API URI에 버전 정보를 붙여주는 이유는
v1으로 만든 API를 운영에 배포한 상태에서, 요구사항이 변경된 경우 v1을 수정하는게 아니라(행여 기존에 해당 API를 사용하고 있는 서비스에 영향을 주지 않기 위함) v2를 새로 만드는 식으로 하기 위함이에요.

2021-05-08 22:25 UTC, serverwizard commented on src/main/java/wooteco/subway/line/MemoryLineDao.java
> +        if (findByName(line.name()).isPresent()) {
Line의 이름과 색상(Line의 데이터) 중복 여부를 Line에게 위임해서 처리하게는 할 수 없을까요?

2021-05-08 22:25 UTC, serverwizard commented on src/test/java/wooteco/subway/line/DBLineDaoTest.java
> +        assertThat(line.color()).isEqualTo(color);
객체와 객체끼리 비교를 한다면 한 줄로 줄일 수도 있겠네요~

2021-05-08 22:25 UTC, serverwizard commented on src/test/java/wooteco/subway/line/LIneAcceptanceTest.java
> +        params.put("color", "bg-red-600");
데이터를 Map타입이 아니라 DTO타입으로 전달하면은 안되는 걸까요?

2021-05-08 22:25 UTC, serverwizard commented on src/test/java/wooteco/subway/line/LIneAcceptanceTest.java
> +                .extract();
아래와 같은 코드가 반복적으로 사용되고 있는 것 같은데요.
메소드로 추출하여 중복을 제거해보는 건 어떨까요?
```
    RestAssured.given().log().all()
                .body(파라미터)
                .contentType(미디어타입)
                .when()
                .post("경로")
                .then().log().all()
                .extract();
```

2021-05-08 22:25 UTC, serverwizard commented on src/test/java/wooteco/subway/name/LineNameTest.java
> +class LineNameTest {
도메인객체 테스트 👍

2021-05-08 22:25 UTC, serverwizard commented on src/main/java/wooteco/subway/line/MemoryLineDao.java
> +        Line findLine = findById(id).orElseThrow(() -> new IllegalArgumentException("없는 노선임!"));
현재 아래와 같은 코드가 반복되고 있는데요.
차라리 findById( ) 내부에서 Exception을 발생시키는건 어떨까요?
```
findById(id).orElseThrow(() -> new IllegalArgumentException("없는 노선임!"));
```

2021-05-08 22:25 UTC, serverwizard commented on src/main/java/wooteco/subway/name/StationName.java
> +public class StationName implements Name {
원시값 포장 👍

2021-05-08 22:25 UTC, serverwizard commented on src/main/java/wooteco/subway/station/MemoryStationDao.java
> +    private static Long seq = 0L;
꼭 필요한 값일까요?

2021-05-09 07:20 UTC, NewWisdom commented on src/main/java/wooteco/subway/line/LineController.java
> +@RequestMapping("/lines")
이 부분은 구현 단계에서 고민했었던 부분이었는데,
미션에서 주어진 프론트엔드 API 요청이 이미 있기 때문에 
컨트롤러 부분만 API를 변경할 수는 없었어요 🥲
앞으로 API를 설계하는데 참고하겠습니다 감사합니다!

2021-05-09 07:27 UTC, NewWisdom commented on src/main/java/wooteco/subway/station/MemoryStationDao.java
> +    private static Long seq = 0L;
이부분은 미션 기본 템플릿으로 주어진 부분인데요,
저는 Static 메모리를 사용할 때 여기서는 DB처럼 index가 설정되지 않으니,
주어진 seq가 DB의 index역할을 한다고 생각했어요!
객체를 저장할 때도 seq 값을 증가시키구요!! 
MemoryDB를 구현하기 위해서는 이러한 부분에서 필요한 값이라고 생각했는데, 
불필요한 값일까요???

2021-05-09 07:29 UTC, NewWisdom commented on src/test/java/wooteco/subway/line/LIneAcceptanceTest.java
> +                .extract();
테스트코드의 중복된 메서드를 추출할 수 있다는 사실을 간과하고 있었던 것 같아요! 
중복된 부분은 메서드로 추출하였습니다! 감사합니다

2021-05-09 08:08 UTC, NewWisdom commented on src/main/java/wooteco/subway/line/MemoryLineDao.java
> +        if (findByName(line.name()).isPresent()) {
Line 객체가 가지고 있는 것은 자신의 이름과 색상인데,
중복 여부를 Line에게 위임한다는 것은  Line이 List Line에 있는 
다른 Line들의 이름을 알아야한다는 것으로 게이츠의 리뷰를 이해했어요!ㅎㅎ
현재 이름이 주어졌을 때 line 객체 내부에서 sameName으로 판단하고 있어 객체에게 메시지를 통해
같은 이름인지 확인하고 있다고 생각했는데 다른 의도를 말씀하신걸까요???

2021-05-09 09:00 UTC, NewWisdom commented on src/main/java/wooteco/subway/line/MemoryLineDao.java
> +        Line findLine = findById(id).orElseThrow(() -> new IllegalArgumentException("없는 노선임!"));
dao에서는 optional로 싼 객체를 반환하고, 
서비스단에서 이에 대한 처리를 해주도록 변경하였습니다 !
감사합니다!

2021-05-09 09:01 UTC, NewWisdom commented on src/test/java/wooteco/subway/line/DBLineDaoTest.java
> +        assertThat(line.color()).isEqualTo(color);
hashCode, equals를 통해 객체를 비교할 수 있도록 하였습니다!

2021-05-10 00:35 UTC, serverwizard commented on src/main/java/wooteco/subway/station/MemoryStationDao.java
> +    private static Long seq = 0L;
제가 2단계 미션 요구사항인 `DB에서 데이터를 관리한다`만 보고 말씀드린 것 같아요.
이 부분은 그냥 skip하셔도 될 것 같아요.
혼란을 드려 죄송해요!

2021-05-13 23:15 UTC, serverwizard approved these changes
피드백 반영을 잘해주셨네요. 👍 

이번 단계는 여기서 머지할게요. 추가로 남긴 피드백은 다음 단계때 같이 반영해주시면 됩니다!

궁금한건 언제든 질문 주세요. 😉

2021-05-13 23:15 UTC, merged